### ISSUE TITLE
Typo in guide?

### ISSUE THREAD

**Issue by szhang1121** [mlverse/torch#1001]
On the "Get Technical" page, "Network from scratch" (https://torch.mlverse.org/technical/network/), it says the following about the weights:

> There are two types of weights. The first, the one we often restrict the term weights to, is different for each connection. So if we want a hidden layer with 32 units, we need a weight matrix of shape 100 (number of observations) by 32.

Should it be shape 3 (dimension of observations) by 32?

**Comment by dfalbel** [comment]
You are definitely right! Should be fixed in https://github.com/mlverse/torch/commit/7aefa6f9c02962db4114ae4fdca4202baa0287d2
