### ISSUE TITLE
Torch not installing lantern error 

### ISSUE THREAD

**Issue by karinkumar** [mlverse/torch#1002]
After installing torch on cran/github I am trying to install the additional dependencies. There appears to be an issue with lantern. I was able to install lantern successfully  on a cluster but not on my personal laptop. I was getting this error. Does anyone know how to resolve it?

Error in cpp_lantern_init(file.path(install_path(), "lib")) : 
  /Library/Frameworks/R.framework/Versions/4.1/Resources/library/torch/lib/liblantern.dylib - dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/torch/lib/liblantern.dylib, 10): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/torch/lib/liblantern.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

**Comment by dfalbel** [comment]
Can you provide the output of `sessioninfo::session_info()`? I think this might be related to liblantern pre-built binaries being built on a different macOS version.

Thank you!

**Comment by karinkumar** [comment]
Thank you for your quick response! Here is the output as requested.


sessioninfo::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       macOS Big Sur 11.6.5
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Detroit
 date     2023-03-29
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   2.18 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/tools/ (via rmarkdown)

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package           * version    date (UTC) lib source
   abind               1.4-5      2016-07-21 [1] CRAN (R 4.1.0)
   arm                 1.12-2     2021-10-15 [1] CRAN (R 4.1.0)
   assertthat          0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
   backports           1.4.1      2021-12-13 [1] CRAN (R 4.1.0)
   base64enc           0.1-3      2015-07-28 [1] CRAN (R 4.1.0)
   bit                 4.0.4      2020-08-04 [1] CRAN (R 4.1.0)
   bit64               4.0.5      2020-08-30 [1] CRAN (R 4.1.0)
   boot                1.3-28     2021-05-03 [1] CRAN (R 4.1.0)
   callr               3.7.0      2021-04-20 [1] CRAN (R 4.1.0)
   checkmate           2.1.0      2022-04-21 [1] CRAN (R 4.1.2)
   cli                 3.3.0      2022-04-25 [1] CRAN (R 4.1.2)
   cluster             2.1.2      2021-04-17 [1] CRAN (R 4.1.3)
   clusterGeneration   1.3.7      2020-12-15 [1] CRAN (R 4.1.0)
   coda                0.19-4     2020-09-30 [1] CRAN (R 4.1.3)
   codetools           0.2-18     2020-11-04 [1] CRAN (R 4.1.3)
   colorspace          2.0-3      2022-02-21 [1] CRAN (R 4.1.2)
   coro                1.0.3      2022-07-19 [1] CRAN (R 4.1.2)
   corpcor             1.6.10     2021-09-16 [1] CRAN (R 4.1.0)
   crayon              1.5.1      2022-03-26 [1] CRAN (R 4.1.3)
   curl                4.3.2      2021-06-23 [1] CRAN (R 4.1.0)
   data.table        * 1.14.2     2021-09-27 [1] CRAN (R 4.1.0)
   DBI                 1.1.2      2021-12-20 [1] CRAN (R 4.1.0)
   dbscan              1.1-11     2022-10-27 [1] CRAN (R 4.1.2)
   digest              0.6.29     2021-12-01 [1] CRAN (R 4.1.0)
   dplyr               1.0.8      2022-02-08 [1] CRAN (R 4.1.2)
   ellipsis            0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
   evaluate            0.15       2022-02-18 [1] CRAN (R 4.1.2)
   fansi               1.0.3      2022-03-24 [1] CRAN (R 4.1.2)
   fastDummies         1.6.3      2020-11-29 [1] CRAN (R 4.1.0)
   fastmap             1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
   fdrtool             1.2.17     2021-11-13 [1] CRAN (R 4.1.0)
   flexmix           * 2.3-18     2022-06-07 [1] CRAN (R 4.1.2)
   foreach             1.5.2      2022-02-02 [1] CRAN (R 4.1.2)
   foreign           * 0.8-82     2022-01-13 [1] CRAN (R 4.1.2)
   Formula             1.2-4      2020-10-16 [1] CRAN (R 4.1.0)
   fossil            * 0.4.0      2020-03-23 [1] CRAN (R 4.1.0)
   funtimes            9.0        2022-09-08 [1] CRAN (R 4.1.2)
   generics            0.1.2      2022-01-31 [1] CRAN (R 4.1.2)
   ggplot2             3.3.6      2022-05-03 [1] CRAN (R 4.1.2)
   glasso              1.11       2019-10-01 [1] CRAN (R 4.1.0)
   glmnet              4.1-6      2022-11-27 [1] CRAN (R 4.1.2)
   glue                1.6.2      2022-02-24 [1] CRAN (R 4.1.2)
   graphicalVAR        0.3        2021-10-19 [1] CRAN (R 4.1.0)
   gridExtra           2.3        2017-09-09 [1] CRAN (R 4.1.0)
   gsubfn              0.7        2018-03-16 [1] CRAN (R 4.1.0)
   gtable              0.3.0      2019-03-25 [1] CRAN (R 4.1.0)
   gtools              3.9.2      2021-06-06 [1] CRAN (R 4.1.0)
   Hmisc               4.7-0      2022-04-19 [1] CRAN (R 4.1.2)
   htmlTable           2.4.0      2022-01-04 [1] CRAN (R 4.1.2)
   htmltools           0.5.2      2021-08-25 [1] CRAN (R 4.1.0)
   htmlwidgets         1.5.4      2021-09-08 [1] CRAN (R 4.1.0)
   httr                1.4.2      2020-07-20 [1] CRAN (R 4.1.0)
   igraph              1.3.1      2022-04-20 [1] CRAN (R 4.1.2)
   iterators           1.0.14     2022-02-05 [1] CRAN (R 4.1.2)
   Jmisc               0.3.1.1    2022-06-22 [1] CRAN (R 4.1.2)
   jpeg                0.1-9      2021-07-24 [1] CRAN (R 4.1.0)
   Kendall             2.2.1      2022-03-20 [1] CRAN (R 4.1.2)
   knitr               1.39       2022-04-26 [1] CRAN (R 4.1.2)
   lattice           * 0.20-45    2021-09-22 [1] CRAN (R 4.1.3)
   latticeExtra        0.6-29     2019-12-19 [1] CRAN (R 4.1.0)
   lavaan              0.6-11     2022-03-31 [1] CRAN (R 4.1.2)
   lifecycle           1.0.1      2021-09-24 [1] CRAN (R 4.1.0)
   lme4                1.1-29     2022-04-07 [1] CRAN (R 4.1.2)
   magrittr            2.0.2      2022-01-26 [1] CRAN (R 4.1.2)
   maps              * 3.4.0      2021-09-25 [1] CRAN (R 4.1.0)
   MASS                7.3-57     2022-04-22 [1] CRAN (R 4.1.2)
   Matrix              1.4-1      2022-03-23 [1] CRAN (R 4.1.2)
   matrixStats       * 0.61.0     2021-09-17 [1] CRAN (R 4.1.0)
   minqa               1.2.4      2014-10-09 [1] CRAN (R 4.1.0)
   mlVAR               0.5        2021-10-25 [1] CRAN (R 4.1.0)
   mnormt              2.0.2      2020-09-01 [1] CRAN (R 4.1.0)
   modeltools          0.2-23     2020-03-05 [1] CRAN (R 4.1.0)
   MplusAutomation     1.1.0      2022-04-06 [1] CRAN (R 4.1.2)
   munsell             0.5.0      2018-06-12 [1] CRAN (R 4.1.0)
   mvtnorm             1.1-3      2021-10-08 [1] CRAN (R 4.1.0)
   nlme                3.1-157    2022-03-25 [1] CRAN (R 4.1.2)
   nloptr              2.0.0      2022-01-26 [1] CRAN (R 4.1.2)
   nnet                7.3-17     2022-01-16 [1] CRAN (R 4.1.3)
   numDeriv          * 2016.8-1.1 2019-06-06 [1] CRAN (R 4.1.0)
   pander              0.6.5      2022-03-18 [1] CRAN (R 4.1.2)
   pbapply             1.5-0      2021-09-16 [1] CRAN (R 4.1.0)
   pbivnorm            0.6.0      2015-01-23 [1] CRAN (R 4.1.0)
   pillar              1.7.0      2022-02-01 [1] CRAN (R 4.1.2)
   pkgbuild            1.3.1      2021-12-20 [1] CRAN (R 4.1.0)
   pkgconfig           2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
   plyr                1.8.7      2022-03-24 [1] CRAN (R 4.1.2)
   png                 0.1-7      2013-12-03 [1] CRAN (R 4.1.0)
   prettyunits         1.1.1      2020-01-24 [1] CRAN (R 4.1.0)
   processx            3.5.3      2022-03-25 [1] CRAN (R 4.1.2)
   proto               1.0.0      2016-10-29 [1] CRAN (R 4.1.0)
   ps                  1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
   psych               2.2.5      2022-05-10 [1] CRAN (R 4.1.2)
   purrr               0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
   qgraph              1.9.3      2022-12-09 [1] CRAN (R 4.1.2)
   R6                * 2.5.1      2021-08-19 [1] CRAN (R 4.1.0)
   rbibutils           2.2.8      2022-04-11 [1] CRAN (R 4.1.2)
   RColorBrewer        1.1-2      2014-12-07 [1] CRAN (R 4.1.0)
   Rcpp                1.0.9      2022-07-08 [1] CRAN (R 4.1.2)
   Rdpack              2.3        2022-03-23 [1] CRAN (R 4.1.2)
   remotes             2.4.2      2021-11-30 [1] CRAN (R 4.1.0)
   reshape2            1.4.4      2020-04-09 [1] CRAN (R 4.1.0)
   rlang               1.0.4      2022-07-12 [1] CRAN (R 4.1.2)
   rmarkdown           2.13       2022-03-10 [1] CRAN (R 4.1.2)
   rpart               4.1.16     2022-01-24 [1] CRAN (R 4.1.3)
   rprojroot           2.0.2      2020-11-15 [1] CRAN (R 4.1.0)
   rstudioapi          0.13       2020-11-12 [1] CRAN (R 4.1.0)
   scales              1.1.1      2020-05-11 [1] CRAN (R 4.1.0)
   sessioninfo         1.2.2      2021-12-06 [1] CRAN (R 4.1.0)
   shape               1.4.6      2021-05-19 [1] CRAN (R 4.1.0)
   shapefiles        * 0.7.2      2022-08-25 [1] CRAN (R 4.1.2)
   sp                * 1.4-6      2021-11-14 [1] CRAN (R 4.1.0)
   stringi             1.7.6      2021-11-29 [1] CRAN (R 4.1.0)
   stringr             1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
   survival            3.3-1      2022-03-03 [1] CRAN (R 4.1.2)
   texreg              1.38.6     2022-04-06 [1] CRAN (R 4.1.2)
   tibble              3.1.6      2021-11-07 [1] CRAN (R 4.1.0)
   tidyselect          1.1.2      2022-02-21 [1] CRAN (R 4.1.2)
   tmvnsim             1.0-2      2016-12-15 [1] CRAN (R 4.1.0)
 V torch             * 0.9.1      2023-03-28 [1] Github (mlverse/torch@dcec58c) (on disk 0.9.1.9001)
   utf8                1.2.2      2021-07-24 [1] CRAN (R 4.1.0)
   vctrs               0.4.1      2022-04-13 [1] CRAN (R 4.1.2)
   withr               2.5.0      2022-03-03 [1] CRAN (R 4.1.2)
   xfun                0.30       2022-03-02 [1] CRAN (R 4.1.2)
   xtable              1.8-4      2019-04-21 [1] CRAN (R 4.1.0)
   yaml                2.3.5      2022-02-21 [1] CRAN (R 4.1.2)

 [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library

 V ── Loaded and on-disk version mismatch.

**Comment by dfalbel** [comment]
Thank you for the info. Unfortunatelly, I think there's no easy way to install torch on old macOS versions. You need to build lantern locally for that to work.

Building locally requires:

- `cmake` should be on your path. eg try `cmake --version` to make sure you have it otherwise install it - `brew install cmake` should work.
- set the env var `BUILD_LANTERN=1`, eg `Sys.setenv(BUILD_LANTERN=1)`.
- then install torch from source: `remotes::install_github("mlverse/torch")`. The current CRAN version does not support installing this way unfortunatelly.

Another solution might be updating your macOS version, but I'm assuming you have other reasons not to do it.

**Comment by karinkumar** [comment]
Thanks! I actually just forgot my most recent update. I didn't have any
reason not to do it, so I updated my macOS and everything works!

**Comment by dfalbel** [comment]
Cool! Glad it worked :)
