### ISSUE TITLE
ISSUE with LibLantern on PC windows 10 (64)

### ISSUE THREAD

**Issue by Milardkh** [mlverse/torch#1006]
package "torch" was successfully installed. However, I have problems with installing LibLantern as the following shows:

install_torch(timeout = 1500)

trying URL 'https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.12.1%2Bcpu.zip'
Content type 'application/zip' length 149618648 bytes (142.7 MB)
downloaded 142.7 MB
trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.1/latest/Windows-cpu.zip'
Error in utils::download.file(library_url, temp_file) : 
  cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.1/latest/Windows-cpu.zip'
In addition: Warning messages:
1: In utils::download.file(library_url, temp_file) :
  downloaded length 0 != reported length 193
2: In utils::download.file(library_url, temp_file) :
  cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.1/latest/Windows-cpu.zip': HTTP status was '403 Forbidden'.

Additionally,
> sessionInfo()

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] torch_0.9.1
loaded via a namespace (and not attached):
 [1] processx_3.8.0  bit_4.0.5       compiler_4.2.2  R6_2.5.1        magrittr_2.0.3  cli_3.6.1       tools_4.2.2     withr_2.5.0     rstudioapi_0.14 Rcpp_1.0.10    
[11] bit64_4.0.5     coro_1.0.3      callr_3.7.3     ps_1.7.3        rlang_1.1.0

**Comment by dfalbel** [comment]
It seems that you don't have rights to download the file in [https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.1/latest/Windows-cpu.zip](https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.1/latest/Windows-cpu.zip) maybe a firewall is blocking it. 

You can download it manually and extract it into the `system.file(package="torch")` directory. Or use instruction like https://torch.mlverse.org/docs/articles/installation.html#file-based-download

**Comment by Milardkh** [comment]
Thank you so much for your quick response. I spent time to resolve the issue, but I wasn't able to do so. I manually downloaded [https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.1/latest/Windows-cpu.zip](url) and extracted it into its appropriate directory via the code, `system.file(package="torch").` However, it still asks me the question that  **Additional software needs to be downloaded and installed for torch to work correctly.,** when I activate the torch library. I am wondering If I extracted it into an appropriate location.

> system.file(package="torch")
[1] "C:/Users/Mashadservice.com/AppData/Local/R/win-library/4.2/torch"
> library(torch)
ℹ Additional software needs to be downloaded and installed for torch to work correctly.

the following image illustrates the location where I extracted the file. I encircled the file in red.
![Uploading
![LanternQuestion1](https://user-images.githubusercontent.com/122512785/230654025-8c757f20-cf29-4c42-8afe-979e14c16798.png)
 
I would like to express my great appreciation to you for your help. 
Regards,

**Comment by dfalbel** [comment]
Hi @Milardkh, 

I'm sorry, lantern.dll should be placed inside the lib directory.

**Comment by Milardkh** [comment]
Dear @dfalbel ,
Thank you very much for your help.

**Comment by dfalbel** [comment]
Happy to help! Hope it worked, please reopen or open a new issue if not. Best
