### ISSUE TITLE
Problem installing torch in window

### ISSUE THREAD

**Issue by agronomofiorentini** [mlverse/torch#1012]
I opened a github issue in the past, in which I wanted to report my inability to install torch in r.

After closed the github issue I was suggested to install the new version of torch and retry the installation but still I find problems in doing so.

#953 

I report below the information regarding my r session. I hope I have provided all the details to be able to reproduce the error and if anything else is needed, I am available

Session Info 

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.utf8  LC_CTYPE=Italian_Italy.utf8    LC_MONETARY=Italian_Italy.utf8 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10          pillar_1.9.0         compiler_4.2.0       tools_4.2.0          digest_0.6.31        bit_4.0.5            lattice_0.20-45     
 [8] evaluate_0.20        lifecycle_1.0.3      tibble_3.1.8         pkgconfig_2.0.3      rlang_1.0.6          DBI_1.1.3            cli_3.5.0           
[15] rstudioapi_0.14      yaml_2.3.7           xfun_0.37            coro_1.0.3           fastmap_1.1.1        terra_1.6-47         withr_2.5.0         
[22] dplyr_1.0.10         knitr_1.42           raster_3.6-20        desc_1.4.2           generics_0.1.3       vctrs_0.5.1          htmlwidgets_1.6.2   
[29] rprojroot_2.0.3      grid_4.2.0           bit64_4.0.5          DT_0.27              tidyselect_1.2.0     glue_1.6.2           data.table_1.14.6   
[36] R6_2.5.1             processx_3.8.0       fansi_1.0.3          rmarkdown_2.20       sp_1.6-0             callr_3.7.3          magrittr_2.0.3      
[43] codetools_0.2-18     ps_1.7.2             htmltools_0.5.4.9000 assertthat_0.2.1     torch_0.9.1.9001     utf8_1.2.2  
```

When i run the following code
```
torch::install_torch()
```

i have the following output
```
trying URL 'https://storage.googleapis.com/torch-lantern-builds/binaries/668fb380a07a2dfb90b57a28b3a07af11c9188ff/lantern-0.9.1.9001+cu116-win64.zip'
Error in utils::download.file(url = url, destfile = destfile) : 
  cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/binaries/668fb380a07a2dfb90b57a28b3a07af11c9188ff/lantern-0.9.1.9001+cu116-win64.zip'
In addition: Warning messages:
1: In utils::download.file(url = url, destfile = destfile) :
  downloaded length 0 != reported length 267
2: In utils::download.file(url = url, destfile = destfile) :
  cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/binaries/668fb380a07a2dfb90b57a28b3a07af11c9188ff/lantern-0.9.1.9001+cu116-win64.zip': HTTP status was '404 Not Found'
Warning message:
In file.remove(tmp) :
  cannot remove file 'C:\Users\Utente\AppData\Local\Temp\Rtmp6FLVvp\file3cc8b022698.zip', reason 'No such file or directory'
```

the version of my torch is 

```
Documentation for package ‘torch’ version 0.9.1.9001
```

which is the github version

**Comment by dfalbel** [comment]
It looks like you don't have access to the URL: `https://storage.googleapis.com/torch-lantern-builds/binaries/668fb380a07a2dfb90b57a28b3a07af11c9188ff/lantern-0.9.1.9001+cu116-win64.zip`. Maybe a firewall is blocking it?

You can refer to #1006 for a related discussion.

**Comment by agronomofiorentini** [comment]
I have installed as refered in #1006, and i have placed the lantern.dll in the lib directory as reported in the 

```
> system.file(package="torch")
[1] "C:/Users/Utente/AppData/Local/R/win-library/4.2/torch"
```

<img width="620" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/231160392-17134b3f-cd32-4d6f-9101-3952c1fbd8c2.png">

But i have still the problem.

```
> torch::as_array()
Error in torch::as_array() : argument "x" is missing, with no default
In addition: Warning message:
ℹ torch failed to start, restart your R session to try again.
ℹ You might need to reinstall torch using `install_torch()`
✖ C:\Users\Utente\AppData\Local\R\win-library\4.2\torch/lib\lantern.dll - Impossibile trovare la procedura specificata.
Caused by error in `cpp_lantern_init()`:
  C:\Users\Utente\AppData\Local\R\win-library\4.2\torch/lib\lantern.dll - Impossibile trovare la procedura specificata.
```

**Comment by dfalbel** [comment]
I think you might have downloaded from the same URL in #1006 which is not compatible with the dev version you just installed.

I think the problem here is that we no longer support CUDA 11.6, and that's why the URL we try to download from doesn't work. I have made improvements to the error message you should get in #1014. 

In the meantime, you might want to download the version from this URL: https://storage.googleapis.com/torch-lantern-builds/binaries/refs/heads/main/latest/lantern-0.9.1.9001%2Bcu117-win64.zip which might work as its just a patch version upgrade.

**Comment by agronomofiorentini** [comment]
Thanks for your support, now it works.

Only one thing, when I go to use the sits_tempcnn function of the sits r package that use the torch package, the system aborts.

I don't know why. While when i am using a empty docker image, everything work.
