### ISSUE TITLE
lantern path not correct for mac os x86_64 for v10.0.0 from cran

### ISSUE THREAD

**Issue by egillax** [mlverse/torch#1019]
Currently the lantern url for this arch is:

```https://storage.googleapis.com/torch-lantern-builds/binaries/0.10.0/lantern-0.10.0+cpu+x86_64-Darwin.zip```

The issues seems to be that despite installing from CRAN the package description for this arch after installingincludes a `RemoteSha` field but the contents of that field is just `0.10.0`. This results in the path being built incorrectly.  

I believe the correct path should be:
```https://storage.googleapis.com/torch-lantern-builds/binaries/refs/heads/cran/v0.10.0/latest/lantern-0.10.0+cpu+x86_64-Darwin.zip```

**Comment by dfalbel** [comment]
Hi @egillax ! Thanks for reporting! I have manually fixed the problem by serving the new binaries in this URL.
This is indeed a bug, I wasn't aware that other package installers would fill `RemoteSha` with the package version.
