### ISSUE TITLE
Cannot find state for adamw optimizer step

### ISSUE THREAD

**Issue by egillax** [mlverse/torch#1039]
Hi @dfalbel,

I'm getting an error sometimes when using `adamw`, when I run the `optimizer$step()`: 

`Error in state(param) : could not find function "state"`

I've not managed to make a reprex. I've gotten this error though on both windows and ubuntu. I can reproduce reliably it when running through a set of packages I use. In short there is a package built on top of targets that executes pipelines where each node of the pipeline is a renv project with it's own dependencies bundled with it. One of those nodes is developing a deep learning models using `torch` and that's where I get the error.  I can open this node as an r project that uses renv in R studio. When I do that and run the script manually that's run as part of the pipeline I get the error, but when trying to do a reprex that doesn't depend on my data or that script it always seems to work.

I've also stepped through it in a debugger and switched out `adamw` for `adam` and then it does work. A further thing I tried was adding the lines at the top of `optim-adam.R` to `optim-adamw.R`

```R
#' @include optim.R
NULL
```

But that also didn't solve the issue.

Any idea what could be going on?

**Comment by dfalbel** [comment]
Hi @egillax ! Thanks for reporting, this looks very tricky.

Would you be able to check what is the output of: 

```
optimizer$step |> rlang::fn_env() |> rlang::env_parents()
```

I'd expect to find torch to be in the search path as `state` is a function in it's namespace. that's the only reason I can think for the 'could not find function "state"' error.

**Comment by egillax** [comment]
@dfalbel ,

The output is:

```R
[[1]]   <env: 0x556b75bfe8f8>
[[2]] $ <env: global>
```

**Comment by dfalbel** [comment]
Weird! Do you somehow move the optimizer between processes after it's created? How is it initialized? Do you have a project implementation of `optim_adamw` that could be mixing up with torch's one?

**Comment by egillax** [comment]
The line that gives the error is [here](https://github.com/OHDSI/DeepPatientLevelPrediction/blob/main/R/LRFinder.R#L94)

I initialize the optimizer with:

```R 
optimizer <- estimatorSettings$optimizer(model$parameters, lr=minLR)
```
The `estimatorSettings$optimizer` object is the `torch::optim_adamw` function (not string). That is specified upfront and written to json along with all other settings before the whole pipeline is executed from that json. 

I just stepped through the code and instead of using `estimatorSettings$optimizer` I just used `torch::adamw`. Then everything works and when running the `rlang` stuff I see `namespace:torch` and `imports:torch` in the environments.

I think the whole saving a function object to json is loosing some vital information for the function. I think I'll try to just save the name of the optimizer as text and resolving it to the correct function just before initializing the optimizer.

**Comment by egillax** [comment]
@dfalbel ,

I did find a typo though in the class name [here](https://github.com/mlverse/torch/blob/9fa3509580230fe1ba2ddadca9d5d4920558e270/R/optim-adamw.R#L10)

`optim_adawm`

For some reason the one I'm loading from json has the class as `optim_adamw`

**Comment by dfalbel** [comment]
It looks like this is the problem! I wonder why it didn't happen for `optim_adam` too. Yes, It's probably better to save the function name and resolve at runtime. Function serialization in R is quite tricky because of R's dynamic lookup.

**Comment by dfalbel** [comment]
Ohh thanks for reporting! Will fix!

**Comment by dfalbel** [comment]
Are you perhaps loading the one from torchopt::optim_adamw?

**Comment by egillax** [comment]
It looks like I actually am. At some point I switched over to using `torch::optim_adamw` instead of from `torchopt`. But looking at the function object it has as well different default learning rate and is missing the step_fun. Which matches the `torchopt` version. I guess I must have mixed up the jsons. 

Thanks for your help! I had been struggling with this for quite a while.

**Comment by dfalbel** [comment]
Glad it worked! Please don't hesitate opening new issues :)
