### ISSUE TITLE
Error in cpp_jit_load(path)

### ISSUE THREAD

**Issue by burnsal** [mlverse/torch#1047]
I trained a series of FasterRCNN models in PyTorch and saved via `jit.save` that I am loading into R via `torch::jit_load(/path/to/model.pt)`  The models had been loading and running fine until today, but now I am getting the following error:

```
Error in cpp_jit_load(path) : 
Unknown builtin op: torchvision::nms.
Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
:
  File "code/__torch__/torchvision/ops/boxes.py", line 138
  _59 = __torch__.torchvision.extension._assert_has_ops
  _60 = _59()
  _61 = ops.torchvision.nms(boxes, scores, iou_threshold)
        ~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _61
'nms' is being compiled since it was called from '_batched_nms_vanilla'
  File "C:\Users\user.name\Anaconda3\envs\CTD\lib\site-packages\torchvision\ops\boxes.py", line 109
    for class_id in torch.unique(idxs):
        curr_indices = torch.where(idxs == class_id)[0]
        curr_keep_indices = nms(boxes[curr_indices], scores[curr_indices], iou_threshold)
                            ~~~ <--- HERE
        keep_mask[curr_indices[curr_keep_indices]] = True
    keep_indices = torch.where(keep_mask)[0]
Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 83
    _31 = torc
```

system info:

- torch v0.10.0
- torchvision v0.5.1
- torchvisionlib v0.3.0
- R v4.2.2
- RStudio 2022.12.0

Any help would be greatly appreciated!

**Comment by dfalbel** [comment]
Hi @burnsal ,

Thanks for reporting!

This might mean that the version of libtorchvision that torchvisionlib is using is outdated compared to the one you used for training and save your model. Can you specifythe version of torchvision (Python) that you used for training?

**Comment by burnsal** [comment]
Thanks for the quick response @dfalbel !

The model was trained with pytorch 1.12.0 and torchvision 0.13.0. The model was trained on GPU, and here is the Python code I used to re-initiate the model on CPU and save for loading into R:

```
 # Save model weights for loading into R package
 path2weights = output_path + cnn_backbone + "_model_weights_cpu.pth"
 torch.save(dict(model.to(device='cpu').state_dict()), f=path2weights)

 # save model architecture for loading into R package
 model.eval()
 s = torch.jit.script(model.to(device='cpu'))
 torch.jit.save(s, output_path + cnn_backbone + "_model_Arch_cpu.pth")
```
I didn't make any changes to the model, the only thing that changed was updating my mlverse R packages, so I know this way of saving the model files worked at one point.

**Comment by burnsal** [comment]
Hi @dfalbel, 

Just checking in here to see if there's any progress on the issue. One thing to note is that I have multiple models that were trained in different versions of torchvision <=0.13.0 that were all working before last week.

**Comment by dfalbel** [comment]
HI @burnsal,

I still didn't look with more depth into it. Sorry :( 
I'll look as soon as possible. 

I still don't have a good explanation, except for a possible incompatibility between the torchvisionlib version of the jit operators and the ones included in the scripted model.

**Comment by burnsal** [comment]
@dfalbel ok thanks. Is there anything you suggest I can look into on my end to get the models up and running?

**Comment by dfalbel** [comment]
Ok, I have a minimal example that works for me with the dev version of torchvisionlib. 


Would you be able to test if the folowing works in your setup?, 

```
import torch
import torchvision

class MyModel(torch.nn.Module):
  def __init__ (self):
    super(MyModel, self).__init__()
  def forward (self, x, y, z):
    return torchvision.ops.nms(x, y, z)
    
model = MyModel()

model(torch.randn(10,4), torch.randn(10), 0.5)
jitted = torch.jit.trace(model, (torch.randn(10,4), torch.randn(10), torch.tensor(0.5)))
jitted.save("path/to/jitnms.pt")
```

Then try to load it in R with:

```
library(torch)
library(torchvisionlib)
jit_load("path/to/jitnms.pt")
```

Then, please install the dev version of torchvisionlib with `remotes::install_github("mlverse/torchvisionlib") and it should work. I'll submit a new version of torchvisionlib to CRAN shortly.

**Comment by burnsal** [comment]
Hi @dfalbel,

When I tried to load the current version of `torchvisionlib` (v0.3.0) I got the following error:
```library(torchvisionlib)
trying URL 'https://github.com/mlverse/torchvisionlib/releases/download/v0.3.0/torchvisionlib-0.3.0+cpu-win64.zip'
Content type 'application/octet-stream' length 2519554 bytes (2.4 MB)
downloaded 2.4 MB

Error: package or namespace load failed for ‘torchvisionlib’:
 .onLoad failed in loadNamespace() for 'torchvisionlib', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/amira.burns/AppData/Local/R/win-library/4.2/torchvisionlib/bin/torchvisionlib.dll':
  LoadLibrary failure:  The specified procedure could not be found.
```

This happened with the version of the package I had previously installed, and when I reinstalled it from CRAN. I also reinstalled `torch` and `torchvision` and they load just fine, so I'm not sure why the load issue is only occurring for `torchvisionlib`. I tried reinstalling R as well to see if that was the issue, but the same issue occurs with a new install.

**Comment by dfalbel** [comment]
The error is expected if torchvisionlib is not loaded, as it's reposible for registering the `ops.torchvision` jit ops.
When you install the dev version and then `library(torchvisionlib)`, what do you see in the directory:

```
C:/Users/user.name/AppData/Local/R/win-library/4.2/torchvisionlib/bin/
```

The error message suggests that the `torchvisionlib.dll` file was not copied to that directory. Could you verify it's there?

**Comment by burnsal** [comment]
Yes the file is there:
![image](https://github.com/mlverse/torch/assets/54477812/77bc10c4-c0b0-4bc8-ac7d-d7b3bd583847)

**Comment by dfalbel** [comment]
I have updated torchvisionlib dev version. Would you mind trying to install it again a reporting the error messages that you see?
Thanks!

```
remotes::install_github("mlverse/torchvisionlib")
```

**Comment by burnsal** [comment]
@dfalbel 

This version works! I tested the minimal example, as well as all the models I've created for my package. I'm not sure if you need any of the messages from the package install or downloading software the first time I loaded it?

**Comment by dfalbel** [comment]
Awesome! Glad it works now! I'll upload the new torchvisionlib version to CRAN early next week.
