### ISSUE TITLE
Is it possible to ignore CUDA when installing torch?

### ISSUE THREAD

**Issue by wlandau** [mlverse/torch#1049]
Maybe my case is atypical, but I am fine to do without the GPU because I am only interested in testing integration with [`targets`](https://docs.ropensci.org/targets). I have observed that `torch` can install successfully on machines without CUDA, but on a machine with an unsupported CUDA version, I see:

```r
> torch::install_torch()
Error in `check_supported_version()`:
✖ Unsupported CUDA version "10.0"
ℹ Currently supported versions are: "11.7" and "11.6".
```

CUDA is currently on version 12.1, so I think I would choose it for an upgrade rather than 11.6 or 11.7.

Is there a way to ignore CUDA altogether and install `torch` assuming there is no GPU? Sorry if I am missing something obvious in the documentation.

Related: #1012

**Comment by dfalbel** [comment]
Hi,

Thanks for your message! Yes, we should improve documentation around this.

Yes, you should be able to force the cpu installation by setting the CUDA env var to "cpu".

**Comment by wlandau** [comment]
Awesome, thanks! Worked for me.
