### ISSUE TITLE
support for storage() method

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#105]
Can we have the  `storage()` method on tensors so we can access `data_ptr()`?

```
t1.storage().data_ptr()
t2.storage().data_ptr()
```

I note we have `ptr` on a tensor, but this seems to be different (does not seem to point to the address where the data begins), right?

```
> t1 <- torch_tensor(rbind(c(1, 2), c(3, 4), c(5, 6)))
> t2 <- t1$view(c(2, 3))
> t1$ptr
<pointer: 0x556019762940>
> t2$ptr
<pointer: 0x5560194c0030>
attr(,"dynamic_type")
[1] "Tensor"
``

**Comment by dfalbel** [comment]
Yeah, the `ptr` is the pointer to the c++ object that knows about the tensor.
