### ISSUE TITLE
Export with_torch_manual_seed

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torch#1052]
It would be great if the function `with_torch_manual_seed()` could be exported :)

And maybe I have already said it, but thank you for being so responsive to issues!

**Comment by dfalbel** [comment]
THank you for reporting @sebffischer !
I had a misconception that `@describeIn` would trigger to function to inherit the `@export` value which is not the case.
Will be fixed in #1057

Looking forward for your work in ml3torch! Let me know if I can help somehow!
