### ISSUE TITLE
LibTorch and LibLantern URLs not correct for x86_64-pc-linux-gnu for v10.0.0

### ISSUE THREAD

**Issue by wwtung** [mlverse/torch#1053]
Hello, 

My installation of `torch 0.10.0` on CentOS Linux has not succeeded. Following https://torch.mlverse.org/docs/articles/installation.html,  `install.packages("torch")` can complete but the subsequent installation of `LibTorch` and `LibLantern` triggered by `library(torch)` result in errors. Error messages show that the URLs to both Libs are incorrect, for example:

`! cannot open URL 'https://download.pytorch.org/libtorch/cu/apps/gilbreth/cuda-toolkit/cuda-1120/libtorch-cxx11-abi-shared-with-deps-1.13.1%2Bcu/apps/gilbreth/cuda-toolkit/cuda-1120.zip'`

To check, the command `get_install_lib_url()` returns:

`Follow the links to download the dependencies, then set the TORCH_URL and LANTERN_URL env vars to the file paths.
LibTorch: <https://download.pytorch.org/libtorch/cu113/libtorch-shared-with-deps-1.13.1%2Bcu113.zip>
LibLantern:
<https://storage.googleapis.com/torch-lantern-builds/binaries/refs/heads/cran/v0.10.0/latest/lantern-0.10.0+cu113+x86_64+pre-cxx11-Linux.zip>`

Nonetheless, `wget` both URLs returns `ERROR 404: Not Found`.

Due to the HPC system setup out of my control, installing from pre-built binaries is not an option at this point.

Could you please share and update the correct  URL paths?

Thank you very much!

-------------
My session information:

> sessionInfo(package = NULL)
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /apps/spack/gilbreth/apps/openblas/0.3.21-gcc-6.3.0-z6maa4u/lib/libopenblas_zenp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] torch_0.10.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10     ps_1.7.2        withr_2.5.0     rprojroot_2.0.2
 [5] R6_2.4.0        magrittr_2.0.3  coro_1.0.3      rlang_1.0.6    
 [9] cli_3.4.1       callr_3.7.3     desc_1.4.2      tools_4.2.2    
[13] bit64_0.9-7     glue_1.4.2      bit_1.1-14      compiler_4.2.2 
[17] processx_3.8.0  tcltk_4.2.2

**Comment by dfalbel** [comment]
The problem is that we don't support CUDA 11.2. Currently support CUDA versions are 11.6 and 11.7. 
To install with older cuda versions you would need to build both LibTorch (the current version used by torch is v1.13.1) and LibLantern (src/lantern in this repository) targetting that CUDA version. You could them modify `LANTERN_URL` and `TORCH_URL` to a path containing the cuda 11.2 builds.

**Comment by wwtung** [comment]
That's indeed what happened and explains the error messages seemingly looking for CUDA 11.2 or 11.3.
However, it's not a straightforward situation in our HPC. In short, I loaded software modules for `cuda/11.7.0` and `cudnn/cuda-11.7_8.6` prior to the installation, but the system still defaulted to `cuda-toolkit` for `cuda-11.2.0`. After I `export CUDA` to the right path for the toolkit, the installation can be completed. Your answer is most helpful! Thank you!

**Comment by dfalbel** [comment]
Cool! Glad it worked! Yes, exporting `CUDA=11.7` env var should tell torch to install the correct version.
