### ISSUE TITLE
[question] torch_arange behavior differs from pytorch's

### ISSUE THREAD

**Issue by Athospd** [mlverse/torch#1059]
Is this behavior expected? 

**torch**
```
> torch::torch_arange(-1, 1)
torch_tensor
-1
 0
 1
[ CPUFloatType{3} ]
```

**pytorch**
```
>>> torch.arange(-1, 1)
tensor([-1,  0])
```

thank you!

**Comment by dfalbel** [comment]
Hey @Athospd !

Yes, this is expected. The main motivation for this behavior is to be equivalent to `1:10`. The main diffference from PyTorch is that end indices are inclusive. This makes it easier for R users to reason about arange when using it as indices.
