### ISSUE TITLE
Trouble with "load_state_dict"

### ISSUE THREAD

**Issue by djd224** [mlverse/torch#1064]
Hello all!

I am interested in importing my PyTorch model into R in order to use the shapr package for further analysis of the model.

I trained the ANN in PyTorch, and saved the model using the same method shown in this [vignette](https://cran.r-project.org/web/packages/torch/vignettes/python-to-r.html).  I have reconstructed the model class in R, but when I attempt to load the saved model using state_dict <- load_state_dict(filepath) I get the following error. 

`Error in cpp_load_state_dict(path) : 
  isGenericDict() INTERNAL ASSERT FAILED at "/Users/dfalbel/Documents/actions-runner/mlverse-m1/_work/libtorch-mac-m1/libtorch-mac-m1/pytorch/aten/src/ATen/core/ivalue_inl.h":1945, please report a bug to PyTorch. Expected GenericDict but got None
Exception raised from toGenericDict at /Users/dfalbel/Documents/actions-runner/mlverse-m1/_work/libtorch-mac-m1/libtorch-mac-m1/pytorch/aten/src/ATen/core/ivalue_inl.h:1945 (most recent call first):
frame #0: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 92 (0x10de3552c in libc10.dylib)
frame #1: c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 72 (0x10de35768 in libc10.dylib)
frame #2: torch::jit::Unpickler::readInstruction() + 12824 (0x178341cf0 in libtorch_cpu.dylib)
frame #3: torch:`

If anyone has any input as to how to fix this issue I would greatly appreciate it!

**Comment by dfalbel** [comment]
The dev version of torch should fix this issue. This was fixed in #1051

You can also save the model in Pytorch by doing `torch.save(dict(model.state_dict()))`, ie converting the `state_dict()` into a proper Python `dict` before the serialization.

**Comment by djd224** [comment]
Thank you very much!  Converting into a proper Python `dict` before serialization worked perfectly!
