### ISSUE TITLE
Please update 'installation from binary' to 0.11.0

### ISSUE THREAD

**Issue by eddelbuettel** [mlverse/torch#1094]
The instructions still show 0.10.0, but there appears to be no repo behind it.   Whereas 'guessing' that 0.11.0 may work was successful.  I would be lovely to make it more obvious one now needs the torch package version -- maybe the example can even farm out and use the version at CRAN to keep the docs in sync 'automagically'  ?

**Comment by GitHubGeniusOverlord** [comment]
https://torch.mlverse.org/docs/articles/installation.html#pre-built

**Comment by dfalbel** [comment]
Thanks for reporting, I have updated the docs. Unfortunatelly it will only appear in the website once we make a new release, but it can be already found in the dev version of the docs:

https://torch.mlverse.org/docs/dev/articles/installation#pre-built

**Comment by eddelbuettel** [comment]
I am having the same problem now with 0.12.0 following the instructions in the current vignette:

```r
> version <- available.packages()["torch","Version"]
> options(repos = c(
  torch = sprintf("https://storage.googleapis.com/torch-lantern-builds/packages/%s/%s/", kind, version),
  CRAN = "https://cloud.r-project.org" # or any other from which you want to install the other R dependencies.
))
> install.packages("torch")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://storage.googleapis.com/torch-lantern-builds/packages/cu117/0.12.0/src/contrib:
  cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/packages/cu117/0.12.0/src/contrib/PACKAGES'
```

**Comment by eddelbuettel** [comment]
Hah!  And like before 'guessing' that `cu118` may work seems to help:

```r
> kind <- "cu118"
> version <- "0.12.0"
> options(repos = c(
  torch = sprintf("https://storage.googleapis.com/torch-lantern-builds/packages/%s/%s/", kind, version),
  CRAN = "https://cloud.r-project.org" # or any other from which you want to install the other R dependencies.
))
> available.packages()["torch","Version"]
[1] "0.12.0"
>  
> install.packages("torch")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://storage.googleapis.com/torch-lantern-builds/packages/cu118/0.12.0/src/contrib/torch_0.12.0_R_x86_64-pc-linux-gnu.tar.gz'
downloaded 2749.2 MB
[...]
```

**Comment by dvictori** [comment]
I just found out that using `cu118` fixed my install issues. It's worth noting that the Install Vignette on CRAN is outdated and thus, not working

> Hah! And like before 'guessing' that `cu118` may work seems to help:
>
