### ISSUE TITLE
GPU Installation instructions point to cuda 11.7 documentation but could point to cuda 11.7 installation files directly

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlverse/torch#1102]
Hi,
the installation instructions https://torch.mlverse.org/docs/articles/installation.html#pre-built
point to the link https://docs.nvidia.com/cuda/archive/11.7.0/ which contains the documentation for cuda 11.7 as expected. However if you follow the obvious link "installation guide windows" from that site, you actually end up with a link to the newest cuda toolkit, as of today 12.2. This is confusing!
Instead, a direct link to the installation files for cuda 11.7 would be easier to handle. 
https://developer.nvidia.com/cuda-11-7-0-download-archive
Thanks!

**Comment by dfalbel** [comment]
@GitHubGeniusOverlord thanks for reporting, I fixed the docs and you can preview it here: https://torch.mlverse.org/docs/dev/articles/installation#pre-built
