### ISSUE TITLE
upload the torch to the aws lambda layer

### ISSUE THREAD

**Issue by Lsgoose** [mlverse/torch#1104]
When I upload the python.zip to the aws lambda, running a easy neural network.The consule remind me that '/opt/python/torch/lib/libtorch_global_deps.so: file too short'.Does anyone know why?

**Comment by cregouby** [comment]
Hello @Lsgoose ,

The repository here is for torch for R. So it has zero adherence with python in any way. 
You should maybe open the issue in the brother [pytorch repository](https://github.com/pytorch/pytorch/issues/new/choose)
