### ISSUE TITLE
Failure to load Lantern error escapes tryCatch() function

### ISSUE THREAD

**Issue by trinetra75** [mlverse/torch#1157]
Hello,

I'm trying to optionally integrate torch in my R package, but,
when I tried to check whether the torch library is effectively available to run,
the following code did still fail to execute:

```
    tryCatch({
      library("torch", character.only = TRUE)
    },
    error = function(err) {
      useTorch <- FALSE
   })
```

with this error:
```
Error: processing vignette 'Guided_tutorial_v2.Rmd' failed with diagnostics:
Lantern is not loaded. Please use `install_torch()` to install additional dependencies.
```

Would it be possible to have this error fall within the range of the ```tryCatch()``` function?

PS: Maybe I'm doing something wrong, but I tried to look anywhere on the resources and didn't find anything about this case.
So I'm asking here: which is the best way to have the `torch` as **optional** feature?

**Comment by dfalbel** [comment]
This doesn't look like the error that torch would show when failing to start, but an error cause by trying to use torch functions with lantern not installed.

Are you sure that all torch calls are avoided when `useTorch = FALSE`?

**Comment by trinetra75** [comment]
I'm pretty sure that no `torch` command is executed once the flag is set to `FALSE`.
And I'm also relatively sure the above is the offending command (it is in a _vignette_ running on a Bioconductor machine...)

**Comment by dfalbel** [comment]
```torch::torch_is_installed()``` is the function that checks if torch binaries are correctly installed. You can use it to check for toprch in your vignette.

**Comment by trinetra75** [comment]
Thank you for your prompt answers!

Does your suggestion implies I can use `torch::torch_is_installed()` before/instead of `library("torch")`?
Naturally assuming I already checked the presence of the `torch` library with `requireNamespace("torch", quietly = TRUE)`...

**Comment by dfalbel** [comment]
Yes, I think you can do something like:

```
useTorch <- requireNamespace("torch", quietly = TRUE) && torch::torch_is_installed()
```

**Comment by trinetra75** [comment]
Thank you!

I'll try asap and report if it worked...

**Comment by trinetra75** [comment]
Hi, the code you suggested, worked perfectly:

`useTorch <- requireNamespace("torch", quietly = TRUE) && torch::torch_is_installed()`

Thank you very much!

Might I suggest to include this code in the documentation/examples?
I suppose I'm not the only one that might need this... Thanks again!
