### ISSUE TITLE
Unable to load pre-trained alexnet weights 

### ISSUE THREAD

**Issue by mika-long** [mlverse/torch#1171]
I have installed packages `torch`, `luz`, and `torchvision`. 
I had the following code: 

```r
library(torch)
library(luz)
library(torchvision)

weights <- model_alexnet(pretrained=TRUE)
```
The above produces an error as follows: 
`Error in !self$..refer_to_state_dict.. : invalid argument type` 

Not sure what is wrong here.

**Comment by dfalbel** [comment]
You probably need to reinstall torch vision, using something like `install.packages("torchvision, type="source")`.
Probably related to https://github.com/mlverse/torchvision/issues/100#issuecomment-1973282566

**Comment by mika-long** [comment]
This worked! Thank you 🙏
