### ISSUE TITLE
allow direct access to module parameters as "weight" and "bias"

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#126]
```l
l <- nn_linear(3, 1)
```

We can do
```
l$parameters$weight
l$parameters$weight
```

but not 
```
l$weight
l$bias
```

Of course that's not a necessity, just a matter of convenience.

**Comment by dfalbel** [comment]
This seems to work for me:

``` r
library(torch)
l <- nn_linear(3, 1)
l$weight
#> torch_tensor 
#> -0.0385  0.1412 -0.5436
#> [ CPUFloatType{1,3} ]
l$bias
#> torch_tensor 
#> -0.1950
#> [ CPUFloatType{1} ]
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Perhaps the autocomplete doesn't show it?

**Comment by skeydan** [comment]
right - will never rely on autocomplete again (which I would have sworn I didn't, but must have, evidently ;-))
