### ISSUE TITLE
necessity of N symbol used in indexing

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#135]
going through the existing vignettes to see what I'm missing for the book (gonna send PR soon)... 
I'm just wondering, do we need this?

```{r}
x[5:N]
```

I mean, `-1` does the same, right? Just thinking that the fewer things to remember, the better ...

**Comment by dfalbel** [comment]
I think `N` has a small difference form `-1`. For instance:

```
x[2:N]
```

is not equivalent to `x[2:-1]`.

But perhaps we want to change that actually.

**Comment by skeydan** [comment]
oh, got it. Yes - judging from what I erroneously assumed myself...my thinking was, the `-1` concept is from Python, but the behavior is R-like (including, not excluding, the index).

Yes I think I would favor that, then - change `-1` behavior and remove N.

Note to self: also need to rephrase what I write in the book, then (re concept vs implementation)
