### ISSUE TITLE
Initial functionality from torchvision

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#144]
There we go ;-)

A great "starter set" would be composed of:

1. transforms

currently used in book e.g.:

```
transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.ColorJitter(),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
```

Of these, the very first should be ` transforms.ToTensor()`.

2. datasets

- `ImageFolder`

```
image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x),
                                          data_transforms[x])
                  for x in ['train', 'valid', 'test']}
```

- a concrete dataset (right now I'd love to have KMNIST :-))

3. one model

preferred would be resnet18 :-)

**_muito obrigada :-))_**

P.S. for concrete usage examples, see e.g.

https://github.com/mlverse/torchbook/blob/master/image_classification.Rmd

https://github.com/mlverse/torchbook/blob/master/GANs.Rmd

**Comment by skeydan** [comment]
@dfalbel I was wondering if I could send a PR for KMNIST and, perhaps, a few transforms, given that you already have `mnist_dataset` and this 

```
transform = function(x) {
    x <- x$to(dtype = torch_float())/256
    x[newaxis,..]
  }
```

but I think there's too many design decisions still to be made (and it's gonna be most efficient if you make them). 
For example, in Python, KMNIST & co are just subclassing MNIST

https://pytorch.org/docs/stable/_modules/torchvision/datasets/mnist.html#KMNIST

(((And no hurry, I can start translating stuff with MNIST as a temporary replacement :-)))

**Comment by dfalbel** [comment]
I think the hardest decision is for the transforms as we will need to decide which R library we will default for image holding the image. For instance, it seems that pytorch vision uses PIL everywhere, but I don't think we a have a default library like this in R.

**Comment by skeydan** [comment]
`utils` has just two functions, of which I find `make_grid` very useful... I've extracted the main functionality (no error handling, just the default input type [[[which should be the one mostly used anyway]]] from https://pytorch.org/docs/stable/torchvision/utils.html.
LMK if we ever want to integrate this and where, and I can do a PR :-)

```
normalize <- function(x) {
  min = x$min()$item()
  max = x$max()$item()
  x$clamp_(min = min, max = max)
  x$add_(-min)$div_(max - min + 1e-5)
  x
}

# 4D mini-batch Tensor of shape (B x C x H x W)
make_grid <- function(tensor, num_rows = 8, padding = 2, pad_value = 0) {
  nmaps <- tensor$size(0)
  xmaps <- min(num_rows, nmaps)
  ymaps <- ceiling(nmaps/xmaps)
  height <- floor(tensor$size(2) + padding)
  width <- floor(tensor$size(3) + padding)
  num_channels <- tensor$size(1)
  grid <- tensor$new_full(c(num_channels, height * ymaps + padding, width * xmaps + padding), pad_value)
  k <- 0
  for (y in 0:(ymaps - 1)) {
    for (x in 0:(xmaps - 1)) {
      if (k >= nmaps) break
      grid$narrow(
        dim = 1,
        start = torch_tensor(y * height + padding, dtype = torch_int64())$sum(dim = 0),
        length = height - padding)$narrow(
        dim = 2,
        start = torch_tensor(x * width + padding, dtype = torch_int64())$sum(dim = 0),
        length = width - padding)$copy_(tensor[k + 1, , , ])
      k <- k + 1
    }
  }
  grid
}
```

**Comment by dfalbel** [comment]
I think most of this is implemented in torchvision now.
