### ISSUE TITLE
Conversion of NAs and NaN in R vectors to tensor

### ISSUE THREAD

**Issue by qykong** [mlverse/torch#172]
I notice that integer-typed NAs are converted to `-2.14748e+09` and bool-typed NAs/NaNs are coverted to `1`, but I guess it makes more sense to convert them to `nan`s in tensors. For example:
```r
> torch_tensor(c(1L, 2L, 0L, NA))
# torch_tensor 
# 1
# 2
# 0
# -2.14748e+09
# [ CPUIntType{4} ]
> torch_tensor(c(1L, 2L, 0L, NaN), dtype = torch_bool())
# torch_tensor 
# 1
# 1
# 0
# 1
# [ CPUBoolType{4} ]

# this works
> torch_tensor(c(1.2, 2., 0, NA))
# torch_tensor 
# 1.2000
# 2.0000
# 0.0000
# nan
# [ CPUFloatType{4} ]
```

**Comment by dfalbel** [comment]
I think we should entirely disallow `NA` values when converting to torch tensors as there's no 'missing data' abstract in torch.

For NaN's, the behavior is really weird, but seems to be consistent with pytorch. It looks like `nan` is only a floating point type and for all other types it will get converted to a different thing. Eg if you run:

```
import torch
(torch.tensor(1.)/0).to(torch.int)
# tensor(-2147483648, dtype=torch.int32)
(torch.tensor(1.)/0).to(torch.bool)
# tensor(True)
```

**Comment by qykong** [comment]
I see. Thanks for the clarification. Yes, disallowing `NA`s makes sense. I didn't realize pytorch actually handles `nan` like this
