### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#21]
After successful compilation:

```
> library(torchr)
You need to install libtorch in order to use torchr.

Do you want to download it now? ~100Mb (yes/no)yes
trying URL 'https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip'
Content type 'application/zip' length 103918316 bytes (99.1 MB)
==================================================
downloaded 99.1 MB

trying URL 'https://storage.googleapis.com/lantern-builds/refs/heads/master/latest/Linux.zip'
Content type 'application/zip' length 868607 bytes (848 KB)
==================================================
downloaded 848 KB

Torch was successfully installed.
Please restar your R session now.

Restarting R session...

> devtools::load_all(".")
Loading torchr
You need to install libtorch in order to use torchr.

Do you want to download it now? ~100Mb (yes/no)no
```

From the above I would have 3 questions/problems:

1. What if I already have a `libtorch` I want to use? (I would hope that in this case, only `lantern` the R package would need to be installed?)

2. If I agree to install torch, should I be able to choose between cpu and gpu builds?

3. I got positive feedback ("torch installed") but evidently it was not ...

This just to start the issue, will try to find out some stuff and comment below...

**Comment by skeydan** [comment]
```
lantern_install_path <- function() {
  normalizePath(file.path(system.file("", package = "torchr"), "deps"), mustWork = FALSE)
}

```

does not exist after I built from source... trying installation from github now.

**Comment by skeydan** [comment]
OK so it was the path problem... `libtorch` gets installed successfully if I install from github...

So I guess questions (1) and (2) still remain, and (3) would now be why - when I build myself - the package is not installed in the official R library?

**Comment by javierluraschi** [comment]
Should be mostly resolved with https://github.com/mlverse/torch/pull/74, now we install the GPU version if the right version of CUDA is detected. We can also manually run `install_torch(type = "10.1")` for a specific CUDA version.

**Comment by skeydan** [comment]
nice!

**Comment by fkgruber** [comment]
> Should be mostly resolved with #74, now we install the GPU version if the right version of CUDA is detected. We can also manually run `install_torch(type = "10.1")` for a specific CUDA version.

How do I install torch on windows with GPU support? I'm using 10.1. Tried the command above and got:
```
install_torch(type = "10.1")
Error in lantern_install_libs(version, type, path) : 
  The windows operating system is currently unsupported.
> 
```

By default it is installing the CPU version.

thanks
FKG

**Comment by bearloga** [comment]
Same error :( Perhaps `install_torch()` could detect/parse presence of `CUDA_PATH` environment variable?

**Comment by dfalbel** [comment]
Hi! 

Sorry, currently we don't support GPU builds on Windows. I just opened https://github.com/mlverse/torch/issues/265 to track it.

**Comment by dfalbel** [comment]
We now support  GPU's on Windows with #281 .
