### ISSUE TITLE
use devel numbering

### ISSUE THREAD

**Issue by topepo** [mlverse/torch#214]
The current devel version has `Version: 0.0.1`. If you use the 9000 system for devel versions (`Version: 0.0.1.9000`) your `pkgdown` GHA will build an additional devel version of the website (at `https://mlverse.github.io/torch/dev`). That will help keep things in sync.

**Comment by dfalbel** [comment]
Done! pkgdown is now autogenerated and current dev website can be found at  https://mlverse.github.io/torch/dev/
