### ISSUE TITLE
automatically convert int to long tensors where necessary?

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#223]
I wonder if we should automatically convert int tensors (as converted from R integers) to long where torch expects them (for example, in `nn_embedding`), the reasoning being that R users don't normally make that distinction.

I could create a PR for `nn_embedding`, unless you think it doesn't make sense, or there is a central place where this should be accomplished.

**Comment by dfalbel** [comment]
I think we should always convert integers to long, no matter if it's required or not, like we do for floating point values that are converted to `float32`.

I think this is just changing this line: https://github.com/mlverse/torch/blob/master/R/tensor.R#L18 if you want to create a PR.

**Comment by skeydan** [comment]
thanks! https://github.com/mlverse/torch/pull/225
