### ISSUE TITLE
make nn_linear.in_feature and out_feature updateable

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#247]
Can we make this work (it does in Python)

```
test <- nn_linear(1,1)
test$out_feature <- 2
```

?

thanks :-)

**Comment by dfalbel** [comment]
Do you expect the weights to change when updating it too?

**Comment by skeydan** [comment]
Ah I should have added more detail, sorry! (And my "minimal reprex" was too minimal probably, as that really makes no sense (but produces the same error message))

The context is, you have a pre-trained model, and then replace a module (layer), like so

```
model <- model_resnet18(pretrained = TRUE)

num_features <- model$fc$in_features

model$fc <- nn_linear(in_features = num_features, out_features = length(class_names))
model$fc$out_feature <- 1
```

**Comment by dfalbel** [comment]
I don't really get it. Once you do `model$fc  <- nn_linear(in_features = num_features, out_features = length(class_names)`
why would `model$fc$out_feature` be different from `length(class_names)`?

**Comment by skeydan** [comment]
basically it's just a new output layer, for some new number of classes instead of the 1000 ones resnet has

(maybe we want to do this differently in R - I was just literally porting the python code)

**Comment by dfalbel** [comment]
Can you point me to the python code? I still don't follow what happens to the weights of the model? Does each time you set `model$fc$in_features` the weights matrix is re-created?

**Comment by skeydan** [comment]
https://github.com/mlverse/torchbook/blob/master/scripts/bird_species.py

**Comment by skeydan** [comment]
https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

**Comment by skeydan** [comment]
model_ft = models.resnet18(pretrained=True)
num_ftrs = model_ft.fc.in_features
# Here the size of each output sample is set to 2.
# Alternatively, it can be generalized to nn.Linear(num_ftrs, len(class_names)).
model_ft.fc = nn.Linear(num_ftrs, 2)

**Comment by dfalbel** [comment]
I think you want `nn_linear` instead of `nnf_linear`:

``` r
library(torchvision)
library(torch)

# get the model
model <- model_resnet18(pretrained=FALSE)

# change the output layer
num_classes <- 10
num_ftrs <- model$fc$in_features
# this seems like it is equivalent, but throws the error below
model$fc <- nn_linear(num_ftrs, num_classes)
model$fc
#> An `nn_module` containing 5,130 parameters.
#> 
#> ── Parameters ──────────────────────────────────────────────────────────────────
#> ● weight: Float [1:10, 1:512]
#> ● bias: Float [1:10]
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikeyEcology** [comment]
Perfect. Thank you @dfalbel !

**Comment by dfalbel** [comment]
Glad it worked @mikeyEcology :)
