### ISSUE TITLE
Failed install on rstudio cloud

### ISSUE THREAD

**Issue by scienceofdeduction** [mlverse/torch#263]
> remotes::install_github("mlverse/torch")
Downloading GitHub repo mlverse/torch@HEAD
Installing 7 packages: bit, Rcpp, magrittr, bit64, rlang, withr, R6
Installing packages into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'http://package-proxy/src/contrib/bit_4.0.4.tar.gz'
Content type 'application/x-tar' length 666984 bytes (651 KB)
downloaded 651 KB

trying URL 'http://package-proxy/src/contrib/Rcpp_1.0.5.tar.gz'
Content type 'application/x-tar' length 3235601 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'http://package-proxy/src/contrib/magrittr_1.5.tar.gz'
Content type 'application/x-tar' length 155851 bytes (152 KB)
downloaded 152 KB

trying URL 'http://package-proxy/src/contrib/bit64_4.0.5.tar.gz'
Content type 'application/x-tar' length 559553 bytes (546 KB)
downloaded 546 KB

trying URL 'http://package-proxy/src/contrib/rlang_0.4.7.tar.gz'
Content type 'application/x-tar' length 1222612 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'http://package-proxy/src/contrib/withr_2.3.0.tar.gz'
Content type 'application/x-tar' length 205322 bytes (200 KB)
downloaded 200 KB

trying URL 'http://package-proxy/src/contrib/R6_2.4.1.tar.gz'
Content type 'application/x-tar' length 57874 bytes (56 KB)
downloaded 56 KB

* installing *binary* package ‘bit’ ...
* DONE (bit)
* installing *binary* package ‘Rcpp’ ...
* DONE (Rcpp)
* installing *binary* package ‘magrittr’ ...
* DONE (magrittr)
* installing *binary* package ‘rlang’ ...
* DONE (rlang)
* installing *binary* package ‘withr’ ...
* DONE (withr)
* installing *binary* package ‘R6’ ...
* DONE (R6)
* installing *binary* package ‘bit64’ ...
* DONE (bit64)

The downloaded source packages are in
	‘/tmp/RtmpmVEGaW/downloaded_packages’
Running `R CMD build`...
* checking for file ‘/tmp/RtmpmVEGaW/remotes11c4d819885/mlverse-torch-6ba88f7/DESCRIPTION’ ... OK
* preparing ‘torch’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘torch/bench’
Removed empty directory ‘torch/docker’
Removed empty directory ‘torch/vignettes/examples’
* building ‘torch_0.1.0.9000.tar.gz’
Installing package into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘torch’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/opt/R/4.0.2/lib/R/include" -DNDEBUG  -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++: _**internal compiler error: Killed (program cc1plus)**_
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make: *** [RcppExports.o] Error 4
/opt/R/4.0.2/lib/R/etc/Makeconf:176: recipe for target 'RcppExports.o' failed
**ERROR: compilation failed for package ‘torch’**
* removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/torch’
_Error: Failed to install 'torch' from GitHub:_
  (converted from warning) installation of package ‘/tmp/RtmpmVEGaW/file11c6cec5e5f/torch_0.1.0.9000.tar.gz’ had non-zero exit status

**Comment by scienceofdeduction** [comment]
> sessionInfo() R version 4.0.2 (2020-06-22) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 16.04.6 LTS  Matrix products: default BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0 LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0  locale:  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8     [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         [11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C     attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       loaded via a namespace (and not attached): [1] compiler_4.0.2 tools_4.0.2    remotes_2.2.0
--
 
> | >
>

**Comment by dfalbel** [comment]
It seems that the RAM memory is exhausted when compiling torch. This should be automatically fixed in a few days, when the pre-compiled binaries are available in the [RStudio package manager](https://packagemanager.rstudio.com/client/#/repos/1/packages/torch).

**Comment by MikeXL** [comment]
Appreciate your quick reply. 
Looking forward to the precompiled package. 

Cheers 
M.

**Comment by dfalbel** [comment]
Just tested and looks like it's working now.

**Comment by scienceofdeduction** [comment]
Yea, below install works.. appreciate for fixing the issue.


Cheers,
M.
```
install.packages("torch")
library(torch)

torch_tensor(c(1,2,3))
```
