### ISSUE TITLE
GPU support on Windows

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#265]
Currently we are not supporting CUDA on Windows. 
The main step to be solved is to be able to correctly build lantern on windows with GPU support. 

The entrypoint is to tweak the CMake file here: https://github.com/mlverse/torch/blob/master/lantern/CMakeLists.txt#L40-L41

Then, we need to add the GPU build in the GH actions that generates pre-build lantern binaries here: https://github.com/mlverse/torch/blob/master/.github/workflows/lantern.yaml

We can then tweak the download links here: https://github.com/mlverse/torch/blob/master/R/install.R#L31-L56

**Comment by shinhongwu** [comment]
when will it support GPU on windows?

**Comment by dfalbel** [comment]
@shinhongwu I don't have an explicit date but I am planning it for the next release of torch

**Comment by shinhongwu** [comment]
> @shinhongwu I don't have an explicit date but I am planning it for the next release of torch

Got it and looking forward to it.  Thanks so much for your efforts.

**Comment by znmeb** [comment]
I've got a Windows 10 Pro partition I can test it on.

**Comment by dfalbel** [comment]
Added support for GPU's on Windows. Should be working in ~30 minutes when the binaries are correctly buily.

**Comment by bearloga** [comment]
Tested and it works! :D
