### ISSUE TITLE
R session crashed with CPU mode

### ISSUE THREAD

**Issue by ozt-ca** [mlverse/torch#266]
R session crashed when I ran [the KMNIST tutorial](https://blogs.rstudio.com/ai/posts/2020-09-29-introducing-torch-for-r/) but with CPU mode (`device = "cpu"`). It occurs when the learning procedure as below ran. Anybody knows what happened?

```
for (epoch in 1:5) {
  
  l <- c()
  
  for (b in enumerate(train_dl)) {
    # make sure each batch's gradient updates are calculated from a fresh start
    optimizer$zero_grad()
    # get model predictions
    output <- model(b[[1]]$to(device = "cpu"))
    # calculate loss
    loss <- nnf_cross_entropy(output, b[[2]]$to(device = "cpu"))
    # calculate gradient
    loss$backward()
    # apply weight updates
    optimizer$step()
    # track losses
    l <- c(l, loss$item())
  }
  
  cat(sprintf("Loss at epoch %d: %3f\n", epoch, mean(l)))
}
```

Session info:
```
sessionInfo()
#>R version 3.6.3 (2020-02-29)
#>Platform: x86_64-apple-darwin15.6.0 (64-bit)
#>Running under: macOS Catalina 10.15.6
#>
#>Matrix products: default
#>BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#>LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#>
#>locale:
#>[1] ja_JP.UTF-8/ja_JP.UTF-8/ja_JP.UTF-8/C/ja_JP.UTF-8/ja_JP.UTF-8
#>
#>attached base packages:
#>[1] stats     graphics  grDevices utils     datasets  methods   base     
#>
#>loaded via a namespace (and not attached):
#>[1] compiler_3.6.3 tools_3.6.3    yaml_2.2.1 
```

**Comment by dfalbel** [comment]
Hi @ozt-ca ,

This looks like a bug. Can you try running the same code in the terminal, so we can get a backtrace?

**Comment by ozt-ca** [comment]
Hi @dfalbel ,

Thank you for the quick response.
When I ran the same code in the terminal, I saw the error messages as below. It looks like an error related to OpenMP.

`OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized. OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6`

**Comment by dfalbel** [comment]
OK! I have seen this before and solved with `Sys.setenv(KMP_DUPLICATE_LIB_OK="TRUE")` but this doesn't seem to be recommended and it would be better to find the root cause. Unfortunatelly I can't reproduce the same error. DO you have `libomp` installed with brew?

**Comment by ozt-ca** [comment]
Thank you very much for the important information! `Sys.setenv(KMP_DUPLICATE_LIB_OK="TRUE")` worked and now it's running (and now I found that I should have used GPU!). At last it showed an error as below but returned test_accuracy as 0.8912, worse than the one in the KMNIST tutorial. I guess that it couldn't run the iteration loop because the last value of `epoch` was `1L`.

```
Error: 
Run `rlang::last_error()` to see where the error occurred. 
14. stop(fallback) 
13. signal_abort(cnd) 
12. rlang::abort(glue::glue(..., .envir = env), class = "stop_iteration_error") 
11. stop_iteration_error() 
10. self$.sampler_iter() 
9. self$.next_index() 
8. self$.next_data() 
7. parent.env(x)$.iter$.next() 
6. `[[.enum_env`(b, 1) 
5. b[[1]] 
4. eval(lhs, parent, parent) 
3. eval(lhs, parent, parent) 
2. x %>% self$conv1() %>% nnf_relu() %>% self$conv2() %>% nnf_relu() %>% 
    nnf_max_pool2d(2) %>% self$dropout1() %>% torch_flatten(start_dim = 2) %>% 
    self$fc1() %>% nnf_relu() %>% self$dropout2() %>% self$fc2() 
1. model(b[[1]]$to(device = "cpu")) 
```

By the way, I've never installed `libomp` with brew. I agree that something related to MP would be the root cause, but I have no idea...

**Comment by dfalbel** [comment]
This error appeared in #180. But I am still trying to reproduce in a smaller example.
