### ISSUE TITLE
Can't connect URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.0.3/latest/Windows-cpu.zip'

### ISSUE THREAD

**Issue by bobshen0721** [mlverse/torch#267]
When I install torch, and I have a issue.

I can't connect  URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.0.3/latest/Windows-cpu.zip'
anyone can hele me ? plze

like this pic:
![image](https://user-images.githubusercontent.com/63269732/94685220-ae882f80-035b-11eb-9acb-d00368c524ab.png)

This's my sessionInfo:
![image](https://user-images.githubusercontent.com/63269732/94685552-2ce4d180-035c-11eb-960e-9a59b64e3546.png)

**Comment by dfalbel** [comment]
For now, a possible solution is to go to this page: https://github.com/mlverse/torch/actions/runs/276774726
and manually download the `Windows` file. You should then extract it to the path returned by:

```
system.file("deps", package = "torch")
```

**Comment by dirkschumacher** [comment]
Related to #325. It would probably be nice to extend the error message to point users to documentation on how to install the libraries manually. This is especially necessary for folks who work in [airgapped networks](https://en.wikipedia.org/wiki/Air_gap_%28networking%29) or behind some restrictive firewall.

**Comment by dfalbel** [comment]
We have a solution for air gapped environments proposed here: https://github.com/mlverse/torch/pull/439
I'll close this issue, please reopen if this still persists.
