### ISSUE TITLE
Segfault on GitHub Actions

### ISSUE THREAD

**Issue by wlandau** [mlverse/torch#271]
`torch` runs fine locally on my work Mac and RHEL 7 cluster, but I am running into segfaults when I develop a package on top of `torch` and test it with GitHub Actions. I reproduced the issue with https://github.com/wlandau/test-torch-ci-reprex.

* With current CRAN (0.1.0): https://github.com/wlandau/test-torch-ci-reprex/actions/runs/282416827.
* With  https://github.com/mlverse/torch/commit/9fb2ab1adfc7ab5680314be3801d17d80e649c31: https://github.com/wlandau/test-torch-ci-reprex/actions/runs/282429500

**Comment by dfalbel** [comment]
Sorry this is undocumented. In non-interactive environments we don't automatically download libtorch so you need to set the 
`TORCH_INSTALL=1` environment variable or manually run `install_torch` see here:

https://github.com/mlverse/torch/blob/master/.github/workflows/main.yaml#L35

**Comment by wlandau** [comment]
Awesome, thanks! `TORCH_INSTALL=1` works.
