### ISSUE TITLE
Developing CPU/GPU/TPU at home and on Colab - Question

### ISSUE THREAD

**Issue by chris-english** [mlverse/torch#273]
When exploring at home, which is only CPU capable, library(torch) downloads  CPU deps, and Lantern CPU build. Without specifying a runtime on Colab (which is to say CPU), GPU deps are downloaded. Changing Colab runtime to TPU still results in GPU download. 

Through the course of this experimenting, and reviewing runtime logs along the way, source of deps changes: google.storageapis on Colab and pytorch.org CPU at home. 

All this suggests a sophisticated, environment aware switch. Is it anticipated, going forward, a devtools::install_github('mlverse/torch', type = c('CPU','GPU','TPU')), for a given runtime under consideration.

Thanks.

**Comment by dfalbel** [comment]
We try to automatically find the OS and if CUDA is installed or not with a few heuristics that you can find here: https://github.com/mlverse/torch/blob/master/R/install.R#L166-L204

You can always use  `install_torch(type = "cpu")` or `install_torch(type="10.1")` (10.1 is the CUDA version) after the package installation. You can also set the env var `TORCH_INSTALL=0` to avoid the automatic installation of the additional libraries.

Regarding the download links: we have 2 libraries that are downloaded when you install torch: lantern and LibTorch. Lantern binaries are hosted in a google storage bucket and LibTorch is hosted by the PyTorch and can be downloaded from pytorch.org.

**Comment by chris-english** [comment]
But as to type='tpu', this would, at this time, be ahead of development, not done yet?

**Comment by dfalbel** [comment]
Yes, we don't currently support TPU's. And it would probably live in a different package offering a different device implementation like: https://github.com/pytorch/xla

**Comment by chris-english** [comment]
Thanks, I'll look at that and see what I can do with GPU. And finally learn SEXP constructions.
