### ISSUE TITLE
Problem with linking libnvToolsExt and libcudart on Ubuntu

### ISSUE THREAD

**Issue by mbergins** [mlverse/torch#298]
Hello,

I just installed torch on Ubuntu 20.04.1 LTS and encountered a small problem with installation. This was following along with blog entry:

https://blogs.rstudio.com/ai/posts/2020-09-29-introducing-torch-for-r/

After running install.packages for torch, I tried to load the library with:

```
> library(torch)
trying URL 'https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.5.0%2Bcu101.zip'
Content type 'application/zip' length 772579626 bytes (736.8 MB)
==================================================
downloaded 736.8 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.1.0/latest/Linux-gpu-101.zip'
Content type 'application/zip' length 1792706 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

Warning message:
Failed to install Torch, manually run install_torch(). /home/mbergins/R/x86_64-pc-linux-gnu-library/3.6/torch/deps/liblantern.so - libnvToolsExt.so.1: cannot open shared object file: No such file or directory 
> install_torch()
Error in cpp_lantern_init(normalizePath(install_path())) : 
  /home/mbergins/R/x86_64-pc-linux-gnu-library/3.6/torch/deps/liblantern.so - libnvToolsExt.so.1: cannot open shared object file: No such file or directory
```
The shared object file libnvToolsExt was present in the same deps directory though, it just appears that the appropriate simlink was missing. I fixed this with:

`ln -s libnvToolsExt-3965bdd0.so.1 libnvToolsExt.so.1`

I'm also assuming that this link should exist, but was missed in the installation. Same problem with another shared library file:

```
> install_torch()
Error in cpp_lantern_init(normalizePath(install_path())) : 
  /home/mbergins/R/x86_64-pc-linux-gnu-library/3.6/torch/deps/liblantern.so - libcudart.so.10.1: cannot open shared object file: No such file or directory
```
Once again fixed by adding a symlink in deps:

`ln -s libcudart-1b201d85.so.10.1 libcudart.so.10.1`

Everything else has gone smoothly, but wanted to point out this small speed bump I encountered. I'm not sure if there is anything to fix in the library, but wanted to make a post somewhere in case another Ubuntu (or other OS, I suppose) user hits the same problem.

Thanks for your work bring machine learning tools to R, looking forward to writing some code with torch.

**Comment by dfalbel** [comment]
@mbergins Thanks for the detailed information. This is the first time I see this problem with the installation. 
I'll leave this post opened to see if others users hit this. 

The file names are strange to me, maybe there was a random crash when copying/extracting the zip file to the deps folder?

**Comment by mbergins** [comment]
Could be possible, also I missed this set of errors that appeared during the installation compilation phase:

```
In file included from device.cpp:2:
torch_types.h:7: warning: "LANTERN_HOST_HANDLER" redefined
    7 | #define LANTERN_HOST_HANDLER lantern_host_handler();
      | 
In file included from device.cpp:1:
lantern/lantern.h:35: note: this is the location of the previous definition
   35 | #define LANTERN_HOST_HANDLER
      | 
In file included from device.cpp:1:
lantern/lantern.h: In function ‘bool lanternInit(const string&, std::string*)’:
lantern/lantern.h:4028:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
 4028 | bool lanternInit(const std::string &libPath, std::string *pError)
      |      ^~~~~~~~~~~
```

Looks like something related to compiling device.ccp that causes some sort of problem with liblantern. Probably outside the scope of the package, but maybe relevant to anyone seeing the same problem.

**Comment by uthline** [comment]
@mbergins
I also had similar experience with you.
I solve my problem like below:

```sh
ln -s libnvToolsExt.so.1 libnvToolsExt.so
ln -s libcudart.so.10.1 libcudart.so
```
