### ISSUE TITLE
Problems with repeat

### ISSUE THREAD

**Issue by emauryg** [mlverse/torch#319]
I'm having trouble with repeat_interleave. I am trying to obtain some sort of torch.repeat behavior, but even just using the example from the website gives me an error on R studio https://mlverse.github.io/torch/reference/torch_repeat_interleave.html

x = torch_tensor(c(1, 2, 3))
x$repeat_interleave(2)

Error in (function (self, repeats, dim)  : 
  repeats has to be Long tensor (repeat_interleave_common at C:\b\windows\pytorch\aten\src\ATen/native/Repeat.h:10)
(no backtrace available)

I'm running torch 0.1.1

Is there a way around this?

**Comment by dfalbel** [comment]
Hi @emauryg 

You can do something like this as a workaround. I'll work so the conversion happens automatically in the next version.

``` r
library(torch)
x = torch_tensor(c(1, 2, 3))
x$repeat_interleave(repeats = torch_scalar_tensor(2L))
#> torch_tensor
#>  1
#>  1
#>  2
#>  2
#>  3
#>  3
#> [ CPUFloatType{6} ]
```

<sup>Created on 2020-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by emauryg** [comment]
Thank you!
