### ISSUE TITLE
Printing tensor$grad_fn crashes R session

### ISSUE THREAD

**Issue by dirkschumacher** [mlverse/torch#320]
Printing the object behind any tensor in $grad_fn crashes my R Session (R 4.0.2, mac)

```R
reprex::reprex({ # gets executed in a separate process so it is safe to run
  library(torch)
  x <- torch_tensor(1)
  print(x$grad_fn)
})

```

**Comment by dfalbel** [comment]
Hi @dirkschumacher ! Thanks for the report! #312 should fix it. I'll merge as soon as CI passes

**Comment by dirkschumacher** [comment]
Thanks!
