### ISSUE TITLE
Check hashes of downloaded libraries

### ISSUE THREAD

**Issue by dirkschumacher** [mlverse/torch#324]
One option to increase securiy of the package is to hardcode the hashes of the files downloaded in [`R/install.R`](https://github.com/mlverse/torch/blob/master/R/install.R) and check the hashes after downloading.

This protects against corrupted files during transmission and also protects somewhat againts attacks on the storage servers or MITM attacks.

Just an idea.

**Comment by dfalbel** [comment]
I agree! I don't see a way of doing it for the development version of Lantern, as the hashes will change all the time.
But we can definitely do it for LibTorch binaries and for Lantern in the CRAN releases.

**Comment by dirkschumacher** [comment]
We could use `md5` hashes checked with `tools::md5sum`, not the best, but those require no additional packages.
