### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by jwijffels** [mlverse/torch#33]
Great work! 
Just a message to indicate that I really look forward in having access to libtorch directly from R. Especially the lstm, gru, rnn functionalities which are very usefull in NLP.

**Comment by dfalbel** [comment]
Thanks @jwijffels 

Hopefully this is coming soon :)

**Comment by jwijffels** [comment]
This package will be great nlp complements to packages
- https://github.com/bnosac/sentencepiece 
- https://github.com/bnosac/word2vec 
which I've uploaded to CRAN last week once lstm/gru/rnn are wrapped up! 

There are also many c++ resources on torch, would be great to have possibility to wrap these ourselved by building on top of this package.

Anyhow thanks. Tremendous effort you are doing here!

**Comment by dfalbel** [comment]
Can you point to an extension that you would want to wrap?

Probably for c++ extensions we will need to create something similar to lantern that wraps the c++ code in a c compatible API that can then be wrapped in R.

**Comment by jwijffels** [comment]
There are many C++ usages at https://github.com/prabhuomkar/pytorch-cpp

But some algorithm I needed personally was (Bidirectional)-LSTM-CRF e.g. so that I could use it to detect language switching, similarly as https://github.com/hiredscorelabs/seqtolang, namely the model at https://github.com/hiredscorelabs/seqtolang/blob/master/seqtolang/model.py
Or similar models Bi-LSTM-CRF models as implemented in Python using pytorch at
- https://github.com/jidasheng/bi-lstm-crf
- https://github.com/allanj/pytorch_lstmcrf
- https://github.com/jiesutd/NCRFpp

All the building blocks seem to be there now
- I put package sentencepiece just on CRAN today for splitting text in subwords: https://CRAN.R-project.org/package=sentencepiece
- getting the embeddings either pretrained or with package word2vec which I also put on CRAN today: https://CRAN.R-project.org/package=word2vec
- just need to implement LSTM-CRF stack using this package

**Comment by jwijffels** [comment]
Hello again. Just wondering if there is also a lantern part of torch.optim?

**Comment by dfalbel** [comment]
@jwijffels not yet. it will be implemented right after the layers

**Comment by jwijffels** [comment]
looking forward !

**Comment by dfalbel** [comment]
Exactly. 

For 3) we can say that in fact the c++ living in https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/src/nn/modules/rnn.cpp is a rewrite of the python module living in https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L25 

For 2 ) we can't write code directly in Rcpp binding to libtorch so we, first write a C compatible wraper in lantern and then we write Rcpp bindings to lantern.
