### ISSUE TITLE
Post-install script downloading shared libraries fails in multi-user environment (Linux)

### ISSUE THREAD

**Issue by strimmerlab** [mlverse/torch#338]
##### installation (as superuser):
install.packages("torch", "/usr/local/lib/R/site-library")

##### then run (as standard user)
library("torch")

##### this downloads shared libraries then fails
Failed to install Torch, manually run install_torch(). 

### Cause of the problem

A standard user has no write access to torch:::install_path()
In the above this is "/usr/local/lib/R/site-library/torch//deps"
Only the superuser can do this.

#### Install as superuser as follows:

install.packages("torch", "/usr/local/lib/R/site-library")
torch::install_torch()   

Therefore, please amend the installation instructions correspondingly at
https://torch.mlverse.org/docs/ and https://torch.mlverse.org/packages/#installation-and-use

### Better solution:

Run the torch::install_torch() as post-install script automatically
whenever install.packages() is called.

However, I am not sure this is actually supported by install.packages()

**Comment by dfalbel** [comment]
We have made this slightly better in https://github.com/mlverse/torch/pull/522
Basically, if you set a `TORCH_HOME` environment variable, we will always install to that folder.
We also should show a better error message if there's no write permission to the default location.

**Comment by strimmerlab** [comment]
There are other R packages on CRAN that incorporate prebuilt libraries in the install process with requiring any post-install downloads  (and installing multiple copies in each user directory).

For example the "gert" packages downloads a static prebuild git library if needed:

https://CRAN.R-project.org/package=gert 
https://github.com/r-lib/gert/
https://github.com/r-lib/gert/blob/master/configure
