### ISSUE TITLE
Add private and active arguments to helper functions for dataset, nn_module, etc.

### ISSUE THREAD

**Issue by mattwarkentin** [mlverse/torch#344]
Discussed briefly in #343 

Submitting this as its own issue for tracking in new release.

**Comment by mattwarkentin** [comment]
Side comment: is there a reason why an instance of `dataset` also carries the `get_item()` method? Is this just residual code? Should this be removed to avoid confusion?
``` r
x <-
  torch::dataset(
  initialize = function() self$data <- mtcars, 
  .length = function() nrow(mtcars),
  .getitem = function(i) mtcars[i, ]
)
x()
#> <dataset>
#>   Public:
#>     .getitem: function (i) 
#>     .length: function () 
#>     add: function (other) 
#>     clone: function (deep = FALSE) 
#>     data: data.frame
#>     get_item: function (index) 
#>     initialize: function ()
x()$get_item(1)
#> Error:
```

**Comment by dfalbel** [comment]
Looks like it's just residual code. Removed in bfbfdc0

**Comment by mattwarkentin** [comment]
Also may want to update the `dataset` `@Description` to reflect updates, here is my attempt:

> All datasets that represent a map from keys to data samples should subclass this class. All subclasses should overwrite the `.getitem()` method, which supports fetching a data sample for a given key. Subclasses could also optionally overwrite `.length()`, which is expected to return the size of the dataset (e.g. number of samples) by many `~torch.utils.data.Sampler` implementations and the default options of `~torch.utils.data.DataLoader`.

**Comment by dfalbel** [comment]
Thanks @mattwarkentin ! updated!
