### ISSUE TITLE
CUDA 11 support

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#348]
- [ ] Windows support
- [x] Linux support

**Comment by grantmcdermott** [comment]
Commenting just to get an automatic notification once this is closed ;-)

(The automatic CUDA lib updates on my Arch system broke the GPU support for this R implementation... grrrr.)

**Comment by dfalbel** [comment]
The dev version should work with CUDA 11.0 now on Linux. Note that LibTorch doesn't seem to support CUDA > 11.0, eg 11.2 for instance. Not sure if Arch is already there though.

**Comment by grantmcdermott** [comment]
Excellent, thanks @dfalbel.

**Comment by kevinykuo** [comment]
CUDA 11.2 working on Ubuntu 20.04 with default installation procedure (`library(torch)`)
