### ISSUE TITLE
Loading a pre-trained model

### ISSUE THREAD

**Issue by danielnjoo** [mlverse/torch#350]
Hi, is there any example or support for loading pre-trained Torch models, e.g. Inception_v3?

Thanks

**Comment by dfalbel** [comment]
Yes, but currently you need to reimplement the architecture and just load the model weights.
You can find examples of that here: https://github.com/mlverse/torchvision/blob/main/R/models-resnet.R

**Comment by danielnjoo** [comment]
I realize adding a [vignette for this](https://github.com/mlverse/torchvision/issues/8) is on your roadmap, and that there's a more than thorough walk-through [here](https://github.com/mlverse/torchbook/blob/master/image_classification.Rmd), though I'm still working on getting this to work on a minimum example (single image)

**Comment by dfalbel** [comment]
Actually the model always takes a tensor. I mean, you can do something like:

``` r
library(torchvision)
library(torch)
resnet <- model_resnet18(pretrained = TRUE)
img <- torch_randn(1, 3, 224, 224)
output <- resnet(img)
output$shape
#> [1]    1 1000
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
