### ISSUE TITLE
An error with `torch_transpose`

### ISSUE THREAD

**Issue by kcf-jackson** [mlverse/torch#359]
Reporting an error with the function `torch_transpose` that occurs on both the CRAN and development versions. 

The error: `Error: cpp_torch_namespace_transpose_self_Tensor does not exist`

Reproducible example and the output:

```{r}
library(torch)
x <- torch_tensor(matrix(1:4, 2, 2))
torch_transpose(x)
#> Error: cpp_torch_namespace_transpose_self_Tensor does not exist
#> Run `rlang::last_error()` to see where the error occurred.

rlang::last_error()
#> <error/value_error>
#> cpp_torch_namespace_transpose_self_Tensor does not exist
#> Backtrace:
#>  1. torch::torch_transpose(x)
#>  2. torch:::call_c_function(...)
#>  3. torch:::value_error("{fun_name} does not exist")
```

**Comment by dfalbel** [comment]
Actually, `torch_transpose` always requires you to pass what dimensions are tranposed. For example:

```
library(torch)
x <- torch_tensor(matrix(1:4, 2))
x$transpose(1,2)
```

You can use `x$t()` for a shortcut that doesn't require arguments.

**Comment by kcf-jackson** [comment]
Thanks! I'll close the issue.
