### ISSUE TITLE
VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by jwijffels** [mlverse/torch#36]
I'm mainly developing on Windows using a cpu. 
At `library(torchr)` this downloaded https://github.com/mlverse/torch/blob/master/R/lantern_install.R#L14 the precompiled dll's from libtorch.
When loading the package again `library(torchr)` it complained about VCRUNTIME140_1.dll not being available on my computer. 
![Knipsel](https://user-images.githubusercontent.com/1710810/83735447-b4d9f980-a650-11ea-996b-bd0581865b00.PNG)

Had to install the latest version of Microsoft Visual C++ Redistributable for Visual Studio 2019 to get rid of the error message (I deleted it 3 weeks ago while doing some computer cleanup) and get started.

**Comment by dfalbel** [comment]
Thanks for letting us know. We will add this to the installation docs. 

Please note, that you will still have a hard time using this package on windows because of #31. Without it you will get a segfault every time an error is raise by libtorch.

**Comment by jwijffels** [comment]
The issues seem not visible to external users or at least there are no comments in #31 
Windows is always a fun experience :)

**Comment by dfalbel** [comment]
Ah sorry, there's no description. The issue is that since libtorch is compiled with Visual Studio and R/Rcpp code is compiled with MinGW, if the error is raised by libtorch then 💣
