### ISSUE TITLE
nnf_batch_norm error: argument "running_mean" is missing, with no default

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#376]
Hi, 
When applying nnf_batch_norm I get the following error:

argument "running_mean" is missing, with no default

From my understanding Keras and Tensorflow did not require this parameter when using layer_batch_normalization and from my understanding shouldn't t nnf_batch_norm calculate "running_mean"?

Can someone please provide a reproducible example showing the use of nnf_batch_norm ?

Thank you.

**Comment by skeydan** [comment]
Hi, you'll probably want to use the module (`nn_batchnorm2d()`) instead of the function, `nnf_batchnorm()`?

**Comment by dominikj2** [comment]
Thank you. That works.
