### ISSUE TITLE
torch_gather() can't be run on gpu

### ISSUE THREAD

**Issue by jimwhamilton** [mlverse/torch#382]
``` r
library(torch)


device="cpu"

x <- torch_tensor(matrix(seq(1:4), nrow=2, ncol=2))$to(device=device)
index <- torch_unsqueeze(torch_tensor(c(1,2), dtype=torch_long()), 2)$to(device=device)

y <- torch_gather(x, dim=2, index)



device="cuda"

x <- torch_tensor(matrix(seq(1:4), nrow=2, ncol=2))$to(device=device)
index <- torch_unsqueeze(torch_tensor(c(1,2), dtype=torch_long()), 2)$to(device=device)

y <- torch_gather(x, dim=2, index)
#> Error: Can't convert cuda tensor to R. Convert to cpu tensor before.
```

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dfalbel** [comment]
Hi @jimwhamilton ! Thanks for the report! This was fixed in https://github.com/mlverse/torch/pull/317 and should be working in the dev version of torch that can be installed with:

```
remotes::install_github("mlverse/torch")
```

The fix will be available in the next CRAN release.

**Comment by jimwhamilton** [comment]
Upgraded to dev version as suggested and can confirm it all works now.

Thanks!
