### ISSUE TITLE
Error in lantern_install_lib

### ISSUE THREAD

**Issue by kailex** [mlverse/torch#397]
After upgrading to torch v0.2 and running `install_torch()` I get this error:

> trying URL 'https://download.pytorch.org/libtorch/cu92/libtorch-cxx11-abi-shared-with-deps-1.7.0%2Bcu92.zip'
Content type 'application/zip' length 639737153 bytes (610.1 MB)
==================================================
downloaded 610.1 MB
Error in lantern_install_lib(library_name = library_name, library_url = library_info$url,  : 
  The file downloaded from 'https://download.pytorch.org/libtorch/cu92/libtorch-cxx11-abi-shared-with-deps-1.7.0%2Bcu92.zip' does not match the expected md5 hash 'bd2cca6179e9f136c736feb9f5cd5f73'. The observed hash is 'b27db365dbd422a6af024127bfb0bb9b'. Due to security reasons the installation is stopped.

`install_torch(type="cpu")` runs without problems.

**Comment by dfalbel** [comment]
Hi @kailex ! Thanks for reporting. Indeed, the md5 hash for that file seems to have changed. I'll make a patch release as soon as possible. This PR will fix it: https://github.com/mlverse/torch/pull/398

You can install that version with: `remotes::install_github("mlverse/torch@cuda9.2-md5hash")`

Another possible solution is to update your cuda installation to 10.1 or 10.2
