### ISSUE TITLE
cpp_torch_method_norm_self_Tensor_dim_IntArrayRef does not exist

### ISSUE THREAD

**Issue by kailex** [mlverse/torch#407]
When I try to run `nnf_normalize(torch_tensor(1:5))` I get the following error:

> Error: cpp_torch_method_norm_self_Tensor_dim_IntArrayRef does not exist
Run `rlang::last_error()` to see where the error occurred.

`rlang::last_error()` gives

> <error/value_error>
cpp_torch_method_norm_self_Tensor_dim_IntArrayRef does not exist
Backtrace:
>1. torch::nnf_normalize(torch_tensor(1:5))
>2. input$norm(p, dim, keepdim = TRUE)
>3. torch:::o(x, x$private, ...)
>4. torch:::call_c_function(...)
>5. torch:::value_error("{fun_name} does not exist")
Run `rlang::last_trace()` to see the full context.

**Comment by dfalbel** [comment]
Thanks for reporting @kailex ! Should be fixed in the dev version.
