### ISSUE TITLE
scatter_ behaviour

### ISSUE THREAD

**Issue by kailex** [mlverse/torch#413]
Running the code below 

    x <- torch_ones(2, 3, device = "cpu")
    dim <- 2
    idx <- torch_tensor(2:3, device = "cpu")
    src <- -10
    x$scatter_(dim, idx$detach()$unsqueeze(2), src)

produces correct result:

>torch_tensor
>1 -10  1
>1  1 -10
>[ CPUFloatType{2,3} ]

But trying to run this code on GPU results in error:

    x <- torch_ones(2, 3, device = "cuda:0")
    dim <- 2
    idx <- torch_tensor(2:3, device = "cuda:0")
    src <- -10
    x$scatter_(dim, idx$detach()$unsqueeze(2), src)

> Error: Can't convert cuda tensor to R. Convert to cpu tensor before.
> Traceback:
> 
> 1. x$scatter_(dim, idx$detach()$unsqueeze(2), src)
> 2. o(x, x$private, ...)
> 3. private$`_scatter_`(dim, index, value = src)
> 4. o(x, x$private, ...)
> 5. call_c_function(fun_name = "scatter_", args = args, expected_types = expected_types, 
>  .     nd_args = nd_args, return_types = return_types, fun_type = "method")
> 6. all_arguments_to_torch_type(args, expected_types)
> 7. argument_to_torch_type(all_arguments[[nm]], expected_types[[nm]], 
>  .     nm)
> 8. get("ptr", as_1_based_tensor(obj), inherits = FALSE)
> 9. as_1_based_tensor(obj)
> 10. as.numeric(e)
> 11. as.double.torch_tensor(e)
> 12. as_array(x)
> 13. as_array.torch_tensor(x)
> 14. runtime_error("Can't convert cuda tensor to R. Convert to cpu tensor before.")
> 15. rlang::abort(glue::glue(..., .envir = env), class = "runtime_error")
> 16. signal_abort(cnd)
> Error: Can't convert cuda tensor to R. Convert to cpu tensor before. 

Apparently the `scatter_` operation should work when all tensors are on GPU.

**Comment by dfalbel** [comment]
Thanks for reporting @kailex. This is a bug and I'll fix it as soon as possible

**Comment by kailex** [comment]
Thank you!

**Comment by dfalbel** [comment]
Hi @kailex 

I think this was fixed in https://github.com/mlverse/torch/commit/2f913fa90a630d8d6a263dce77c433fea60c3b92
I get the correct result with the current dev version:

```
> x <- torch_ones(2, 3, device = "cuda:0")
> dim <- 2
> idx <- torch_tensor(2:3, device = "cuda:0")
> src <- -10
> x$scatter_(dim, idx$detach()$unsqueeze(2), src)
torch_tensor
 1 -10  1
 1  1 -10
[ CUDAFloatType{2,3} ]
```
