### ISSUE TITLE
Please include a higher `timeout=` option in `install_torch()` to prevent download file 60s timeout

### ISSUE THREAD

**Issue by cregouby** [mlverse/torch#437]
Hello, 

Initial `library(torch)` or manual `install_torch()` very often fails due to large file download timeout, as mentionned by https://github.com/mlverse/torch/issues/186#issuecomment-735576520

### Current situation
Usual home internet connection do not succeed to download libtorch (130MB+ ) before the default `timeout=60`, making the first contact with the package frustrating, and diverting the user from the goal to build and train a neural network.

Even if problem is made explicit during the `install_torch()` process by the log : 
```(r)
Warning messages:
1: In utils::download.file(library_url, temp_file) :
  downloaded length 44901568 != reported length 141774525
2: In utils::download.file(library_url, temp_file) :
  URL 'https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.7.1.zip': Timeout of 60 seconds was reached
3: Failed to install Torch, manually run install_torch(). download from 'https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.7.1.zip' failed 
```
But it is not obvious for most users on how to increase the timeout with the global `options(timeout = 360)`

## Proposed improvement
add a `timeout=360` option in the `install_torch()` function so that
- solution to the problem is self contained in the documentation
- an adapted default value gives a much higher success-rate of initial installation 

Thanks a lot

**Comment by GitHubGeniusOverlord** [comment]
I noted, that even the timeout of 600seconds can be insufficient, depending on the connection. Pumping it up to 1000 can't hurt in my opinion. Low priority.
