### ISSUE TITLE
Deploying model to mobile devices

### ISSUE THREAD

**Issue by LordRudolf** [mlverse/torch#440]
I would like to ask about the R Torch deployment possibilities.

I know there exist a user-friendly manual to torch python counterpart - pytorch: https://pytorch.org/mobile/android/ .
Also, there is a TensorFlow package dedicated for R tensorflow models bringing into production: https://github.com/rstudio/tfdeploy

But what about R torch - is there options to run R trained torch models on Android devices? If yes, a manual would be really useful. If not, then I would Iappreciate hearing whether it is included in future plans?

**Comment by dfalbel** [comment]
In 0.2 we added very basic support for JIT in torch, so you can basically export an R function that makes tensor computations to a TorchScript file `.pt` file. Once you have a `.pt` file, you could just follow PyTorch's Android guide starting from section 2.

We plan to make support for JIT more robust in the near future. You can see docs here: https://torch.mlverse.org/docs/reference/jit_save.html

**Comment by LordRudolf** [comment]
Awesome. Thanks!
