### ISSUE TITLE
copying tensors to a different memory storage indicator

### ISSUE THREAD

**Issue by emauryg** [mlverse/torch#441]
I'm trying to perform an optimization that requires me to keep the parameter values with the best likelihood, but my optimization procedure does not guarantee monotonic increase of the likelihood. I would like to be able to store the parameters that produce the best likelihood thus far, while continuing to iterate through the optimization procedure. 

`    if (new_elbo$item() > max_elbo){
      max_elbo = new_elbo$item()
      EM_res = list(theta_res=theta$detach(), elbo_res=new_elbo$detach(), Xi_res=Xi$detach(), 
              Sigma = Sigma$detach(), nu_res = nu$detach(), eta_res = eta$detach(), gamma_sigma_res=gamma_sigma$detach(), 
              zeta_res = zeta$detach(),
              covs_res = covs, T0_res=T0) 
    }`

However, when  I tried something as above with detach() I only get a copy of the values at the end of all the iterations which is not the optimal configuration of parameters. 

Is there a way of just copying each parameter while not pointing to the same location in memory? 

Thank you!

**Comment by dfalbel** [comment]
I think you are looking for the `clone` method:

``` r
library(torch)

x <- torch_tensor(1)
x$add_(1)
#> torch_tensor
#>  2
#> [ CPUFloatType{1} ]

y <- x$clone()
x$add_(1)
#> torch_tensor
#>  3
#> [ CPUFloatType{1} ]
y
#> torch_tensor
#>  2
#> [ CPUFloatType{1} ]
```

<sup>Created on 2021-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by emauryg** [comment]
Oh great yeah that is exactly what I was looking for. I noticed that the reference tab on the website does not include descriptions on clone() nor detach(). Could this be fixed?

Thank you!

**Comment by dfalbel** [comment]
Glad it worked! Thanks for reporting @emauryg !

I added a small example to the docs in this commit: https://github.com/mlverse/torch/commit/adc505a3cd9f2e71501f90b3789d190dfc47c9cf

Changes will appear here: https://torch.mlverse.org/docs/articles/tensor/index.html#clone in the next release!
