### ISSUE TITLE
mean() returning NA

### ISSUE THREAD

**Issue by Athospd** [mlverse/torch#445]
``` r
library(torch)
x <- torch_tensor(1)
y <- torch_tensor(1)
mean((y - x)^2)
#> Warning in mean.default((y - x)^2): argument is not numeric or logical:
#> returning NA
#> [1] NA
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dfalbel** [comment]
Thanks! in the meantime maybe you can use `torch_mean()`.

**Comment by skeydan** [comment]
just my very personal & subjective opinion .... I was thinking analogously with tensorflow ... I personally prefer not having these kinds of generics, as I like keeping track of whether I'm dealing with tensors or R values ... but that's probably just me

**Comment by dfalbel** [comment]
I think it's nice for quick experimentation!
`+`, `-`, `^` are all generics too, and make code much more readable than having to use `torch_add`, `torch_sub`, `torch_pow`, etc.
