### ISSUE TITLE
"get started" link on main page broken

### ISSUE THREAD

**Issue by maxdrohde** [mlverse/torch#446]
The "get started" link on the main page is broken.

<img width="1562" alt="Screen Shot 2021-01-21 at 1 07 51 AM" src="https://user-images.githubusercontent.com/25734232/105315632-3b622d80-5b85-11eb-9f81-5f84a3bddd6e.png">

**Comment by dfalbel** [comment]
Hi @maxdrohde ! Thanks for reporting!

**Comment by dfalbel** [comment]
Should be fixed in https://github.com/mlverse/torch/commit/a5512ed5e76aae7fc3f104e97174462e0a9e7f67

Thanks!
