### ISSUE TITLE
Extending the "Serialization" Vignette for loading models saved in Python

### ISSUE THREAD

**Issue by jlombard314159** [mlverse/torch#463]
Hi - I am attempting to develop code to use models trained in Python via PyTorch read into R with the end product being a Shiny application to use these models via Rtorch for predictions. As a first step, I need to read a .pt file into R. 

I have played around with the example provided in the Serialization vignette and I am using the Alexnet example as a starting point [see here](https://github.com/mlverse/torchvision/blob/main/R/models-alexnet.R#L2-L63)

Unfortunately the R portion of my code seems to fail. I am hoping I can get this simple example to work, then make a request to add this in order to have a full example in the "Serialization" vignette.

I am new to this, so I apologize if there is a stupid error in here somewhere. 

Python Code:

```
import torch
import numpy as np

#Make up data
madeUpData_x = np.random.rand(1000,100)
madeUpData_y = np.random.rand(1000,1)
madeUpData_y = madeUpData_y.round()
train_py_X = torch.from_numpy(madeUpData_x).float()

train_py_Y = torch.from_numpy(madeUpData_y).float()


class simpleMLP(torch.nn.Module):
    def __init__(self):
        super(simpleMLP, self).__init__()
        self.modelFit = torch.nn.Sequential(
            torch.nn.Linear(100,20),
            torch.nn.ReLU(),
            torch.nn.Linear(20,1),
            torch.nn.Sigmoid()
        )
    def forward(self, x):
        x =self.modelFit(x)

        return x

model = simpleMLP()

def modelTrainer(data_X,data_Y,model):
    criterion = torch.nn.BCELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

    for epoch in range(100):

        optimizer.zero_grad()

        yhat = model(data_X)

        loss = criterion(yhat,data_Y.unsqueeze(1))

        loss.backward()
        optimizer.step()

modelTrainer(data_X = train_py_X,data_Y = train_py_Y,model = model)

#-----------------------------------------------------------------
#save the model 

torch.save(model,f="yourPath/babyTest.pt",
           _use_new_zipfile_serialization=True)


```

R Code: 

```

library(torch)
#-------------------------------------------------------------------------------


simpleMLP <- torch::nn_module(
  "simpleMLP",
  initialize = function(){
    
    self$modelFit <- nn_sequential(nn_linear(100,20),
                                   nn_relu(),
                                   nn_linear(20,1),
                                   nn_sigmoid())
    
  },
  forward = function(x){
    
    x <- self$modelFit
    return(x)
    
  }
)

model_JAL <- function() {
  
  model <- simpleMLP()
  
  
  state_dict_path <- "path/babyTest.pt"
  
  state_dict <- torch::load_state_dict(state_dict_path)
  model$load_state_dict(state_dict)
  
  
  model
}

```

The R part of the code that fails is the torch::load_state_dict(). I assume there is an error in the creation of the class in R. I can run the AlexNet example just fine. 

I hope I made this reproducible, but if not please let me know.

**Comment by dfalbel** [comment]
Hi @jlombard314159 

Thanks opening the issue! I think the problem is in how you are saving from python:

You are saving the entire model but loading with `load_state_dict`: you probably want `torch.save(model.state_dict(), ...)`. 

There's a caveat here though, `model.state_dict()` returns a Python **ordered dict**, and this is not possible to load from LibTorch (and in R too), so you need to convert the OrderedDict to a Dict before saving. (see eg: https://stackoverflow.com/questions/20166749/how-to-convert-an-ordereddict-into-a-regular-dict-in-python3 )

Also the I think the `forward` method of your module is not doing what you would expect. I think you want:

```
forward = function(x){ 
   self$modelFit(x) 
}
```

Let me know if this helps!

**Comment by jlombard314159** [comment]
Hi, @dfalbel Thank you for responding. I did play around with the ```model.state_dict()``` but neglected to realize it was an ordered dictionary. Unfortunately, that did not fix my issue. 

My Python code is the same except now when I save the model I do:

``` 
stateDict = dict(model.state_dict())
torch.save(stateDict,f="path/babyTest.pth",_use_new_zipfile_serialization=True)
```

The stateDict is probably a bit silly, but I just wanted to verify some properties of the model before saving. My R code was modified per your suggestion for the forward step, thank you. 

I was having this same error, see below, previously where the Rcpp function ```cpp_load_state_dict``` fails in an unexpected way. I attempted to see if that function could have some sort of issue with it, but it all looks fine. But my rcpp debugging skills are poor. See below for where the code errors:

![image](https://user-images.githubusercontent.com/18014459/106975529-f527d500-6713-11eb-9b4a-519de8e5cdf1.png)

I believe it is still with how I save the model in Python. I double checked that I can train models in R with just the torch package. I also checked that I can load models that I trained and saved all from R using torch. I played around a bit with torch.save() in Python, but nothing seemed to really help. 

For a complete example of code, here is my updated code, below.

Python:
```
#---------------------------------------------

import torch
import numpy as np

#Make up data

madeUpData_x = np.random.rand(1000,100)
madeUpData_y = np.random.rand(1000,1)
madeUpData_y = madeUpData_y.round()
train_py_X = torch.from_numpy(madeUpData_x).float()

train_py_Y = torch.from_numpy(madeUpData_y).float()


class simpleMLP(torch.nn.Module):
    def __init__(self):
        super(simpleMLP, self).__init__()
        self.modelFit = torch.nn.Sequential(
            torch.nn.Linear(100,20),
            torch.nn.ReLU(),
            torch.nn.Linear(20,1),
            torch.nn.Sigmoid()
        )
    def forward(self, x):
        x =self.modelFit(x)

        return x

model = simpleMLP()
#Set up weights before the criterion
#then put as inputs to the loss fxn
#Then use reduction in the bce loss also

def modelTrainer(data_X,data_Y,model):
    criterion = torch.nn.BCELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

    for epoch in range(100):

        optimizer.zero_grad()

        yhat = model(data_X)

        loss = criterion(yhat,data_Y.unsqueeze(1))

        loss.backward()
        optimizer.step()

modelTrainer(data_X = train_py_X,data_Y = train_py_Y,model = model)

#-----------------------------------------------------------------
#save the model 
stateDict = dict(model.state_dict())
torch.save(stateDict,f="path/babyTest.pth",_use_new_zipfile_serialization=True)


```

R Code: 

```
library(torch)
#Run below to see if it worked for you
y <- torch_tensor(array(runif(8),dim = c(2,2,2)),dtype = torch_float64())
#-------------------------------------------------------------------------------


simpleMLP <- torch::nn_module(
  "simpleMLP",
  initialize = function(){
    
    self$modelFit <- nn_sequential(nn_linear(100,20),
                                   nn_relu(),
                                   nn_linear(20,1),
                                   nn_sigmoid())
    
  },
  forward = function(x){
    self$modelFit(x)
    }
)

model_JAL <- function(progress = TRUE, ...) {
  
  model <- simpleMLP()
  
  state_dict_path <- "path/babyTest.pt"
  
  state_dict <- torch::load_state_dict(state_dict_path)
  model$load_state_dict(state_dict)
  
  model
}

```

**Comment by dfalbel** [comment]
Your code seems to work as expected for me. I just tweaked the paths to something relative to my working dir.
Are you sure all paths are correct?

**Comment by jlombard314159** [comment]
I did double check my paths this morning but I get that same error. Maybe I am misspecifying the path syntax. My actual path looks like:

``` 
torch.save(stateDict,f="C:/Users/jlombardi/Documents/GitLabCode/nnplay/Rtorch/babyTest.pth",
           _use_new_zipfile_serialization=True)
```
And my R code uses that for the path as well.

I am going to have a coworker test the code for me. I am worried that I botched something while installing torch or some other user installation error. It seems like there is an error in my Python code or maybe with 

Would it be helpful to post more info on my software specs? I am using Torch version 1.4.0 in Python, and I am using 3.8 Conda as my interpreter.

**Comment by jlombard314159** [comment]
As an update - my coworker can run the code fine also. I updated PyTorch to 1.7.1 in Python and am hoping that helps. I am going to compare my system to my coworkers and update accordingly. 

If this example is useful, would it be OK to add to the Vignette? If so - is the process to set up a pull request? I am not great with the GitHub so I just don't know the formal process. Thanks!

**Comment by dfalbel** [comment]
Oh, It can definitely be related to PyTorch's version. It should work version >= 1.6 though.
Sure! Adding this to the vignette would be great! A PR is the best way for us, but no formal requirements!

**Comment by jlombard314159** [comment]
I believe I did the pull request correctly. I added minor notes from this issue. Thank you again for your help. Feel free to close this (or I can) once the pull request is approved.

**Comment by dfalbel** [comment]
Thanks very much @jlombard314159 ! Your PR looks great and I just merged it!
