### ISSUE TITLE
num_workers>0 in dataloader returns error

### ISSUE THREAD

**Issue by myoung3** [mlverse/torch#467]
Tested in versions 3.6.2 and 4.0.2

Code is from [this example](https://torch.mlverse.org/start/custom_dataset/), except i changed `num_workers`

``` r
> library(torch)
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(palmerpenguins)
>
>
> penguins %>% glimpse()
Rows: 344
Columns: 8
$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ade…
$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgers…
$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1,…
$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1,…
$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 18…
$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475,…
$ sex               <fct> male, female, female, NA, female, male, female, mal…
$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 200…
>
> penguins_dataset <- dataset(
+
+   name = "penguins_dataset",
+
+   initialize = function(df) {
+
+     df <- na.omit(df)
+
+     # continuous input data (x_cont)
+     x_cont <- df[ , c("bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "year")] %>%
+       as.matrix()
+     self$x_cont <- torch_tensor(x_cont)
+
+     # categorical input data (x_cat)
+     x_cat <- df[ , c("island", "sex")]
+     x_cat$island <- as.integer(x_cat$island)
+     x_cat$sex <- as.integer(x_cat$sex)
+     self$x_cat <- as.matrix(x_cat) %>% torch_tensor()
+
+     # target data (y)
+     species <- as.integer(df$species)
+     self$y <- torch_tensor(species)
+
+   },
+
+   .getitem = function(i) {
+     list(x_cont = self$x_cont[i, ], x_cat = self$x_cat[i, ], y = self$y[i])
+
+   },
+
+   .length = function() {
+     self$y$size()[[1]]
+   }
+
+ )
>
> train_indices <- sample(1:nrow(penguins), 250)
>
> train_ds <- penguins_dataset(penguins[train_indices, ])
>
> train_dl <- train_ds %>% dataloader(batch_size = 16, shuffle = TRUE,num_workers=2)
>
> train_dl$.iter()$.next()
Error: callr subprocess failed: external pointer is not valid
Run `rlang::last_error()` to see where the error occurred.
>

```

**Comment by myoung3** [comment]
``` r
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS:   /opt/R/R-4.0.2/lib/R/lib/libRblas.so
LAPACK: /opt/R/R-4.0.2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] palmerpenguins_0.1.0 dplyr_1.0.4          torch_0.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       magrittr_2.0.1   tidyselect_1.1.0 bit_4.0.4
 [5] R6_2.5.0         rlang_0.4.10     fansi_0.4.2      tools_4.0.2
 [9] coro_1.0.1       utf8_1.1.4       cli_2.3.0        ellipsis_0.3.1
[13] bit64_4.0.5      assertthat_0.2.1 tibble_3.0.6     lifecycle_0.2.0
[17] crayon_1.4.0     processx_3.4.5   purrr_0.3.4      callr_3.5.1
[21] vctrs_0.3.6      ps_1.5.0         glue_1.4.2       compiler_4.0.2
[25] pillar_1.4.7     generics_0.1.0   pkgconfig_2.0.3

```

**Comment by dfalbel** [comment]
Hi! Thanks for reporting.
This is actually expected but not very well documented. When doing parallel data loading we currently do not support transferring tensors that live in the dataset object. We can modify the dataset to something like below.
We just don't do `torch_tensor` before assigning to the `self` object.

``` r
library(torch)
library(palmerpenguins)

penguins_dataset <- dataset(
  
  name = "penguins_dataset",
  
  initialize = function(df) {
    
    df <- na.omit(df) 
    
    # continuous input data (x_cont)   
    self$x_cont <- df[ , c("bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "year")] %>%
      as.matrix()
    
    
    # categorical input data (x_cat)
    x_cat <- df[ , c("island", "sex")]
    x_cat$island <- as.integer(x_cat$island)
    x_cat$sex <- as.integer(x_cat$sex)
    self$x_cat <- as.matrix(x_cat)
    
    # target data (y)
    species <- as.integer(df$species)
    self$y <- species
    
  },
  
  .getitem = function(i) {
    list(x_cont = self$x_cont[i, ], x_cat = self$x_cat[i, ], y = self$y[i])
  },
  
  .length = function() {
    length(self$y)
  }
  
)

train_indices <- sample(1:nrow(penguins), 250)
train_ds <- penguins_dataset(penguins[train_indices, ])
train_dl <- train_ds %>% 
  dataloader(batch_size = 16, shuffle = TRUE,num_workers=2)
train_dl$.iter()$.next()
#> $x_cont
#> torch_tensor
#>    36.2000    17.3000   187.0000  3300.0000  2008.0000
#>    52.7000    19.8000   197.0000  3725.0000  2007.0000
#>    41.3000    21.1000   195.0000  4400.0000  2008.0000
#>    42.5000    20.7000   197.0000  4500.0000  2007.0000
#>    50.4000    15.3000   224.0000  5550.0000  2008.0000
#>    50.5000    18.4000   200.0000  3400.0000  2008.0000
#>    59.6000    17.0000   230.0000  6050.0000  2007.0000
#>    51.5000    18.7000   187.0000  3250.0000  2009.0000
#>    45.3000    13.7000   210.0000  4300.0000  2008.0000
#>    42.9000    17.6000   196.0000  4700.0000  2008.0000
#>    41.1000    17.6000   182.0000  3200.0000  2007.0000
#>    40.2000    17.0000   176.0000  3450.0000  2009.0000
#>    44.0000    13.6000   208.0000  4350.0000  2008.0000
#>    48.7000    14.1000   210.0000  4450.0000  2007.0000
#>    46.1000    13.2000   211.0000  4500.0000  2007.0000
#>    45.0000    15.4000   220.0000  5050.0000  2008.0000
#> [ CPUFloatType{16,5} ]
#> 
#> $x_cat
#> torch_tensor
#>  2  1
#>  2  2
#>  1  2
#>  3  2
#>  1  2
#>  2  1
#>  1  2
#>  2  2
#>  1  1
#>  3  2
#>  3  1
#>  3  1
#>  1  1
#>  1  1
#>  1  1
#>  1  2
#> [ CPULongType{16,2} ]
#> 
#> $y
#> torch_tensor
#>  1
#>  2
#>  1
#>  1
#>  3
#>  2
#>  3
#>  2
#>  3
#>  1
#>  1
#>  1
#>  3
#>  3
#>  3
#>  3
#> [ CPULongType{16} ]
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by myoung3** [comment]
Thanks for clarifying, that makes perfect sense that torch tensors wouldn't be copied by R into subprocesses since they're not really in R memory. Adding a caveat about this to the help file would be great (either for `datasat` and/or for `dataloader`). 

I surmise from this that `train_dl$.iter()$.next()` is coercing each element returned by `.getitem` into a torch tensor? If that's the case, is there ever any reason why it's good to coerce using `torch_tensor` in `initialize` or `.getitem`?

**Comment by dfalbel** [comment]
Yes! I will do it ASAP!

The default `collate_fn` will convert R objects to `torch_tensors`. 

In general you don't need to convert using `torch_tensor` unless you want to use a torch function to do some kind of preprocessing inside them. For example, torchvision has a bunch of image processing functions that are backed by torch operations.

Unlike `self$...` objects, the `.getitem` can return `torch_tensor`s because we serialize them before returning from the subprocess to the main process.

**Comment by myoung3** [comment]
Yes that makes, data augmentation and image preprocessing operate on torch. In that case, I suppose those transformations might be able to occur in `.getitem` instead of in initialize?  I guess my question is then whether there are benefits to transforming in one place or the other. I suppose the benefit of transforming in `.getitem` is that if your files are on disk, you only need to read them once, whereas if you transformed in intialize you'd need to read then write then read again in .getitem.

I tried to figure how it's working in this [example](https://blogs.rstudio.com/ai/posts/2020-10-19-torch-image-classification/). From the source code of [bird_species_dasaset](bird_species_dataset), the transform argument gets passed to super$intialize via `...` and bird_species_dataset inherits image_folder_dataset. 

[I can't seem to find the definition of image_folder_dataset](https://github.com/mlverse/torchdatasets/search?q=image_folder_dataset), and the [help file ](https://torchvision.mlverse.org/reference/image_folder_dataset.html) doesn't say whether transform occurs in initialize (might be good to add this to the documentation).

In any case, where do you recommend transformations like that to occur?

**Comment by myoung3** [comment]
Ok I see I was looking in torchdatasets rather than torchvision for the definition of image_folder_dataset. I see in the [source ](https://github.com/mlverse/torchvision/blob/55f5de9e2fbccf5ebb3d49e6deba117af543554b/R/folder-dataset.R) that transformation does eventually occur in `.getitem` of `folder_dataset` which makes sense to me. 

I think it may also be slightly unclear what exactly `num_workers` is parallelizing over. My guess is that each time $iter()$.next() is called on a dataloader object, each element of $iter() gets .getitem called on it in its own subprocess (assuming num_workers > the batchsize of dataloader, and otherwise elements are queued). Is that correct?

**Comment by dfalbel** [comment]
Hi @myoung3 ,

The documentation now includes a brief description of how the parallelization happens within datalaoders: 
https://torch.mlverse.org/docs/dev/reference/dataloader.html#parallel-data-loading
