### ISSUE TITLE
torch_arange end is not included

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#472]
library(torch)
torch_arange(start = 1, end = 5)
#> torch_tensor
#>  1
#>  2
#>  3
#>  4
#> [ CPUFloatType{4} ]

**Comment by skeydan** [comment]
@dfalbel should I create a PR for this? Probably we just want to add `+ 1` here:

https://github.com/mlverse/torch/blob/0555381cc1ff3fcbb76f36329811124daf18c920/R/creation-ops.R#L253

?

(I guess we'll need to change some units tests as well)

**Comment by dfalbel** [comment]
sure! we should also update all current occurrences of `torch_arange` in the code base. Probably also look into the other packages eg torchvision and tabnet.

**Comment by skeydan** [comment]
https://github.com/mlverse/torch/pull/506 (needs further action)

**Comment by dfalbel** [comment]
Fixed in #506
