### ISSUE TITLE
Torch Does Not Find My GPU On Windows 10

### ISSUE THREAD

**Issue by drag05** [mlverse/torch#475]
I have just installed `torch` to run the vignettes. I've had already `cudatools` and `cudnn` installed and in working condition for `keras` and `tensorflow-gpu` on R.

I run on:

GPU: Nvidia GeForce RTX 2080 with Max-Q Design
CPU: Intel I9
R version 4.0.3

Here are the excerpts from `conda` list:

```
   (tensorflow) C:\Windows\system32>conda list
# packages in environment at C:\  \.conda\envs\tensorflow:    

# Name                    Version                   Build  
cudatoolkit               10.1.243               h74a9793_0
cudnn                        7.6.5               cuda10.1_0
.
python                       3.7.9               h60c2a47_0
```
And this is the result so far:

```
> require(torch)
Loading required package: torch
> torch::install_torch()
> torch::cuda_is_available()
[1] FALSE
```
I have created a new Environment variable but have gotten similar result:

```
CUDATOOLS_HOME = C:\Users\  \.conda\envs\tensorflow
```
Please advise, thank you!

**Comment by dfalbel** [comment]
Hi! 

Torch isn't able to find the cuda toolkit and cudnn versions installed in a conda environment.
You need to have a system installation of both libraries.

Links for the installation guides are available here: https://torch.mlverse.org/docs/articles/installation.html#gpu-2

**Comment by drag05** [comment]
@dfalbel 
Thank you for your time and for the link! Is there any chance that `torch` will be able to find `cuda`  installations on `conda` any time soon? I try to avoid duplicate installations.

**Comment by dfalbel** [comment]
I haven't tried, but perhaps if you can point the `CUDA_PATH`env var to the location of the CUDA binaries in the conda environment you might be able to use the conda installation.

**Comment by drag05** [comment]
- Renamed the above Env. variable as CUDA_PATH keeping the same path as above and getting the same result as above.
 - Extended path in Env. variable CUDA_PATH to `C:\Users\   \.conda\envs\tensorflow\Library\bin` getting the same result as above.
 
I have rebooted each time before checking.
