### ISSUE TITLE
Add Torch / TabNet as Modeltime Forecasting Package Backend

### ISSUE THREAD

**Issue by mdancho84** [mlverse/torch#482]
I'm in the process of developing a Learning Lab where I will be using Torch TabNet as a backend for forecasting using [modeltime](https://business-science.github.io/modeltime/). 

## Requested Website Edits

![image](https://user-images.githubusercontent.com/13734662/108861604-68a75e80-75bd-11eb-841d-6526e7215b51.png)

## How Modeltime Works

Any `tidymodels` compliant regression model can become a forecaster using the `modeltime` forecasting workflow and api. The `tabnet` package is a perfect example of how we can gain the benefits of Torch inside of a forecasting framework. We can also do LSTM provided a tidymodels model is made. 

![image](https://user-images.githubusercontent.com/13734662/108861649-765ce400-75bd-11eb-8773-f08e2d5d6aaa.png)

**Comment by dfalbel** [comment]
Hi @mdancho84 !

Very nice!  It will be really nice to see tabnet used together with modeltime.
Do you want to file a PR with the requested changes? 

The website is in the blogdown branch and you will probably want to change that file: https://github.com/mlverse/torch/blob/blogdown/content/packages/index.md

**Comment by mdancho84** [comment]
Yes - I can do that. Looking forward to showing off tabnet for time series.

**Comment by dfalbel** [comment]
@mdancho84 closing this issue. I added a reference to modeltime in https://github.com/mlverse/torch/commit/3f5d970eb07277dea922720a44b173203b656b09

**Comment by mdancho84** [comment]
Awesome! Much appreciated. The students loved the Learning Lab we did with it. We made some great forecasts using Tabnet on the M5 Forecasting Competition data.
