### ISSUE TITLE
torch.nan_to_num

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#493]
Hi,

I have a tensor with zeros that I would like to use as a denominator in a division. This produces inf values. I would like to make all inf values zero.  

torch.nan_to_num is a good solution in pytorch. Is there anything like that in R torch. If not, could we have such a function in R?

**Comment by dfalbel** [comment]
We currently don't have a `nan_to_num` function. You could do something like this though:

``` r
library(torch)
x <- torch_tensor(c(1,2,3,0/0))
x[torch_isnan(x)] <- 99
x
#> torch_tensor
#>   1
#>   2
#>   3
#>  99
#> [ CPUFloatType{4} ]
```

<sup>Created on 2021-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dominikj2** [comment]
Yes, thank you. Came to that solution. Probably not necessary for a pytorch replica.
