### ISSUE TITLE
Install Information About GPU Seems to be Out of Date

### ISSUE THREAD

**Issue by jaredlander** [mlverse/torch#504]
The [install vignette](https://cran.r-project.org/web/packages/torch/vignettes/installation.html) says that CUDA 11 is not supported. But that seems contradicted by ``names(torch:::install_config$`1.7.1`)`` which returns

```r
[1] "cpu"  "10.1" "10.2" "9.2"  "11.0"
```

Further evidence is that I installed it with 11.0 and it is working.

**Comment by dfalbel** [comment]
Thanks @jaredlander ! Will update!

**Comment by dfalbel** [comment]
Oh actually I already updated but still doesn't appear on the pkgdown website or vignettes because it's still unreleased.

https://github.com/mlverse/torch/blob/master/vignettes/installation.Rmd#L82
