### ISSUE TITLE
loading a model trained in Python with a GPU to R

### ISSUE THREAD

**Issue by mikeyEcology** [mlverse/torch#507]
Hi, Thank you for creating torch for R! 
I trained a model in pytorch with a GPU and now I want to load it into R. I am using this to load the model:
```
state_dict <- torch::load_state_dict("./model.pt")
```

I receive this error:

> Error in cpp_load_state_dict(path) : 
  Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. 'aten::empty_strided' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
CPU: registered at aten\src\ATen\CPUType.cpp:2127 [kernel]
BackendSelect: registered at aten\src\ATen\BackendSelectRegister.cpp:761 [kernel]
Named: registered at ..\..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:7974 [autograd kernel]
AutogradCPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:7974 [autograd kernel]
AutogradCUDA: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:7974 [autograd kernel]
AutogradXLA: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:7974 [autograd kernel]
AutogradPrivate

I can successfully train a model in pytorch and load it in R using `load_state_dict`, but not if I train the model using a GPU. Do you have any suggestions?
Thank you in advance. 

UPDATE: If I train a model with the same architecture in pytorch, but don't use a GPU, I can load it into R with `torch::load_state_dict` and I do not get an error.

**Comment by dfalbel** [comment]
This looks like a bug. I'll investigate.

One possible workaround in your case would be to move the python model to the cpu before serializing and then everything should work as expected. You could do something like `model.to(device='cpu')` in python before saving the state dict.

**Comment by mikeyEcology** [comment]
Thank you @dfalbel! I'll use that workaround for now.

**Comment by dfalbel** [comment]
I investigated this issue today and it looks like it's a LibTorch issue that has been fixed in the 1.8 release.
We shouldn't need to do anything to fix it in the R package once we update to libtorch v1.8

**Comment by dfalbel** [comment]
To reproduce the problem with libtorch 1.7 just use something like: 

```
#include <torch/torch.h>
#include <iostream>

int main() {
    std::ifstream file("/Users/dfalbel/Documents/cudatensor/cuda.pt", std::ios::binary);
    std::vector<char> data((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    torch::IValue ivalue = torch::pickle_load(data); 
}
```

**Comment by mikeyEcology** [comment]
Great! Thank you @dfalbel
