### ISSUE TITLE
madgrad

### ISSUE THREAD

**Issue by kevinykuo** [mlverse/torch#510]
should cool new optimizers live in this package?

https://github.com/facebookresearch/madgrad
https://github.com/facebookresearch/madgrad/blob/master/madgrad/madgrad.py

**Comment by dfalbel** [comment]
Both are fine for me.

I'd say it's probably easier to implement in different packages for faster release cycle and etc. But we currently don't export a `optim` function in the same sense that `dataset` and `nn_module` that allows for package developers to implement other optimizers. I make this higher priority to implement this faster if you are interested in creating a new package..

**Comment by dfalbel** [comment]
Quick implementation here: https://github.com/mlverse/madgrad
