### ISSUE TITLE
latern binary 404 for linux

### ISSUE THREAD

**Issue by kevinykuo** [mlverse/torch#519]
current master

```
r$> library(torch)                                                   
trying URL 'https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.8.0%2Bcu101.zip'
Content type 'application/zip' length 830828045 bytes (792.3 MB)
==================================================
downloaded 792.3 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/libtorch-v1.8/latest/Linux-gpu-101.zip'
Warning messages:
1: In utils::download.file(library_url, temp_file) :
  cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/libtorch-v1.8/latest/Linux-gpu-101.zip': HTTP status was '404 Not Found'
2: Failed to install Torch, manually run install_torch(). cannot open URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/libtorch-v1.8/latest/Linux-gpu-101.zip' 
```

**Comment by kevinykuo** [comment]
oh i guess 101 isn't in the build matrix https://github.com/mlverse/torch/blob/f7aa1cd875b211369809cb9da9fdece16230ae9a/.github/workflows/lantern.yaml#L199

fwiw i'm running cuda 11.2 and the install worked out of the box before we bumped to libtorch 1.8

**Comment by kevinykuo** [comment]
okay i lied about my cuda version, TIL `nvidia-smi` and `nvcc` can give different numbers

**Comment by dfalbel** [comment]
Unfortunately the pytorch team is no longer providing LibTorch build for CUDA 10.1.
And yeah, `nvidia-smi` actually reports the latest supported CUDA version and not the actual installed version 🤦 
Anyway, it seems like the error message should be more clear, and state that CUDA 10.1 is not supported.

**Comment by dfalbel** [comment]
Actually it looks like the provide LibTorch builds for 10.1 but don't advertise in the website. I can probably recover it and provide lantern builds then
