### ISSUE TITLE
JIT tracing functions with multiple parameters

### ISSUE THREAD

**Issue by kevinykuo** [mlverse/torch#529]
Currently we can't trace functions with multiple parameters, e.g., something like

```
fn1 <- function(x, y) {
    x + y
}
```
The issue I think stems from https://github.com/mlverse/torch/blob/88700be25bc0b1d7747d3a950570595922d11fef/tests/testthat/test-trace.R#L105-L115 where we support functions that take a list, which requires push the tensor list to the stack in one go here https://github.com/mlverse/torch/blob/88700be25bc0b1d7747d3a950570595922d11fef/R/trace.R#L57-L62

While the user could rewrite the function `fn1` to take a list, it's a bit unnatural especially in more complex examples. Also, some deployment targets (RedisAI for one) expect tensors and not lists thereof, so they would be blocked. Finally, the PyTorch example follows the pattern of treating `example_inputs` as an arg list (https://pytorch.org/docs/stable/generated/torch.jit.trace.html)

```
import torch

def foo(x, y):
    return 2 * x + y

# Run `foo` with the provided inputs and record the tensor operations
traced_foo = torch.jit.trace(foo, (torch.rand(3), torch.rand(3)))
```

Could we consider modifying the behavior of `jit_trace()` so we treat `example_inputs` as an arg list?

**Comment by dfalbel** [comment]
Oh yes, this makes perfect sense for me. Will do it when I come back to work on the JIT.
