### ISSUE TITLE
Installation Fails in R 4.0.5 with CUDA 11.1

### ISSUE THREAD

**Issue by magicianofriga** [mlverse/torch#536]
Hi,
I have spent hours trying to install torch on R. However, everything seems to fail. I have CUDA 11.1 (the guides I read said this is best), CUDNN 8.0.5. I have a strong GPU - RTX 2070 Super. I tried the following commands and I get the following error:

```
Sys.setenv(CUDA="11.1")
devtools::install_github("mlverse/torch")
library(torch)

trying URL 'https://download.pytorch.org/libtorch/cu111/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcu111.zip'
Content type 'application/zip' length 2077761397 bytes (1981.5 MB)
==================================================
downloaded 1981.5 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.3.0/latest/Linux-gpu-111.zip'
Content type 'application/zip' length 1707620 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

Failed to install Torch, manually run install_torch().
 /home/dell/R/x86_64-pc-linux-gnu-library/4.0/torch/deps/liblantern.so - libnvToolsExt.so.1: cannot open shared object file: No such file or directory
```

Also, during installation, I got the following: 

```
In file included from device.cpp:1:
lantern/lantern.h: In function ‘bool lanternInit(const string&, std::string*)’:
lantern/lantern.h:5765:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
 5765 | bool lanternInit(const std::string &libPath, std::string *pError)
      |      ^~~~~~~~~~~
```

Can someone please help me? I would love to use it for my work.

Also, when I run the installer without setting the environment, it doesn't detect that I have CUDA installed. What is the fix here?

**Comment by dfalbel** [comment]
This error usually means that you don't have the right cuda toolkit version or it's installation is not in the path. [Here's](https://forums.developer.nvidia.com/t/how-can-i-install-the-pytorch/108038/2?u=dfalbel) a link showing how to put it on the path.

A common pitfall is that `nvidia-smi` might be reporting the wrong version of the cuda toolkit.... It actually reports the last version the driver supports but not necessarily the on you have installed.

Can you check that you have the correct cuda version and that it's correctly on the path?

The warning you got during installation can be safely ignored.

**Comment by magicianofriga** [comment]
Hi,
Regarding the toolkit, I can confirm that I have the correct one - Cuda 11.1 with CUDNN 8.0.5. 
However, there is something strange happening.
When I try to use nvcc --version, it says it's not found, but I find two CUDA folders inside my usr/local/lib folder. I don't know what is causing it.
The way I installed CUDA is that I downloaded a .sh file from NVIDIA and ran it. For CUDNN I ran a .deb file.
What can I do to solve this?

**Comment by dfalbel** [comment]
I think you have to add it to the path with something like this:

```
$ export PATH=/usr/local/cuda-11.3/bin${PATH:+:${PATH}}
$ export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

See item 6 here: https://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html#ubuntu-x86_64-run

**Comment by magicianofriga** [comment]
Hi,
Does the library support CUDA 11.3? I spent hours uninstalling CUDA 11.3 so that I can use 11.1.

**Comment by dfalbel** [comment]
Oh, no, I'm sorry, I linked to the wrong docs. We do not support 11.1 as LibTorch is not yet compatible with it...

But the task should be the same, it's about getting the right version to the path. In the example it should work by just replacing `cuda-11.3` for `cuda-11.1`.

**Comment by magicianofriga** [comment]
> Oh, no, I'm sorry, I linked to the wrong docs. We do not support 11.1 as LibTorch is not yet compatible with it...
> 
> But the task should be the same, it's about getting the right version to the path. In the example it should work by just replacing `cuda-11.3` for `cuda-11.1`.

Hi,
Thanks to adding it to the path, it finally worked! I think I will close this issue now. 
I will stick to CUDA 11.1 as it is the one that works here. Also, if possible, please edit your comment to say it doesn't support 11.3, as it worked for me on 11.1.
Thanks for your wonderful support! I should have asked here first instead of wasting 8 hours trying to make something work!
Take care and stay safe!

**Comment by dfalbel** [comment]
Great @magicianofriga ! Glad it worked now ! Installing the NVIDIA libraries are usually frustrating tasks. Please, do open issues whenever you have problems :)

Best,
Daniel

**Comment by magicianofriga** [comment]
Hi, I won't reopen the issue, but just asking - does torch support CUDA 11.3 now?

**Comment by skeydan** [comment]
Hi, we will be upgrading to libtorch 1.9 soon -  see https://github.com/mlverse/torch/issues/592 - but it seems like officially, they still only support 11.1: https://pytorch.org/ ...

Personally, I had been using libtorch 1.8 (and older) with 11.2 for a long time, never encountering problems, but unfortunately, with 11.3 I've started to run into occasional segfaults ... This may be architecture-dependent (happens for RNNs, I think, mostly), but overall I can't recommend using ` torch` with 11.3 until they officially support it.
