### ISSUE TITLE
`jit_trace` strips names from lists of tensors

### ISSUE THREAD

**Issue by rdinnager** [mlverse/torch#537]
I've been playing around with `jit_trace` for a package I'm working on. So far it is looking very useful but I ran into an issue when the function to be traced takes a named list of tensors and then uses the names inside the function. I was getting an esoteric error about `NULL` pointers. After a fair amount of debugging work I figured out the names are no longer accessible inside the function when using `jit_trace`. Here is a reprex, where I modify the example from your tests mentioned in #529:

``` r
library(torch)
#> Warning: package 'torch' was built under R version 4.0.3
```

This code works but the output has the name “res” stripped. Additionally we get a warning to be careful about returning a list in a traced function (see below).

``` r
fn <- function(x) { 
  list(res = torch_stack(list(x[[1]], x[[2]])))
} 
x <- list(t1 = torch_tensor(1), t2 = torch_tensor(2)) 

tr_fn <- jit_trace(fn, x)

tr_fn(x)
#> [[1]]
#> torch_tensor
#>  1
#>  2
#> [ CPUFloatType{2,1} ]
```

Running this version doesn’t work because names get stripped. This gives an esoteric error about an external pointer, but getting a `NULL` instead. Printing the names of the input shows that the names are now `NULL`.

``` r
fn <- function(x) {
  print(names(x))
  list(res = torch_stack(list(x$t1, x$t2)))
} 
x <- list(t1 = torch_tensor(1), t2 = torch_tensor(2)) 

tr_fn <- jit_trace(fn, x) 
#> NULL
#> Error in cpp_trace_function(tr_fn, ex_inp$ptr, .compilation_unit): Evaluation error: Expecting an external pointer: [type=NULL]..
```

The function itself works as expected:

``` r
fn(x)
#> [1] "t1" "t2"
#> $res
#> torch_tensor
#>  1
#>  2
#> [ CPUFloatType{2,1} ]
```

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">

<summary>Standard output and standard error</summary>

``` sh
[W ..\..\torch\csrc\jit\frontend\tracer.cpp:928] Warning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior. (function defaultWarn)
```

</details>

This issue is fairly easy to workaround in most cases, but it is slightly annoying to not be able to refer to names.

**Comment by dfalbel** [comment]
Hi @rdinnager 

Thanks for the detail report! This is indeed not expected.  I am planning to work on the JIT soon and I'll make sure we fix this.

Regarding the warning message: this one is little more tricky. It's raised in the c++ side but it's really targeting PyTorch (python package) where there are differences between tuples and lists and named tuples and named dicts. We will ultimately need to silent it, even though it can be dangerous because tracing don't support variable sized list outputs.

**Comment by dfalbel** [comment]
This should work once #593 is merged. 
Note though that named outputs don't keep their names as this seems to be a limitation in PyTorch's implementation.
See: https://discuss.pytorch.org/t/retrieve-names-of-namedtuple-output/125405

One can still return named dictionaries, but then `strict=FALSE` is necessary as argument to `jit_trace`.
