### ISSUE TITLE
nn_multihead_attention throws error

### ISSUE THREAD

**Issue by jonathanbratt** [mlverse/torch#539]
when I try `nn_multihead_attention` as directed in the examples, I get an error.

```
> library(torch)
> embed_dim <- 16L
> num_heads <- 4L
> multihead_attn <- nn_multihead_attention(embed_dim = embed_dim, num_heads = num_heads)
## Error in if (self$qkv_same_embed_dim) { : argument is of length zero
```

The error appears to be coming from this line:
https://github.com/mlverse/torch/blob/d5cecbf342c857a0fbe9a5a29a09daf1441a706f/R/nn-activation.R#L789

**Comment by jonathanbratt** [comment]
I believe that this was fixed in yesterday's release! :)

**Comment by dfalbel** [comment]
Alright! Cool! There might still be some issues see #497
