### ISSUE TITLE
in nnf_multi_head_attention_forward, return attention weights for each head

### ISSUE THREAD

**Issue by jonathanbratt** [mlverse/torch#542]
Currently, the function averages the attention weights over all the heads before returning:
https://github.com/mlverse/torch/blob/d5cecbf342c857a0fbe9a5a29a09daf1441a706f/R/nnf-activation.R#L733

I'm not sure when it would be useful to have the average, but that's clearly the intended behavior. This function would be more useful to me if it returned the un-averaged weights, i.e.:

`  return(list(attn_output, attn_output_weights)) `
rather than
`  return(list(attn_output, attn_output_weights$sum(dim = 2)/num_heads)) `

Is there any reason *not* to make this change?

I see there's a discussion in pytorch about this, also:
https://github.com/pytorch/pytorch/issues/47583

I suppose there's a desire to keep torch as parallel to pytorch as possible. What's the policy about making changes in torch before they're made in pytorch?

**Comment by dfalbel** [comment]
We don't have a strict policy for that yet. We try to keep as parallel as possible, but I'm ok with having an option that avoids averaging as long as we keep the default similar to PyTorch's.

The other solution would be to re-implement multihead attention like what was done in torchtext here: https://github.com/pytorch/text/blob/9ebfb7b746999cff8df562704e5366a902df759f/torchtext/nn/modules/multiheadattention.py#L191-L198 but that sounds unreasonable considering the current size of R's torch community.
