### ISSUE TITLE
[v0.3.0] Liblatern failed to find libnvToolsExt 

### ISSUE THREAD

**Issue by dg520** [mlverse/torch#551]
Hi,

Thanks for developing and maintaining torch for R. Really enjoy it so far on v0.2.1. I encountered a problem when tried to update to v0.3.0. This problem is similar to #298 .
I first updated my cuda-toolkit-11-1 and cuDNN8. The updated CUDA sits at `/usr/local/cuda`. 
I started with a fresh Rstudio console and installed v0.3.0 as following:
```
> Sys.setenv(CUDA_HOME="/usr/local/cuda/")
> Sys.setenv(PATH=paste0("/usr/local/cuda/bin:",Sys.getenv("PATH")))
> Sys.setenv(LD_LIBRARY_PATH=paste0("/usr/local/cuda/lib64:",Sys.getenv("LD_LIBRARY_PATH")))
> install.packages("torch")
```
The installation was said to be successful, except I saw the following error/warning in the middle of compiling 
```
In file included from device.cpp:1:
lantern/lantern.h: In function ‘bool lanternInit(const string&, std::string*)’:
lantern/lantern.h:5765:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
 5765 | bool lanternInit(const std::string &libPath, std::string *pError)
      |      ^~~~~~~~~~~
```

When I loaded `torch`, it tried to installed `libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcu111` and `latern`. But the latter failed with the following message:
```
Warning message:
Failed to install Torch, manually run install_torch().
 /home/dadi/R/x86_64-pc-linux-gnu-library/4.0/torch/deps/liblantern.so - libnvToolsExt.so.1: cannot open shared object file: No such file or directory
```
I'm not sure which directory `liblantern` looks for `libnvToolsExt.so.1`. This file does exist in /usr/local/cuda/lib64, which I have included in the first place of `LD_LIBRARY_PATH` in R system environment. Please see the evidence below:
```
$ ls -ll /usr/local/cuda/lib64/libnvToolsExt*

lrwxrwxrwx 1 root root    18 Sep 16  2020 /usr/local/cuda/lib64/libnvToolsExt.so -> libnvToolsExt.so.1
lrwxrwxrwx 1 root root    22 Sep 16  2020 /usr/local/cuda/lib64/libnvToolsExt.so.1 -> libnvToolsExt.so.1.0.0
-rw-r--r-- 1 root root 36832 Sep 16  2020 /usr/local/cuda/lib64/libnvToolsExt.so.1.0.0
```

Any advice will be highly appreciated!

**Comment by dfalbel** [comment]
Hi @dg520 ! 

Thanks for the detailed report! I'll try to reproduce this later today. 
One thing you could try is setting `LD_LIBRARY_PATH` env var from outside R, for example something like:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
R
```

As changing from inside the R process might not be having any effect(?)

**Comment by dg520** [comment]
@dfalbel Thanks for such a quick reply! I did export the `LD_LIBRARY_PATH` variable in the Linux environment as well, per your and Nvidia's suggestion. That didn't help unfortunately.

**Comment by dfalbel** [comment]
FWIW in a docker img: https://github.com/mlverse/torch/blob/master/docker/cuda-111 (which is basically CUDA, CUdnn and R installed)
The shared object seems to be loaded from: `/usr/local/cuda-11.1/targets/x86_64-linux/lib/libnvToolsExt.so.1.0.0`
Maybe the symlink exists but the actual file is not actually there?
See below part of the output of `lsof -p <pid>`

```
R       1294 root  mem       REG                8,2 21074296 24391274 /usr/lib/x86_64-linux-gnu/libcuda.so.455.32.00
R       1294 root  mem       REG                8,2          11408575 /usr/local/lib/R/site-library/torch/deps/libnvToolsExt-24de1d56.so.1 (path dev=0,166)
R       1294 root  mem       REG                8,2          11408558 /usr/local/lib/R/site-library/torch/deps/libcudart-6d56b25a.so.11.0 (path dev=0,166)
R       1294 root  mem       REG                8,2          11408567 /usr/local/lib/R/site-library/torch/deps/libgomp-75eea7e8.so.1 (path dev=0,166)
R       1294 root  mem       REG                8,2          23739732 /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1.74 (path dev=0,166)
R       1294 root  mem       REG                8,2          23743292 /usr/local/cuda-11.1/targets/x86_64-linux/lib/libnvToolsExt.so.1.0.0 (path dev=0,166)
R       1294 root  mem       REG                8,2          11408591 /usr/local/lib/R/site-library/torch/deps/libtorch.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408594 /usr/local/lib/R/site-library/torch/deps/libtorch_cuda_cpp.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408592 /usr/local/lib/R/site-library/torch/deps/libtorch_cpu.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408595 /usr/local/lib/R/site-library/torch/deps/libtorch_cuda_cu.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408593 /usr/local/lib/R/site-library/torch/deps/libtorch_cuda.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408547 /usr/local/lib/R/site-library/torch/deps/libc10_cuda.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408546 /usr/local/lib/R/site-library/torch/deps/libc10.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11408601 /usr/local/lib/R/site-library/torch/deps/liblantern.so (path dev=0,166)
R       1294 root  mem       REG                8,2          11407648 /usr/local/lib/R/site-library/torch/libs/torchpkg.so (path dev=0,166)```

I was not able to reproduce the problem in both my local setup and in docker images.

**Comment by dg520** [comment]
@dfalbel I see now lantern looks for `/usr/local/cuda/targets/x86_64-linux/lib/`. In that folder, I do have `libnvToolsExt.so.1.0.0` and `libcudart.so`. See below:
```
$ ls -ll /usr/local/cuda/targets/x86_64-linux/lib/libnvToolsExt.so*
lrwxrwxrwx 1 root root    18 Sep 16  2020 /usr/local/cuda/targets/x86_64-linux/lib/libnvToolsExt.so -> libnvToolsExt.so.1
lrwxrwxrwx 1 root root    22 Sep 16  2020 /usr/local/cuda/targets/x86_64-linux/lib/libnvToolsExt.so.1 -> libnvToolsExt.so.1.0.0
-rw-r--r-- 1 root root 36832 Sep 16  2020 /usr/local/cuda/targets/x86_64-linux/lib/libnvToolsExt.so.1.0.0

$ ls -lh /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so*
lrwxrwxrwx 1 root root   17 May  6 00:24 /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so -> libcudart.so.11.0
lrwxrwxrwx 1 root root   20 Sep 16  2020 /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 -> libcudart.so.11.1.74
-rw-r--r-- 1 root root 528K Sep 16  2020 /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.1.74
```
However, there is no symlink files of `libnvToolsExt.so.1` and `libcudart.so.11.0` in the torch package folder (i.e. `torch/deps/`). 
I mannually created these two symlinks in `torch/deps/`, pointing to the corresponding files in `/usr/local/cuda/targets/x86_64-linux/lib/`. 
```
cd ~/R/x86_64-pc-linux-gnu-library/4.0/torch/deps
ln -s /usr/local/cuda/targets/x86_64-linux/lib/libnvToolsExt.so.1 libnvToolsExt.so.1
ln -s /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 libcudart.so.11.0
```
This made torch load successfully. 

My questions become: 
1. Did I link the files in the correct way?
2. For my curiosity, why did `lantern` fail to build the links in v0.3.0, while it was successful in v0.2.1? Are they two different versions of `lantern` and have changed their installation behaviors? 

Thanks!

**Comment by dfalbel** [comment]
GLad you managed to make it work now.

To be honest I have no idea why this happens and I could not reproduce locally. Maybe, an old installation could block the creation of the new correct symlink? 

In theory there should be no need to manually create the symlinks, but the ones you created seems correct to me.

I don't think there was any related change in lantern both in packaging terms and code that could have affected this.

I'll try again to reproduce this in the next few days so we can understand the 'real' cause.

**Comment by dg520** [comment]
@dfalbel Ah! It turned out to be my fault. 

I only set `export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$PATH` on the node that does NOT hold Rstudio-server. After exporting LD_LIBRARY_PATH on the Rstudio-server node, `install_torch` completed successfully as expected.

I'm really sorry for my own mistake to cause confusion and I'll close this issue.
