### ISSUE TITLE
Xavier initialization

### ISSUE THREAD

**Issue by duct317** [mlverse/torch#555]
Hi,
In `nn_init_xavier_uniform_ ` and `nn_init_xavier_normal_ ` functions, the line `std <- gain * sqrt(2.0 / fan_in + fan_out)` is missing the brackets. It should be `std <- gain * sqrt(2.0 / (fan_in + fan_out))`.

**Comment by dfalbel** [comment]
Oh wow, thanks for reporting. Sorry about that. Will fix ASAP.
