### ISSUE TITLE
is tensor$tolist() implemented?

### ISSUE THREAD

**Issue by egillax** [mlverse/torch#603]
In the documentation [here](https://torch.mlverse.org/docs/articles/tensor/index.html) it says you can convert a tensor to a list with tensor$tolist(). But in my case it doesn't work:

```R
tensor <- torch::torch_rand(10)
myList <- tensor$tolist()
```

gives me the error:
```Error: attempt to apply non-function```

Am I using it wrong or isn't it implemented as it says in the docs?

**Comment by dfalbel** [comment]
The documentation is wrong and this method is not implemented.
Currently the recommended way to convert a Tensor to an R object is using `as.array()`.

**Comment by egillax** [comment]
Thanks that did the trick.
