### ISSUE TITLE
Operations on high dimensional arrays

### ISSUE THREAD

**Issue by grantmcdermott** [mlverse/torch#605]
I feel I must be missing something obvious here, but couldn't find a definitive answer in the docs.

Say I want to perform some operation on a higher (3+) order array. In base R, this is typically done via `apply.` For example,

``` r
(A = array(c(5,1,1,3), dim = c(2,2,2)))
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    5    1
#> [2,]    1    3
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]    5    1
#> [2,]    1    3

## One element example: Cholesky decomposition
chol(A[,,1])
#>          [,1]      [,2]
#> [1,] 2.236068 0.4472136
#> [2,] 0.000000 1.6733201

## Apply across all elements in the 3rd dimension
apply(A, 3, chol)
#>           [,1]      [,2]
#> [1,] 2.2360680 2.2360680
#> [2,] 0.0000000 0.0000000
#> [3,] 0.4472136 0.4472136
#> [4,] 1.6733201 1.6733201
```
Now, I convert to a Torch array and try the equivalent operation.

``` r
library(torch)

(At = torch_tensor(A))
#> torch_tensor
#> (1,.,.) = 
#>   5  5
#>   1  1
#> 
#> (2,.,.) = 
#>   1  1
#>   3  3
#> [ CPUFloatType{2,2,2} ]

## Single element works as (both encapsulated and functional methods)
At[,,1]$cholesky(upper = TRUE)
#> torch_tensor
#>  2.2361  0.4472
#>  0.0000  1.6733
#> [ CPUFloatType{2,2} ]
torch_cholesky(At[,,1], upper = TRUE)
#> torch_tensor
#>  2.2361  0.4472
#>  0.0000  1.6733
#> [ CPUFloatType{2,2} ]

## Vectorised(?) across the whole array doesn't work
At$cholesky()
#> Error in (function (self, upper) : cholesky_cpu: For batch 1: U(2,2) is zero, singular U.
#> Exception raised from batchCheckErrors at ../aten/src/ATen/native/LinearAlgebraUtils.h:105 (most recent call first):
#> <... truncated error message ...>

## Fair enough, though apply + encapsulation doesn't work either
apply(At, 3, function(m) m$cholesky(upper = TRUE))
#> Error in m$cholesky: $ operator is invalid for atomic vectors

## The functional equivalent does
apply(At, 3, function(m) torch_cholesky(m, upper = TRUE))
#> [[1]]
#> torch_tensor
#>  2.2361  0.4472
#>  0.0000  1.6733
#> [ CPUFloatType{2,2} ]
#> 
#> [[2]]
#> torch_tensor
#>  2.2361  0.4472
#>  0.0000  1.6733
#> [ CPUFloatType{2,2} ]
```
I was (naively) hoping a "vectorised" solution might work out the box. However, it's nice to know that the `apply` + function approach carries over to tensor objects, even if the encapsulated methods don't.

Still, this presents a bit of a headache AFAICT when working with tensor arrays on a GPU. (Is there a functional way to convert to "cpu"? I apologise if I missed it.)

```r
## GPU
(Atg = torch_tensor(A, device = 'cuda'))
#> torch_tensor
#> (1,.,.) = 
#>   5  5
#>   1  1
#> 
#> (2,.,.) = 
#>   1  1
#>   3  3
#> [ CUDAFloatType{2,2,2} ]

## No dice for either approach
apply(Atg, 3, function(m) torch_cholesky(m, upper = TRUE))
#> Error: Can't convert cuda tensor to R. Convert to cpu tensor before.

apply(Atg, 3, function(m) torch_cholesky(m, upper = TRUE)$cpu())
#> Error: Can't convert cuda tensor to R. Convert to cpu tensor before.
```

A final approach that I tried is to combine the individual array matrices into a block diagonal matrix. This does work out of the tin, but now we're creating a sparse matrix that is sub-optimal from a memory perspective.

```r
## Block version
Ablock = torch_block_diag(list(A[,,1], A[,,2]))
Ablock$cholesky(upper = TRUE)
#> torch_tensor
#>  2.2361  0.4472  0.0000  0.0000
#>  0.0000  1.6733  0.0000  0.0000
#>  0.0000  0.0000  2.2361  0.4472
#>  0.0000  0.0000  0.0000  1.6733
#> [ CPUFloatType{4,4} ]
```

<sup>Created on 2021-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Any pointers to the optimal way for performing operations on high(er) dimensional torch arrays would be much appreciated.

P.S Thanks for this fantastic package!

**Comment by dfalbel** [comment]
Hey @grantmcdermott 

Thanks for opening the issue! It's interesting that `apply` works, but I think it calls `as.array()` before the `apply` loop, so it wouldn't take too much benefit of torch's implementations.

I think I would do something like this:

``` r
library(torch)

A = array(c(5,1,1,3), dim = c(2,2,2))
At = torch_tensor(A)

At %>% 
  torch_unbind(dim = 3) %>% 
  lapply(function(m) m$cholesky(upper = TRUE)) %>% 
  torch_stack(dim = 3)
#> torch_tensor
#> (1,.,.) = 
#>   2.2361  2.2361
#>   0.4472  0.4472
#> 
#> (2,.,.) = 
#>   0.0000  0.0000
#>   1.6733  1.6733
#> [ CPUFloatType{2,2,2} ]
```

Also, many mathematical function can be applied into selected dimensions (using the `dim` argument) eg. `torch_sum(At, dim = c(1,2))` is equivalent to `apply(A, MARGIN = 3, sum)`.

**Comment by grantmcdermott** [comment]
Ah, very helpful. 

For my IRL application I have a bespoke function, so the lapply approach should carry over nicely. It would be extra nice to invoke parallelism across the GPU (some kind of equivalent to mclapply?), but I think this should get me within reach of where I want to go.

Thanks Daniel!
