### ISSUE TITLE
Rstudio on EC2 instance crashes when torch is called

### ISSUE THREAD

**Issue by G3Jram** [mlverse/torch#606]
Hi,

Im trying to implement tabnet in rstudio on an EC2 instance. When tabnet fit is called ,it crashes my rstudio session. 

The problem seems to be with underlying torch installation.

Any help to resolve this will be much appreciated. 

Thanks.

**Comment by dfalbel** [comment]
How are you installing torch in this instance?
By default, we don't automatically the underlying libs in non-interactive environments.

Have you set `TORCH_INSTALL` env var to 1, so it’s automatically installed or manually call `torch::install_torch()`.

**Comment by G3Jram** [comment]
If i do torch::install_torch(), i get an error saying, "Error in cpp_lantern_init(install_path()).

Please note im running it on an EC2 instance.

**Comment by dfalbel** [comment]
Can you copy and paste the full error message?

**Comment by kevinykuo** [comment]
off of a fresh install from master, EC2 running ubuntu focal

```
r$> library(torch)                                                                    
trying URL 'https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcpu.zip'
Content type 'application/zip' length 197368912 bytes (188.2 MB)
==================================================
downloaded 188.2 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/master/latest/Linux-cpu.zip'
Content type 'application/zip' length 1798171 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

Warning message:
Failed to install Torch, manually run install_torch().
 /home/ubuntu/R/x86_64-pc-linux-gnu-library/4.1/torch/deps/liblantern.so - /home/ubuntu/R/x86_64-pc-linux-gnu-library/4.1/torch/deps/liblantern.so: undefined symbol: _ZN2at11addcmul_outERNS_6TensorERKS0_S3_S3_N3c106ScalarE 

r$> install_torch()                                                                   
Error in cpp_lantern_init(install_path()) : 
  /home/ubuntu/R/x86_64-pc-linux-gnu-library/4.1/torch/deps/liblantern.so - /home/ubuntu/R/x86_64-pc-linux-gnu-library/4.1/torch/deps/liblantern.so: undefined symbol: _ZN2at11addcmul_outERNS_6TensorERKS0_S3_S3_N3c106ScalarE
```

**Comment by dfalbel** [comment]
@kevinykuo this is expected in the dev branch because I broke this: https://github.com/mlverse/torch/runs/3078747546?check_suite_focus=true

**Comment by kevinykuo** [comment]
@dfalbel ahh gotcha, OP may be hitting a different error then

**Comment by G3Jram** [comment]
> Can you copy and paste the full error message?

Version 'GLIBCXX_3.4.21' not found

**Comment by dfalbel** [comment]
What OS are you using? Can you try using a more recent OS, or installing a more recent version of  GCC?
