### ISSUE TITLE
Parallel dataloader fails when dataset contains tensors

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#625]
``` r
library(torch)
dt <- tensor_dataset(torch_randn(20, 1))
dl <- dataloader(dt, batch_size = 10, num_workers = 2)
coro::collect(dl)
#> Error: callr subprocess failed: external pointer is not valid
```

This fails because tensors are not correctly serialized before transfering to the worker subprocess. 
It would be nice to able to correctly serialize them, but at least we should raise a good error message.

**Comment by aosakwe** [comment]
Hello @dfalbel. I get the warning you have added when trying to use multiple workers during training. I looked through the vignettes to see if there is an example of how to properly implement the parallel dataloader but can only find examples where num_workers =0. Could you provide a short example which would allow for a non-zero input?

**Comment by aosakwe** [comment]
Hi @dfalbel I received this warning after setting up my dataLoader with a non_zero num_workers input. However, I cannot find any vignettes detailing how to properly implement this to avoid errors. Would you be able to provide a brief example of how to achieve this?
