### ISSUE TITLE
Enable anomaly detection for the autograd engine

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#627]
Hi.
 I encounter the RuntimeError: one of the variables needed for gradient computation has been modified by an in place operation while running backward().

```
Error in (function (self, inputs, gradient, retain_graph, create_graph)  : 
  one of the variables needed for gradient computation has been modified by an inplace operation:
[CUDALongType [4, 16, 24]] is at version 1; expected version 0 instead. Hint: enable anomaly detection 
to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
Python has a debugging feature `anomaly_detection` for "modified by an inplace operation" error. Does R have an equivalent?

Below links explain:

[https://pytorch.org/docs/stable/autograd.html#anomaly-detection](url)

[https://github.com/pytorch/pytorch/issues/15803](url)

[https://discuss.pytorch.org/t/encounter-the-runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/836/17]()

**Comment by dfalbel** [comment]
Hey @dominikj2 

I added that option with `with_detect_anomaly`. See the linked PR.
