### ISSUE TITLE
provide Lantern objects built with GPU support

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#63]
We currently only support cpu builds of lantern

**Comment by jwijffels** [comment]
I'm interested in trying this code https://github.com/DIGI-VUB/torch.ner/blob/master/dev/01-ner-bilstm-packed.R out on Google Colab with GPU. Do you think this will work already?

**Comment by dfalbel** [comment]
It won't work yet, because you will need a GPU build of lantern. We are working on it, see #74

**Comment by dfalbel** [comment]
@jwijffels We now have lantern binaries with GPU support. It seems to be working correctly on Google Colab, see: https://colab.research.google.com/drive/1L_cyz-hkAQCukGF0ASZq8gBr_6EJSPUo?usp=sharing

**Comment by jwijffels** [comment]
Thank you!
