### ISSUE TITLE
"gcc versions later than 10 are not supported" following #619

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#631]
Hi Daniel,

I get the following cuda compilation error since we've added custom cuda code:

```
[  2%] Building NVCC (Device) object CMakeFiles/lantern.dir/src/Contrib/SortVertices/lantern_generated_sort_vert_kernel.cu.o
In file included from /usr/include/cuda/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/cuda/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
```

Is this something we want to do something about? (I don't think gcc 11 is that rare; Fedora, for example, is at 11.4 already.)

Thanks!

Edit: tag #619

**Comment by dfalbel** [comment]
I don't think there's much we can do... Sooner or later we would want to use CUDA somewhere in torch codebase and we would hit this. You can still use a conda environment (or other package managers) to have a gcc <= 10 installation or have other versions of gcc installed in parallel.

**Comment by skeydan** [comment]
Not sure yet what's going on - need to look at why exactly this pops up - but reopening because according to https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html and the linked https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html, gcc 11 should be supported by nvcc 11.4 ... 

So this issue will at least serve for documentation purposes, whatever turns out to be a workaround/solution...

**Comment by skeydan** [comment]
Turns out that for whatever reason, when I force usage of gcc 11 (modifying `/usr/include/cuda/crt/host_config.h`), the lantern build in fact fails:

```
/home/key/libtorch/include/c10/core/TensorImpl.h(2179): error: static assertion failed with "You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed."
```

Workaround was a custom gcc 10.2 build.
