### ISSUE TITLE
with_detect_anomaly provides "unknown line number" in  traceback()

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#634]
Hi, 

Below addresses bug with #627

 When a variable needed for gradient computation has been modified by an in-place operation, Pytorch `torch.autograd.set_detect_anomaly` prints `traceback` with a **line number** for variable in question that "was changed in there or anywhere later". For example:

```
with torch.autograd.set_detect_anomaly(True):
        
  x = torch.rand(2, requires_grad = True)
  y = torch.rand(1)
  b = (x**y).sum()
  y.add_(1)
  b.backward()
```

Traceback says:
`line 12, in <module> b = (x**y).sum() 
`
to help identify error in `y.add_(1)`  for debugging into `y.add(1)`

Applying same code with R `with_detect_anomaly`
```
  with_detect_anomaly({
    
    x <- torch_rand(2, requires_grad = TRUE)
    y <- torch_rand(1)
    b <- (x^y)$sum()
    y$add_(1)
    b$backward()
    })
```
results in the following information:
`Warning: Error detected in PowBackward1. Traceback of forward call that caused the error:
000000006C7FC0E5 <unknown symbol address> R.dll!<unknown symbol> [<unknown file> @ <unknown line number>]`

It is difficult to debug with only `PowBackward1` information **(no line number)** for code that has many Pow operations. Shouldn't the traceback() provide line number and function where gradient computation failed `backward()`?

**Comment by dfalbel** [comment]
Hi @dominikj2 

Thanks for reporting. In order to fix this we would need to implement the equivalent of: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_anomaly_mode.cpp

I don't think I'll be able to implement this in the next few weeks. That doesn't look trivial and its not in the top priorities for the project. 

I can understand that without the traceback the mode is not that helpful... Let me know if I can help you debugging your code. You are looking for in-place operations like those calls that end with an underscore eg `x$pow_(2)` which hopefully shound't be that many.

**Comment by dominikj2** [comment]
Hi @dfalbel,

I've tried to identify the variable responsible for "failed to compute its gradient due to modified in-place operation", and have had no success without `with_detect_anomaly`.  Thank you for offering to help me debug my code. The code is located here:

[https://github.com/dominikj2/Torch_R_GIoU_3dRotated_BBox_Loss](url)

It translates pytorch code found here:

[https://github.com/lilanxiao/Rotated_IoU](url)

The error message is `Warning: Error detected in MaxBackward0.` so it should be after a max function:

The **TORCH_GIoU_MIN_ENCLOSING.r** code has `max ` operation in the _**point_line_distance_range**_ function:
  ```
d_max = d$max(dim=-1)[[1]] # torch_max(d, dim =-1)[[1]]       # (..., 24)
  d_min = d$min(dim=-1)[[1]]  # torch_min(d, dim=-1)[[1]]      # (..., 24)
  d1 = d_max - d_min  
  # suppose points on different side
  d2 = torch_max(d$abs(), dim=-1)[[1]]      # or, all points are on the same side
  output = torch_max(d1, other = d2)
```

And in _**point_line_projection_range**_ function:

` proj_max = proj$max(dim=-1)[[1]]  #torch_max(proj, dim =-1)[[1]]       # (..., 24)`

I tried to remove all in-place operators such as below but none of them solved my problems:
 ```
 rotated[.., 1]$add_(x)
  rotated[.., 2]$add_(y)
```

Mind you pytorch code successfully uses in place operations such as below: 
```
   rotated[..., 0] += x
    rotated[..., 1] += y
```

I hope the problem is obvious to you.  I tried to not take up your offer to look at my code but I have run out of ideas. 

I'd be interested to know whether there are other debugging tools for this sort of a problem?  For example, would you use `register_hook`?

**Comment by dfalbel** [comment]
Is there a way to run this code without having to download data, saving into different directories, etc? Maybe a minimal example, just so we can easily test? I don't know where to get the DATA_DIR for example: https://github.com/dominikj2/Torch_R_GIoU_3dRotated_BBox_Loss/blob/main/TORCH_GIoU_Rotating_3d_LOSS_MAIN.R#L26

**Comment by dominikj2** [comment]
Sorry, the code requires no data as it generates data. The directory is where it saves data. 

Hopefully i can get hooks to work today for debugging (if the cuda sys.enviro variable works).

Thanks!

**Comment by dominikj2** [comment]
Hi @dfalbel,

Using `$register_hook` I fixed my in-place op bug. Below line
`d2 = torch_max(d$abs(), dim=-1)[[1]]`
was replaced with
```
d_abs = d$abs()
 d2 = d_abs$max(dim=-1)[[1]]
```
Oddly enough I think `$register_hook` didn't work well as a bugging tool due to a possible **CUDA cache** issue explained below. 

To explain, I'm still getting odd behavior regarding `Sys.setenv(CUDA_LAUNCH_BLOCKING=1)` . With the following three steps: (1) create error message with buggy `$register_hook` approach, (2) fix  `$register_hook` bug, (3) re-run, then re-running (3rd step) result in the below error unless I close RStudio and reopen. After reopening, it sometimes works and sometimes has the same below error message. It seems inconsistent as it sometimes works after a second "close and reopen" of RStudio without changing anything.  

I think it might be a CUDA cache error that muddles up the indexing of a `tensor._version` number. I'm wondering if this behavior could be fixed with Pytorch's ` torch.cuda.empty_cache`. Does R Torch have similar?


```
Error in (function (self, device, dtype, non_blocking, copy, memory_format)  : 
  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from copy_kernel_cuda at C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Copy.cu:200 (most recent call first):
00007FFBD44D10D200007FFBD44D1070 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFBC3BEE30600007FFBC3BEE290 c10_cuda.dll!c10::CUDAError::CUDAError [<unknown file> @ <unknown line number>]
00007FFB29B01BC700007FFB29AE6010 torch_cuda_cu.dll!torch::jit::fuser::cuda::OptOutConstDispatch::handle [<unknown file> @ <unknown line number>]
00007FFB1CA9782300007FFB1CA96C60 torch_cpu.dll!at::native::copy_ [<unknown file> @ <unknown line number>]
00007FFB1CA96CB700007FFB1CA96C60 torch_cpu.dll!at::native::copy_ [<unknown file> @ <unknown line number>]
00007FFB1D1F0D9E00007FFB1D1F0CF0 torch_cpu.dll!at::redispatch::copy_ [<unkno
```

Once the in-place op error was fixed I now get this error. Not sure if could be fixed with ` torch.cuda.empty_cache` :
```
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [7,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [16,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [17,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Error in (function (self, dim, index, sparse_grad)  : 
  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from _launch_scatter_gather_kernel at C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:79 (most recent call first):
00007FFB909610D200007FFB90961070 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFBC3BEE30600007FFBC3BEE290 c10_cuda.dll!c10::CUDAError::CUDAError [<unknown file> @ <unknown line number>]
00007FFB2A3DB47900007FFB2A3CF310 torch_cuda_cu.dll!at::native::cummin_helper_cuda [<unknown file> @ <unknown line number>]
00007FFB2A3DFDE500007FFB2A3CF310 torch_cuda_cu.dll!at::native::cummin_helper_cuda [<unknown file> @ <unknown line number>]
00007FFB2A3DCA7C00007FFB2A3CF310 torch_cuda_cu.dll!at::native::cummin_helper_cuda [<unknown file> @ <unknown line number>]
00007FFB2A3E220D00007FFB2A3CF310 torc
```
