### ISSUE TITLE
Unexpected behaviour of bracket in do.call for tensor

### ISSUE THREAD

**Issue by vwrobel** [mlverse/torch#637]
Hi,

I need to slice a tensor based on slices defined dinamically for all dimensions.

Say I have these:

```
m <- matrix(1:9, ncol = 3, byrow = TRUE)
t <- torch::torch_tensor(m)

slices <- list(1:2, 1:2)
```

`do.call('[', c(list(m), slices))`

gives
```
     [,1] [,2]
[1,]    1    2
[2,]    4    5 
```

`do.call('[', c(list(t), slices))`

gives
```
torch_tensor
 1
 5
[ CPULongType{2} ]
```

while
`'['(t, 1:2, 1:2)`
gives
```
torch_tensor
 1  2
 4  5
[ CPULongType{2,2} ]
```

I could not find any help with this in the doc.

Why is the bracket operator behaving this way in do.call?

What would be a proper way to slice a tensor based on dinamically created slices that can vary in dimension?

I would appreciate any help with this. Thanks for this package!

**Comment by dfalbel** [comment]
Hi @vwrobel ,

Thanks for reporting!
This is a bug. A minimal reprex would be:

``` r
library(torch)
m <- matrix(1:9, ncol = 3, byrow = TRUE)
t <- torch::torch_tensor(m)
t[c(1,2), c(1,2)]
#> torch_tensor
#>  1
#>  5
#> [ CPULongType{2} ]
```

So it's not really caused by do.call, but by the fact that we are indexing by 2 numeric vectors. 
For efficiency reasons, we do some interpretations when indexing with range, like `1:3`.

As a work around you can do something like:

``` r
library(torch)
m <- matrix(1:9, ncol = 3, byrow = TRUE)
t <- torch::torch_tensor(m)

slices <- list(1:2, 1:2)

for(i in seq_along(slices)) {
  t <- torch_index_select(t, dim = i, slices[[i]])
}
```

**Comment by vwrobel** [comment]
Thanks a lot!

As I understand, `torch_index_select` will each time use a different storage for the new tensor. As I need to use my slicing function frequently in my program, this seems to results in a significative deoptimization.

So what I ended up doing is, recreating a string from my slices and use eval:

```R
slices_string <- "1:100, 100:200, 1" 
eval_string <- "t[%s, drop = F]" %>% 
  sprintf(slices_string)
t <- eval(parse(text=eval_string))
```
Much quicker in my case. Thanks again!

**Comment by dfalbel** [comment]
Oh yeah, range based indexing should be much faster than indexing by a vector.
