### ISSUE TITLE
ETM

### ISSUE THREAD

**Issue by jwijffels** [mlverse/torch#650]
I see on the website  https://torch.mlverse.org/packages that 

> If you are developing a torch extension, contact us on GitHub so we can feature it

I've put https://github.com/bnosac/ETM available online. It does text clustering on embeddings. Feel free to add it to your ecosystem site.
I hope to have it on CRAN this month.

**Comment by dfalbel** [comment]
Awesome! I'll add it to the extensions page!
Let us know if you are also interested in writing a blog post introducing ETM in the [RStudio AI Blog](https://blogs.rstudio.com/ai/).

**Comment by jwijffels** [comment]
Thank you for this fix (https://github.com/mlverse/torch/issues/636) you did, that allowed to test the package. 
I could compare doc2vec::top2vec  and ETM::ETM for topic clustering on embeddings in a blog post. I'll contact you here if I'll have time for this.

**Comment by dfalbel** [comment]
You should now be able to see ETM in the extensions page: https://torch.mlverse.org/packages/

![image](https://user-images.githubusercontent.com/4706822/129032563-a91cb82a-5b17-4152-90c8-a23c662114fe.png)

**Comment by jwijffels** [comment]
nice!
