### ISSUE TITLE
https://torch.mlverse.org server is falling

### ISSUE THREAD

**Issue by mohamed-180** [mlverse/torch#652]
little times i can open https://torch.mlverse.org page

**Comment by mohamed-180** [comment]
for me for while

**Comment by dfalbel** [comment]
I have tried checking the torch website in this platform and coulnd't find any problem

http://www.site24x7.com/tools/public/t/results-1628771504532.html

If the problem persist, could you please inform your location and I can open a ticket Netlify for them to investigate?
