### ISSUE TITLE
Implement `[` for `nn_sequential` modules.

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#675]
So we can get a subset of the model layers.

**Comment by mohamed-180** [comment]
Can we use s3 method dispatch like this :

```
`[.nn_sequential` <- function(x,y) {
x$children[y]
}
```
in https://github.com/mlverse/torch/blob/c3803922d6687b5d683246d6b46e8273ed1ff652/R/nn.R#L675

**Comment by mohamed-180** [comment]
Or we can use `modules` method for recursively iterate over modules
discussion here :
[https://discuss.pytorch.org/t/module-children-vs-module-modules/4551/10](url)

`[.nn_sequential` <- function(x,y) {
x$modules[y]
}

the problem here is nn_sequential has index

**Comment by dfalbel** [comment]
Yes, I think we would need to implement something similar to:

https://github.com/mlverse/torch/blob/173df9f078d8f9667f85beb32f472cdf39e9c9f6/R/nn.R#L675-L681

to extract a single index, then the `[` to extract multiple indexes would be:

```
`[.nn_sequential` <- function(x, y) {
  nn_sequential(!!!lapply(y, function(i) x[[i]]))
}
```

so we return a new sequential module based on the selected layers.
Do you want to create a PR?
