### ISSUE TITLE
jit -> mobile wishlist

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#676]
- optimize_for_mobile
- _save_for_lite_interpreter

```
import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torchvision.models.mobilenet_v3_small(pretrained=True)
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
optimized_traced_model = optimize_for_mobile(traced_script_module)
optimized_traced_model._save_for_lite_interpreter("app/src/main/assets/model.ptl")
```

**Comment by mohamed-180** [comment]
Dose the implementation must begin from here :

https://github.com/mlverse/torch/blob/13970e9d3b7bd8128e96cfc6542f07910e4e9a88/src/script_module.cpp#L23-L26

**Comment by skeydan** [comment]
Maybe also quantization (see https://pytorch.org/tutorials/recipes/quantization.html, (3): Post Training Static Quantization)

(using pre-quantized models is not applicable to every use case, e.g., when using a pre-trained model as a feature detector)

**Comment by skeydan** [comment]
See also https://pytorch.org/mobile/home/ for the overall workflow:

![image](https://user-images.githubusercontent.com/469371/133224414-3e8d6059-a8d2-4eeb-82cf-0ad0b965a96a.png)

At this point, it seems to me that all of the three steps

- quantization
- optimization
- saving for lite interpreter 


are optional - but I'm not sure about the last (yet).

**Comment by dfalbel** [comment]
Hey! I'm closing it because we now have: https://github.com/mlverse/torch/pull/713
I think the rest API can be implemented on per-request basis.
