### ISSUE TITLE
installation:  file too short

### ISSUE THREAD

**Issue by parsifal9** [mlverse/torch#677]
Hi torch,
I have an installation issue. It seems that the file  liblantern.so is too short (sizes below). It is not a download timeout as the much larger  libtorch-cxx11-abi-shared-with-deps-1.9.0+cu111.zip is downloaded without problems.

Bye
R

```
> library(torch)
trying URL 'https://download.pytorch.org/libtorch/cu111/libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcu111.zip'
Content type 'application/zip' length 2148133921 bytes (2048.6 MB)
==================================================
downloaded 2048.6 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.5.0/latest/Linux-gpu-111.zip'
Content type 'application/zip' length 1889110 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

Warning message:
Failed to install Torch, manually run install_torch().
 /home/dun280/local/lib/R/x86_64-pc-linux-gnu/4.0/site-library/torch/deps/liblantern.so - /home/dun280/local/lib/R/x86_64-pc-linux-gnu/4.0/site-library/torch/deps/liblantern.so: file too short 
```

and using the file install I get the same problem
```
install_torch_from_file(libtorch = "file:///scratch1/dun280/torch/libtorch-cxx11-abi-shared-with-deps-1.9.0+cu111.zip",
                        liblantern = "file:///scratch1/dun280/torch/Linux-gpu-111.zip")
#Error in cpp_lantern_init(install_path()) : 
#  /home/dun280/local/lib/R/x86_64-pc-linux-gnu/4.0/site-library/torch/deps/liblantern.so - /home/dun280/local/lib/R/x86_64-pc-linux-gnu/4.0/site-library/torch/deps/liblantern.so: file too# short
```
$: ls -l
total 2107731
-rw-r--r-- 1 dun280 hpc-users    1889110 Aug 17 06:55 Linux-gpu-111.zip
-rw-r--r-- 1 dun280 hpc-users    6403192 Aug 17 06:55 liblantern.so
-rw-r--r-- 1 dun280 hpc-users 2148133921 Jun 16 00:48 libtorch-cxx11-abi-shared-with-deps-1.9.0+cu111.zip

> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Server 15 SP2

Matrix products: default
BLAS/LAPACK: /apps/intel/mkl/2020.1.217/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=C              
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] torch_0.5.0

loaded via a namespace (and not attached):
 [1] processx_3.5.1 bit_4.0.4      compiler_4.0.5 magrittr_2.0.1 tools_4.0.5   
 [6] withr_2.4.1    Rcpp_1.0.6     bit64_4.0.5    coro_1.0.1     callr_3.6.0   
[11] ps_1.6.0       rlang_0.4.11  
> q()

module list #the machine uses a module management system
Currently Loaded Modulefiles:
 1) SC                             6) realvnc/6.7.2         11) python/3.9.4(default)         
 2) slurm/current(default)         7) xfce/4.12             12) cuda/11.2.1(default)          
 3) intel-cc/2020.4.304(default)   8) emacs/27.2            13) cudnn/8.1.1-cuda112(default)  
 4) intel-fc/2020.4.304(default)   9) intel-mkl/2020.1.217  14) cuda/11.1.1                   
 5) cuda-driver/current           10) R/4.0.5(default)

**Comment by mohamed-180** [comment]
Would you see this #671

**Comment by parsifal9** [comment]
Closing this issue. I suspect that was a disk quota problem! I just couldn't install the files in site-library/torch/deps
Seems to be installed without error now.
Sorry for that

**Comment by parsifal9** [comment]
sorry for taking up your time
