### ISSUE TITLE
CUDA 11.1 vs install_torch on Windows

### ISSUE THREAD

**Issue by jonthegeek** [mlverse/torch#687]
Like linux, we need to use nvcc to find the CUDA version number for 11.1+. Exactly the same code as is used for linux seems to work, so some relatively simple refactoring should fix it.

**Comment by harryprince** [comment]
### Problem:
the same issue, after correct installing CUDA11.1 on Windows:

'''
Sys.setenv(CUDA="11.1")

torch::install_torch_from_file(type = "11.1",libtorch = "file:///C:/Users/Harry/Downloads/libtorch-win-shared-with-deps-1.9.0+cu111.zip",
                               liblantern = "file:///C:/Users/Harry/Downloads/Windows-gpu-111.zip")
'''

'''
torch::cuda_is_available()
# False
'''

### Dependency：


CUDA Version：
'''
PS C:\Users\Harry> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:12:04_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0
'''

ENV info:

'''
> Sys.getenv()
ALLUSERSPROFILE                                     C:\ProgramData
APPDATA                                             C:\Users\Harry\AppData\Roaming
CLICOLOR_FORCE                                      1
CommonProgramFiles                                  C:\Program Files\Common Files
CommonProgramFiles(x86)                             C:\Program Files (x86)\Common Files
CommonProgramW6432                                  C:\Program Files\Common Files
COMPUTERNAME                                        DESKTOP-H3T6660
ComSpec                                             C:\WINDOWS\system32\cmd.exe
CUDA                                                11.1
CUDA_PATH_V11_1                                     C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
DISPLAY                                             :0
DriverData                                          C:\Windows\System32\Drivers\DriverData
GFORTRAN_STDERR_UNIT                                -1
GFORTRAN_STDOUT_UNIT                                -1
HOME                                                C:/Users/Harry/Documents
HOMEDRIVE                                           C:
HOMEPATH                                            \Users\Harry
LOCALAPPDATA                                        C:\Users\Harry\AppData\Local
LOGONSERVER                                         \\DESKTOP-H3T6660
MPLENGINE                                           tkAgg
MSYS2_ENV_CONV_EXCL                                 R_ARCH
NUMBER_OF_PROCESSORS                                6
NVCUDASAMPLES11_1_ROOT                              C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.1
NVTOOLSEXT_PATH                                     C:\Program Files\NVIDIA Corporation\NvToolsExt\
OneDrive                                            C:\Users\Harry\OneDrive
OneDriveConsumer                                    C:\Users\Harry\OneDrive
OS                                                  Windows_NT
PATH                                                C:\Program Files\R\R-4.1.2\bin\x64;C:\Program Files\NVIDIA GPU Computing
                                                    Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing
                                                    Toolkit\CUDA\v11.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
                                                    Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                                                    NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                                                    Files\NVIDIA Corporation\Nsight Compute
                                                    2020.2.0\;C:\Users\Harry\miniconda3;C:\Users\Harry\miniconda3\Library\mingw-w64\bin;C:\Users\Harry\miniconda3\Library\usr\bin;C:\Users\Harry\miniconda3\Library\bin;C:\Users\Harry\miniconda3\Scripts;C:\Users\Harry\AppData\Local\Microsoft\WindowsApps;C:\Program
                                                    Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing
                                                    Toolkit\CUDA\v11.1\extras\CUPTI\libx64;C:\Program Files\NVIDIA GPU Computing
                                                    Toolkit\CUDA\v11.1\include;C:\tools\cuda\bin;C:\Program Files\NVIDIA
                                                    Corporation\NVSMI;C:\Anaconda3\Library\bin;C:\Users\Harry\AppData\Local\Microsoft\WindowsApps;
PATHEXT                                             .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE                              AMD64
PROCESSOR_IDENTIFIER                                Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL                                     6
PROCESSOR_REVISION                                  9e0a
ProgramData                                         C:\ProgramData
ProgramFiles                                        C:\Program Files
ProgramFiles(x86)                                   C:\Program Files (x86)
ProgramW6432                                        C:\Program Files
PSModulePath                                        C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                                              C:\Users\Public
PYTHONIOENCODING                                    utf-8
QT_D3DCREATE_MULTITHREADED                          1
R_ARCH                                              /x64
R_COMPILED_BY                                       gcc 8.3.0
R_DOC_DIR                                           C:/PROGRA~1/R/R-41~1.2/doc
R_HOME                                              C:/PROGRA~1/R/R-41~1.2
R_LIBS_USER                                         C:/Users/Harry/Documents/R/win-library/4.1
R_USER                                              C:/Users/Harry/Documents
RETICULATE_PYTHON                                   C:/Users/Harry/Anaconda3/envs/r-reticulate/Python.exe
RMARKDOWN_MATHJAX_PATH                              C:/Program Files/RStudio/resources/mathjax-27
RS_LOCAL_PEER                                       \\.\pipe\23766-rsession
RS_RPOSTBACK_PATH                                   C:/Program Files/RStudio/bin/rpostback
RS_SHARED_SECRET                                    63341846741
RSTUDIO                                             1
RSTUDIO_CONSOLE_COLOR                               256
RSTUDIO_CONSOLE_WIDTH                               80
RSTUDIO_MSYS_SSH                                    C:/Program Files/RStudio/bin/msys-ssh-1000-18
RSTUDIO_PANDOC                                      C:/Program Files/RStudio/bin/pandoc
RSTUDIO_PROGRAM_MODE                                desktop
RSTUDIO_SESSION_PORT                                23766
RSTUDIO_USER_IDENTITY                               Harry
RSTUDIO_WINUTILS                                    C:/Program Files/RStudio/bin/winutils
SESSIONNAME                                         Console
SystemDrive                                         C:
SystemRoot                                          C:\WINDOWS
TEMP                                                C:\Users\Harry\AppData\Local\Temp
TERM                                                xterm-256color
TMP                                                 C:\Users\Harry\AppData\Local\Temp
USERDOMAIN                                          DESKTOP-H3T6660
USERDOMAIN_ROAMINGPROFILE                           DESKTOP-H3T6660
USERNAME                                            Harry
USERPROFILE                                         C:\Users\Harry
windir                                              C:\WINDOWS
'''

**Comment by harryprince** [comment]
I think the torch R project needs to build a clear dependency analysis tool for Windows first, instead of the other fancy function.
The bad installation experience will lose the trust of this project.

**Comment by harryprince** [comment]
The sf project is a good case, the installation is pretty easy for the end-user, including gdal, proj, geotiff and so on.

**Comment by dfalbel** [comment]
hi @harryprince ! Happy to take contributions on that area. How do you suggest us to make the installation on Windows better? 

I think with have some key differences from `sf` like depending on specific versions of libtorch and the cudatoolkit. No trivial possibility to install dependecies from rwinlib because compilation must happen with MSVC compiler (non MinGW) and other special necessities.

We are trying to make installation as straightforward as possible and willing to take all steps to improve it. 

From your first post, it doesn't seem that all dependencies have been correctly copied to the dependencies directory. Maybe there was some kind of corruption during download or extraction. This might be caused by lack of disk space.
