### ISSUE TITLE
Feature request: TORCH_GEOMETRIC.NN in R

### ISSUE THREAD

**Issue by mm0708** [mlverse/torch#692]
Are there plans to implement the geometric nnet features in R?

**Comment by skeydan** [comment]
Hi,

thanks for asking! We would certainly be interested in having an equivalent of PyTorch Geometric in the R `torch` ecosystem.
We plan to look into the prerequisites (which won't be trivial) in the nearer future, but can't as of today name a more concrete date.

Once we've explored the options, and the groundwork has been done, we'd be very happy to have contributors for that project (which is pretty huge)!

**Comment by karrtikiyer** [comment]
Hi @skeydan & @dfalbel  : Any further updates on this feature request? Thanks in advance, regards!
