### ISSUE TITLE
Indexing error when using `..`

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#695]
I think there is another issue now, 

```
a <- torch_randn(c(3,4,2))
c <- torch_randn(c(3,4,2))
b <- c(1,2,4)
a[..,torch_tensor(as.integer(b)),]
c[..,torch_tensor(as.integer(b)),]
b
```

`Error in Tensor_slice(tensor$ptr, environment(), drop = drop, mask = .d): index 3 is out of bounds for dimension 0 with size 2
Exception raised from get at aten/src/ATen/native/cpu/IndexKernel.cpp.AVX2.cpp:42 (most recent call first)`

The error does not occur if we do not use the `..` annotation.

_Originally posted by @emauryg in https://github.com/mlverse/torch/issues/691#issuecomment-927501469_

**Comment by mohamed-180** [comment]
@dominikj2 
As workaround you we can use : 
```
a <- torch_randn(c(3,4,2))
b <- c(1,2,4)
a$index_select(2,as.integer(torch_tensor(b)))
```

**Comment by mohamed-180** [comment]
@dfalbel 
Does it related to :

https://github.com/mlverse/torch/blob/e839b18485fb2922968226bfe8f9b7824ca195f0/src/indexing.cpp#L130-139
