### ISSUE TITLE
Predict an image CNN

### ISSUE THREAD

**Issue by MelihOrel** [mlverse/torch#721]
Hello, how can I predict an image on R torch? 

`AlexNetmodel.eval()
with torch.no_grad():
    new_pred = AlexNetmodel(.view(1,3,224,224)).argmax()
print(f'Predicted value: {new_pred.item()} {class_names[new_pred.item()]}')`

I need to convert this python code to R code.

**Comment by dfalbel** [comment]
``` r
library(torch)
library(torchvision)

tmp <- tempfile(fileext = ".jpeg")
download.file(
  "https://media.istockphoto.com/photos/european-short-haired-cat-picture-id1072769156?k=20&m=1072769156&s=612x612&w=0&h=k6eFXtE7bpEmR2ns5p3qe_KYh098CVLMz4iKm5OuO6Y=",
  tmp
)

img <- base_loader(tmp) %>% 
  transform_to_tensor() %>% 
  transform_resize(c(224, 224))


model <- model_alexnet(pretrained = TRUE)
model$eval()

with_no_grad({
  pred <- model(img$unsqueeze(1))$argmax()
})

print(pred)
#> torch_tensor
#> 286
#> [ CPULongType{} ]
```

You can then find the classname in any imagenet mapping like: https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a

**Comment by MelihOrel** [comment]
Thanks for your help!!! @dfalbel  Now, I can continue to work on my project. Many thanks for your time.
