### ISSUE TITLE
export `is_torch_tensor()`?

### ISSUE THREAD

**Issue by rdinnager** [mlverse/torch#728]
I always end up writing an `is_torch_tensor()`  as a utility function for most of my `torch` projects, because I get tired of typing `inherits(x, "torch_tensor")` (which cannot autocomplete). Would you consider exporting this function? I find it pretty handy.

**Comment by dfalbel** [comment]
Sure! We can definitely export it. Do you want to file a PR?

**Comment by rdinnager** [comment]
Do you mind if I add a `%*%` operator for `torch_tensor` that calls `torch_matmul()` as well? I ask because I am trying to port some Python code which uses the `@` operator to matrix multiply tensors and it will be a lot easier to simply replace the operator as opposed to wrapping as arguments to `torch_matmul`. Sorry this is not related to the original issue, I just thought I'd ask as long as I'm going to make a PR, and there could be a good reason why this isn't implemented that I am not aware of.

**Comment by dfalbel** [comment]
IIRC it's not trivial to implement `%*%` for S3 classes. @t-kalinowski had an issue when implementing this in tensorflow but I don't remember if it was ever solved:

https://stackoverflow.com/questions/69453749/make-r-matrix-multiplication-dispatch-on-s3-objects

basically, for the dispatching to work one of the arguments must be S4 objects but that's not the most common case.

**Comment by rdinnager** [comment]
Ah, I was not aware of this. This may be beyond my current R skills to get around. I might take a quick look into it, but I likely will leave it be. That is a shame. Thanks for pointing me to this information, it is certainly good to know for future reference as well.

I suppose the alternative is to create a new custom operator `%mm%` or something (or `%@%` in analogy with Python)? This may not be ideal though.

**Comment by rdinnager** [comment]
Does this look like a valid solution?
https://stackoverflow.com/questions/40580149/overload-matrix-multiplication-for-s3-class-in-r

It seems to work for me in an R session. Not sure if any issues would crop up in a package though.

**Comment by dfalbel** [comment]
I don't think the SO solution is good because it won't work if you don't `library(torch)` and it will raise warnings telling that we are overwriting functions from base when loading.

I would be fine with something like `%mm%` if you think that would be useful for your use cases.
