### ISSUE TITLE
torch.cuda.get_device_capability() for R?

### ISSUE THREAD

**Issue by rdinnager** [mlverse/torch#729]
In some Python code I am trying to port it uses `torch.cuda.get_device_capability()` to decide whether to use some custom ops (e.g. Ampere vs. Volta). Is there a way to get equivalent information from `torch` in R? I can't seem to find an equivalent function, but I could be missing it.
Many thanks.

**Comment by dfalbel** [comment]
Currently its not implemented, but we should be able to get this information by wrapping `at::cuda::getDeviceProperties`:

https://pytorch.org/cppdocs/api/function_namespaceat_1_1cuda_1af6a77be40bebc6666d6832d071f7412c.html#exhale-function-namespaceat-1-1cuda-1af6a77be40bebc6666d6832d071f7412c

**Comment by rdinnager** [comment]
Would you like me to try a PR?  If I'm not mistaken, this would require adding wrappers:
- here:
https://github.com/mlverse/torch/blob/master/lantern/src/Cuda.cpp
- here:
https://github.com/mlverse/torch/blob/master/src/cuda.cpp
- and here?:
https://github.com/mlverse/torch/blob/master/R/cuda.R

**Comment by dfalbel** [comment]
Sure! It would be awesome! 

You will also need to export the function in the lantern headers. 
See for example this PR:

https://github.com/mlverse/torch/pull/713/files#diff-cdf41c6f2680495f3b1bb228ee65924bcf3bd39fc73df81f922163600f8d9504R724

**Comment by rdinnager** [comment]
Ah yes of course. Thanks for the example PR, I should be able to work everything out by following it.
