### ISSUE TITLE
Torch and CUDA Version / lantern

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlverse/torch#737]
Hi, 

torch did not autodetect my cuda installation. Therefore it downloaded the CPU-Version. To overcome this, I searched the issues here and did this:
unintall torch - package
restart R
Sys.setenv(CUDA="11.4")
install.packages("torch")
install_torch(type = '11.1')

So far so good. cuda_is_available() tells me "TRUE".

What bothers me is that I actually have the newest version of cuda installed, but in the last step got told that 
"Error in lantern_install_libs(version, type, path, install_config) : 
  The 11.4 installation type is currently unsupported."

- It would be nice to get a message saying, which is the last supported version. I had to figure that out from the forum here
- I wonder whether I need to downgrade my System Cuda now to fit the 11.1?
- Can this process somehow be made a little smoother?

All the best!

**Comment by dfalbel** [comment]
Thanks @GitHubGeniusOverlord for reporting! 

- Sure we can improve the error message so it also shows the last supported versions. 
- In general you can have multiple versions of the CUDA toolkit coexisting in your system, so you shoudn't need to downgrade, but install CUDA 11.1 additionally.
