### ISSUE TITLE
ability to automatically load pytorch models without having to pre-build model structure in R

### ISSUE THREAD

**Issue by mattrichard-datascience** [mlverse/torch#745]
This would be amazing!

cheers,
Matt Richard

**Comment by dfalbel** [comment]
In theory this is possible if your model has been saved with `torch.jit.save` in PyTorch or its equivalent in other frontends. 
In this case you can simply use `jit_load` the model to load both the architecture and the weights.

**Comment by mattrichard-datascience** [comment]
I could be doing something wrong,  but I don't think it works.

Could you take a look at making the strategy work for the python model

<<< model = torchvision.models.detection.keypointrcnn_resnet50_fpn(pretrained=True)

<<< torch.jit.save(model, 'scriptmodule.pt')

jit saving throws the error 'AttributeError: 'KeypointRCNN' object has no attribute 'save''

**Comment by dfalbel** [comment]
Hi @mattrichard-datascience , this is because we still don't have these operators. 
Could you try installing: https://github.com/mlverse/torchvisionlib 

then simply:

```
library(torchvisionlib)
torch::jit_load("model_path")
```

Should work.

I'm closing, but feel free open an issue in torchvisionlib so we can debug further.
