### ISSUE TITLE
Experimenting with torch:: functions

### ISSUE THREAD

**Issue by egillax** [mlverse/torch#793]
Let's say I would like to experiment with using some functions straight from the libtorch front end (torch:: namespace) that are not currently supported in torch. Is there a guide or code/commit somewhere with the steps required to do that? I'd guess it would involve using Lantern and Rcpp to get the R objects to C++ and back again.

I guess the use case I had in mind was to try to see if using the optimizers straight from c++ would speed it up. But in general it would help me learn the package structure better which could help me contribute.

**Comment by dfalbel** [comment]
Hi @egillax,

You can take a look at: https://github.com/mlverse/lltm
The readme has a walkthrough guide on how to do it, and the repository itself should serve as a minimal template.

**Comment by egillax** [comment]
thanks that's exactly what I need.
