### ISSUE TITLE
Detect CUDA version without version.txt?

### ISSUE THREAD

**Issue by SvenVw** [mlverse/torch#797]
I am trying to install the gpu version of torch on my windows machine. However, torch does not to recognize that CUDA 11.1 is installed on my machine.
When looking at the source code I see that torch checks for a `version.txt` file located at `cuda_path`:
https://github.com/mlverse/torch/blob/0afe34f8fbf13a7ff2a13c342544bf9a5e0b8c84/R/install.R#L243
However, it seems that from CUDA 11 onwards this file is not supplied anymore. Could another method be used to detect the CUDA version? For example: https://github.com/llvm/llvm-project/commit/e7fe125b776bf08d95e60ff3354a5c836218a0e6

Thanks in advance!

**Comment by dfalbel** [comment]
Are you on Linux or Windows?

Yeah, we should definitely implement something like this. Looks like parsing `cuda.h` is a reasonable approach. I think we already handle on Linux by querying nvcc:

https://github.com/mlverse/torch/blob/0afe34f8fbf13a7ff2a13c342544bf9a5e0b8c84/R/install.R#L302-L304

I think both approaches should be fine. Would you like to contribute a PR?

In the meantime, you can manually set the cuda version with `Sys.setenv(CUDA="11.1")` too to avoid the automatic detection.

**Comment by SvenVw** [comment]
Yes I am on Windows. Parsing `cuda.h` seems a little bit difficult to me, but querying nvcc should be possible. I will try to contribute a PR for this issue

**Comment by dfalbel** [comment]
Awesome! That's very helpful. I don't have a Windows machine with a GPU to experiment, so it's hard to make sure it works.

**Comment by dfalbel** [comment]
Closed in #798
