### ISSUE TITLE
GPU can't work

### ISSUE THREAD

**Issue by Bioerjzy** [mlverse/torch#800]
Firstly, it's very nice for you to develop this package. However, I can't use my GPU for this package. When I run the code, the R
will stuck, and I have to restart R. But I can run torch in python.
So I want to ask you if this package need special version of CUDA or other things?

**Comment by Bioerjzy** [comment]
![image](https://user-images.githubusercontent.com/69882352/158770345-8a007062-3c9f-4d4c-a69d-a1718dd76d0f.png)

**Comment by Bioerjzy** [comment]
![image](https://user-images.githubusercontent.com/69882352/158771784-790abe92-3dec-4c75-bb80-2656012608a6.png)

**Comment by DallasElleman** [comment]
Hi @Bioerjzy I am having the same issue, did you ever figure it out? Thanks!

**Comment by dfalbel** [comment]
Hi! You can take a look at instructions here: https://torch.mlverse.org/docs/articles/installation.html#gpu
You might be missing additional software installation.
