### ISSUE TITLE
export Sampler?

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torch#808]
Hey, 

I would like to use the samplers (Sampler, SequentialSampler, RandomSampler and BatchSampler) in an R package, but they are not being exported. Is it possible to export them? 

Thanks in advance!

Sebastian

**Comment by dfalbel** [comment]
Sure! Ideally we should also have a `sampler` constructor similar to what `dataset`, `nn_module` and `optimizer` do. But I'm fine with exporting the classes directly since this is a quite low level API.

Do you want to file a PR?
