### ISSUE TITLE
add a `nn_prune_head()` utility function

### ISSUE THREAD

**Issue by cregouby** [mlverse/torch#812]
Hello,

It took me a while to find an good way to prune head of a pretrained nn_module, to turn it into an embedding module.
Finally 
```r
pruned_model <- torch::nn_sequential(!!!model$children[1:(length(model$children)-1)])
```
did it.

I think it would be convenient to have this as an utility function, either with explicit parameter `module=1L` either with an heuristic to prune all fully-connected / linear / batch_norm / *elu layers from the tail.

**Comment by dfalbel** [comment]
I think it will be hard to come up with a good heuristic. For instance, many of the torchvision models don't use sequential modules: 

https://github.com/mlverse/torchvision/blob/5258a19a8d1c7ca18db66364534ae2ed5ffe32b8/R/models-mobilenetv2.R#L121-L127

I think it would make sense to have the utility, but narrow the scope so it works only with sequential modules. What do you think?

**Comment by cregouby** [comment]
Seems good to me ! I'll try a PR.
Is {torch} the right place for it ? or is {luz} more appropriate ?

**Comment by dfalbel** [comment]
I am fine with having it in torch! I'd add in the same file as `nn_sequential` is defined.
