### ISSUE TITLE
Random error: Error in resolve_size(...) : You should specify a single size argument.

### ISSUE THREAD

**Issue by mchikina** [mlverse/torch#823]
I randomly get the error "You should specify a single size argument."
when calling model=net()  though never when it is called for the first time.

The error itself has nothing to do with torch, is there any way to avoid it.

**Comment by dfalbel** [comment]
`resolve_size` is an internal torch function so it's likely something with the torch code:

https://github.com/mlverse/torch/blob/7f95e3cadf5dc2d52cecf514513c2875113a0e3c/R/creation-ops.R#L1-L19

Can you share your implementation of `net`?
