### ISSUE TITLE
Error when trying to install liblantern

### ISSUE THREAD

**Issue by krzjoa** [mlverse/torch#831]
Hi, 
When installing **[tft](https://github.com/mlverse/tft)** library, I accepted the update of torch. 
Unfortunately, I cannot install liblantern anymore. I try to install the following pair of libs:
- libtorch-cxx11-abi-shared-with-deps-1.10.2+cu111.zip
- Linux-gpu-111.zip

using  `torch::install_torch_from_file` and I always get the error below:

![obraz](https://user-images.githubusercontent.com/17183113/169918333-d9e85601-8bb9-4d97-96f4-013802465143.png)
I tried to re-install torch from the GitHub repo, but it didn't help. 

Previously I used one of the earlier versions of torch with:
- libtorch-cxx11-abi-shared-with-deps-1.10.1+cu111.zip
- Linux-gpu-111.zip

Is the change from libtorch 1.10.1 to 1.10.2 so drastic that I cannot update it and be compatible with my current driver, CUDA etc.?
Or maybe the problem lies elsewhere?

**Comment by dfalbel** [comment]
Maybe you are using an old version of `Linux-gpu-111.zip` can you try using the following URL:

- [For the current CRAN version (0.7.2)](https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.7.2/latest/Linux-gpu-111.zip)
- [For current dev version](https://storage.googleapis.com/torch-lantern-builds/refs/heads/main/latest/Linux-gpu-111.zip)

Liblantern URL must match the torch version that you are using.

**Comment by krzjoa** [comment]
Thanks! I've used the newest version and it works now. The problem was I thought we can unambiguously identify these files by name, i.e. `Linux-gpu-111.zip` is always the same file. Additionally, I've had to manually remove liblantern.so file before the installation.
