### ISSUE TITLE
Support later versions of cuda such as cuda 11.7 please

### ISSUE THREAD

**Issue by Newtype07** [mlverse/torch#859]
Torch only supports cuda 11.3 or earlier versions, unfortunately my cuda version is 11.7, so GPU accelerating is not available.

**Comment by yulijia** [comment]
> Cuda 11.2 detected but torch only supports: cpu, 10.2, 11.3

My cuda version is 11.2, not supported by Torch neither.  :(

**Comment by dfalbel** [comment]
Cuda 11.6 is now supported. We can't always go to the most recent version because LibTorch doesn't support them.
