### ISSUE TITLE
[Feature request] Warn when overwriting modules of nn_sequential

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torch#863]
I think one should get at least a warning when overwriting already present modules.

``` r
library(torch)
n = nn_sequential()
n$add_module("a", nn_relu())
n$add_module("a", nn_linear(1, 2)) # <<<---

n
#> An `nn_module` containing 4 parameters.
#> 
#> ── Modules ─────────────────────────────────────────────────────────────────────
#> • a: <nn_linear> #4 parameters
```

<sup>Created on 2022-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dfalbel** [comment]
Hey @sebffischer ! THanks for filing this issue!

I guess I see why this would be helpful, but I also can imagine that users could have patterns where overwriting assigned modules is also useful and having the warning message appearing wouldn't be nice.

We could make it fail and provide a `overwrite` argument that could be FALSE by default to support those users. But then I don't know how that could be passed when using the `n[["a"]] <- nn_relu()` syntax. And probably making both behave differently is confusing.

So I'm not entirely sure we should do it. Do you have an example that could help on the discussion?

Best,
