### ISSUE TITLE
torch failed to start

### ISSUE THREAD

**Issue by EKtheSage** [mlverse/torch#866]
Hi,

I am testing `torch` on RStudio Workbench running on CentOS7 and Docker container (Kubernetes).

The error I am getting is:

```
Torch failed to start, restart your R session to try again. 
/home/R/x86_64-pc-linux-gnu-library/4.1/torch/lib/liblantern.so - /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' 
not found (required by /home/R/x86_64-pc-linux-gnu-library/4.1/torch/lib/liblantern.so) 
```
What does the error mean?

Running `strings /lib64/libstdc++.so.6 | grep LIBCXX` in terminal I can see the below output:

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Does that mean I need to update libstdc++ to GLIBCXX_3.4.20? How do I do that?

**Comment by dfalbel** [comment]
Hi,

We don't currently have an easy solution for this, but you should be able to compile liblantern from source and copy it to the same directory as the error message shows.

To do it you can:

1. Clone this repository, fo to the lantern directory: https://github.com/mlverse/torch/tree/main/lantern
2. Run the compilation instructions 
    ```
    mkdir build
    cd build
    cmake ..
    make
    ```
3. Copy the generated `liblantern.so` to `/home/R/x86_64-pc-linux-gnu-library/4.1/torch/lib/liblantern.so`.

Can you point to the Docker image you are using with CentOS 7?

**Comment by EKtheSage** [comment]
Thanks. I can't get to the cmake step - it said the command is not found

I also don't know the the Docker image since I am just a user of the RStudio Workbench.

**Comment by dfalbel** [comment]
Hi @EKtheSage,

This might be related to #868 
Can you try reinstalling torch from github and set the `PRECXX11ABI` env var to `1`. Eg:

```
Sys.setenv("PRECXX11ABI" = 1)
remotes::install_github("mlverse/torch")
library(torch)
```

That will use a pre CXX11 ABI version of LibTorch that is likely to work well with older GLIBC versions.

**Comment by EKtheSage** [comment]
Thanks! This solved the issue.
