### ISSUE TITLE
M1 mac installation issue

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#894]
After installing the main branch from GitHub, I am seeing errors like these:

``` r
library(torch)
#> Warning: ℹ torch failed to start, restart your R session to try again.
#> ℹ You might need to reinstall torch using `install_torch()`
#> ✖ /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/torch/lib/liblantern.dylib
#>   -
#>   dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/torch/lib/liblantern.dylib,
#>   0x000A): Library not loaded: '/opt/homebrew/opt/libomp/lib/libomp.dylib'
#>   Referenced from:
#>   '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/torch/lib/libtorch_cpu.dylib'
#>   Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file),
#>   '/Library/Frameworks/R.framework/Resources/lib/libomp.dylib' (no such file),
#>   '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libomp.dylib'
#>   (no such file)
install_torch()
#> Error in cpp_lantern_init(file.path(install_path(), "lib")): /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/torch/lib/liblantern.dylib - dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/torch/lib/liblantern.dylib, 0x000A): Library not loaded: '/opt/homebrew/opt/libomp/lib/libomp.dylib'
#>   Referenced from: '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/torch/lib/libtorch_cpu.dylib'
#>   Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libomp.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libomp.dylib' (no such file)
```

<sup>Created on 2022-10-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Do you have any advice for what I should try?

_Originally posted by @juliasilge in https://github.com/mlverse/torch/issues/595#issuecomment-1267833975_

**Comment by MOOnLyer** [comment]
I am using llvm and it seems fine during the installation. However, when I try to create a large tensor say 100 by 1,000, R session crashes.

**Comment by dfalbel** [comment]
Are you creating tensors on the 'cpu' device or the 'mps' device? If it's the 'mps' device then it's probably related to #891 .

**Comment by MOOnLyer** [comment]
> Are you creating tensors on the 'cpu' device or the 'mps' device? If it's the 'mps' device then it's probably related to #891 .

I try both `torch::torch_randn(c(100,1000), device = "cpu")` and `torch::torch_randn(c(100,1000), device = "mps")`. It crashes either way.

**Comment by dfalbel** [comment]
@MOOnLyer, let me know if you have problem with the new dev version. openMP is very tricky because it needs to match the compiler's version. I decided to not link the pre-built binaries to openMP which should avoid the crashes.

**Comment by MOOnLyer** [comment]
> @MOOnLyer, let me know if you have problems with the new dev version. openMP is very tricky because it needs to match the compiler's version. I decided to not link the pre-built binaries to openMP which should avoid the crashes.

Thanks for the update. I just install the latest version, and it works like a charm.

**Comment by sezaz-acog** [comment]
try this to reinstall :

`pip3 install torch torchvision --upgrade --force-reinstall`
