### ISSUE TITLE
CUDA 11.6 supported by PyTorch but not R torch

### ISSUE THREAD

**Issue by s-u** [mlverse/torch#901]
`install_torch()` reports on Linux:

    Cuda 11.6 detected but torch only supports: cpu, 10.2, 11.3

Which is not true, 11.6 is supported. Presumably the `install_config` needs updating to use `https://download.pytorch.org/libtorch/cu116/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Bcu116.zip` - manual download and moving into `lib` works.

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS
```

**Comment by dfalbel** [comment]
Thanks for reporting! 

In theory, the C wrappers (Lantern) are also built for specific CUDA versions, so you could have random crashes by just switching LibTorch. We now provide provide pre-built binaries for Lantern too.
