### ISSUE TITLE
[lib request] Please Add non abi11 build of LibLantern for Cuda 11.6

### ISSUE THREAD

**Issue by cregouby** [mlverse/torch#918]
Hello,

Could you please add support for the following 
- Liblantern for CUDA 11.6 PRE C++11 ABI to the file repository ? 

As a matter of facts, it would be good to ensure **version parity** for NonABI liblantern and C++11 ABI Liblantern for each and every CUDA supported version. This is because there is no way to render an explicit error message to the end-user... 

# (Not a ) ReprEx

This is my (expected) environment
```r
> Sys.getenv("PRECXX11ABI")
[1] "1"
> torch:::get_install_libs_url()
$libtorch
[1] "https://download.pytorch.org/libtorch/cu116/libtorch-shared-with-deps-1.12.1%2Bcu116.zip"

$liblantern
[1] "https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.0/latest/LinuxNonABI-gpu-116.zip"
```
But the downloaded file do not exist
```bash
wget https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.0/latest/LinuxNonABI-gpu-116.zip
--2022-10-28 15:42:36--  https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.9.0/latest/LinuxNonABI-gpu-116.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.75.240, 216.58.214.176, 216.58.215.48, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.75.240|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-28 15:42:36 ERROR 404: Not Found.
```

Thanks !

**Comment by dfalbel** [comment]
You are right! The way it's currently implemented is kind of hacky. 
I'll build the non ABI version.

**Comment by cregouby** [comment]
Great ! (plus I'm afraid I may overhack the hacky with ROCM )
