### ISSUE TITLE
Behaviour of torch_normal

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlverse/torch#927]
Hi,

I am unsure about the behaviour of torch_normal. 
When using pytorch, this
`n = torch.distributions.Normal(0,1)
n.sample()`
works. However in R - torch
`torch_normal(0,1)` would already lead to an error
Error in `value_error()`:
! size is not set.

This leads me to some problems in translating pytorch code to torch code. In my view, the translation from one into the other should be as easy as possible. 

Thank You for commenting!

**Comment by dfalbel** [comment]
Hi @GitHubGeniusOverlord ,

Thanks for reporting! I think you want `distr_normal()` instead, eg:

``` r
library(torch)

n <- distr_normal(0, 1)
n$sample(10)
#> torch_tensor
#>  0.5460
#>  0.5696
#>  0.4946
#> -1.4143
#> -0.1661
#>  0.0716
#>  0.7821
#> -1.9102
#> -0.8889
#> -0.6159
#> [ CPUFloatType{10,1} ]
```

Let me know if this works!

**Comment by GitHubGeniusOverlord** [comment]
Thank You @dfalbel , 
this works. Just one remark: I believe that easy translation from pytorch to torch code will be what makes this project successful. Maybe we could make a site that hints at naming conventions? Like now I think I understood, that I need to search for a name that starts with the second element from the pytorch names. Like here torch.distributions.normal is distr_normal. But it took me a while to get there.

I could even imagine that a "translator" script could be good. But I am not deep enough in the topic to try that on my own.

**Comment by dfalbel** [comment]
Thanks for the feedback! Yes, that makes sense, we should have a quick document mapping PyTorch namespaces to R function names.

For instance we have:

| PyTorch                       | torch          |
|-------------------------------|----------------|
| `torch.fun`                   | `torch_fun`    |
| `torch.nn.Module`             | `nn_module`    |
| `torch.nn.functional.fun`     | `nnf_fun`      |
| `torch.distributions.Normal`  | `distr_normal` |
