### ISSUE TITLE
Using JIT operators without writing wrappers

### ISSUE THREAD

**Issue by dfalbel** [mlverse/torch#929]
In python one can do something like:

```
import torch
torch.ops.load_library("build/libwarp_perspective.so")
print(torch.ops.my_ops.warp_perspective(torch.randn(32, 32), torch.rand(3, 3)))
```

In R, we have an equivalent for `torch.ops.load_library` but we can't really use the operations without writing C++ wrappers for them. We should be able to generate the wrappers using JIT types automatically, so users could do `ops$my_ops$warp_perspective` and access the operator with the JIT signature.

See more info [here](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html#using-the-torchscript-custom-operator-in-python)

**Comment by skeydan** [comment]
https://github.com/mlverse/torch/pull/1020, https://github.com/mlverse/torch/pull/1023
