### ISSUE TITLE
Compliment on your awesome work

### ISSUE THREAD

**Issue by vankesteren** [mlverse/torch#932]
Hey all, I just finished porting my library for estimating Structural Equation Models using Torch to R: [`tensorsem`](https://github.com/vankesteren/tensorsem). 

It previously was an awkward R + python hybrid package, with model specification in R and estimation in python (see [`here`](https://github.com/vankesteren/tensorsem/tree/v1.0))

It was really easy to do this rewrite! The experience was extremely smooth, basically everything I needed was there. My compliments to the `mlverse/torch` team 😄 

One sub-optimal thing I had was that I wanted to create an `nn_module` which has some additional methods, like `$loglik()` and `$partable()`. For this, I had to redo some `R6` class stuff and duplicate some code from `torch:::create_nn_module_callable()`, see here: https://github.com/vankesteren/tensorsem/blob/main/R/torch_sem.R#L27-L45

**Comment by dfalbel** [comment]
Hi @vankesteren 

Thanks very much for your message! `tensorsem` looks really nice!
In theory you can have `nn_modules` with as many arbitrary methods. For instance, you could do, to avoid the duplication. Would that work for you?

``` r
library(torch)

Module <- nn_module(
  "hello_world",
  initialize = function() {
    
  },
  forward = function(x) {
    x
  },
  loglik = function(x) {
    x
  },
  active = list(
    hello = function() {
      "world"
    }
  )
)

model <- Module()
model(1)
#> [1] 1
model$loglik(1)
#> [1] 1
model$hello
#> [1] "world"
```
