### ISSUE TITLE
missing torch_size 

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlverse/torch#934]
Hello!

in Python: 
`
>>> torch.rand(10).shape
torch.Size([10])
`
in R:
`
> torch_rand(10)$shape
[1] 10
`
So while Python gives us a torch.Size, R just gives an integer. This leads to problems further down the road when I sample from a distribution
`
distr_normal(0,1)$sample(10)
`
is different to the python
`
torch.distributions.Normal(0,1).sample(torch.Size([10]))
`
The sample function in Python does not accept integers at all, but it only accepts torch.Size([]) values. This breaks any translation attempt where a sample is drawn.

Will torch_size be implemented in the future, or is there a better way to do this? 
Thanks!

**Comment by dfalbel** [comment]
Hello @GitHubGeniusOverlord ,

Thanks for reaching out! 
Shapes in torch are always represented by integer vectors, so far this hasn't caused ambiguity thus we didn't implement a custom `Size` type like in Python.

In your example, I didn't follow the translation problem, it seems to be that

```
distr_normal(0,1)$sample(10)
```

is equivalent to:

```
torch.distributions.Normal(0,1).sample(torch.Size([10]))
```

or if referring to the shape of another tensor, you could do, just like in Python.

```
distr_normal(0,1)$sample(torch_rand(10)$shape)
```

**Comment by GitHubGeniusOverlord** [comment]
Hm, @dfalbel 

I don't think that 
`distr_normal(0,1)$sample(10)`
 and
`torch.distributions.Normal(0,1).sample(torch.Size([10]))`
are the same. The R output adds another dimension, while Python does not. 

As a result of this, when I multiply 
`distr_normal(0,1)$sample(10) * torch_rand(10)`, I get a
[ CPUFloatType{10,10} ]

while in Python, I would do 
`
x = torch.distributions.Normal(0,1).sample(torch.Size([10])) * torch.rand(10) 
x.shape
#torch.Size([10])
`
What am I missing?

**Comment by dfalbel** [comment]
Oh, I missed the shape difference. 

In Python, it seems that the behavior of `sample()` is different if `loc` and `scale` are scalar values or tensors. In R since, in general it's hard to disambiguate scalar values from 1-D tensors we opted for considering that `loc` is always a tensor like object, which is a questionable decision.

A way to get the same behavior is to make loc and scale scalar tensors, eg:

```
distr_normal(torch_scalar_tensor(0),torch_scalar_tensor(1))$sample(10)
```

This hits one of the hardest things when translating R to other languages. R values are always vectors, thus it's not possible to disambiguate between a vector with one element and a scalar. In general in torch we have been considering R objects always as tensors of length one and asking users to force scalar values with `torch_scalar_tensor()` when a scalar is really necessary. 

I'm not sure what would be best in this specific situation. Do you have thoughts?

**Comment by GitHubGeniusOverlord** [comment]
This really is a tough case for translation because the different behavior of distr_normal will first show, when you sample. And this made me assume, that the argument for the sample() function would need to be different. But actually it is like you showed. First note: My code works now. Thank You @dfalbel !

Translatability of the code will be very important. Maybe at some point we will have a vignette pointing at all that one needs to know to translate pytorch into torch. The sooner, the better! People should feel like it does not matter, which framework they use. At the moment it still feels like an extra large step to pick up the pytorch model and translate it. Once this step is eliminated or very small, torch can gain much more in popularity. 

Another idea would be to write a function that provides a basic code translation for models (if not for training). For many parts this would be just a string replacement operation. But then there would be situations like these, which the function would need to know about as well, which would make it very maintenance intensive.

**Comment by GitHubGeniusOverlord** [comment]
One more idea: Why not force inputs to the distr_normal to torch_scalar_tensor? Or maybe let the function have the option?

**Comment by GitHubGeniusOverlord** [comment]
@dfalbel 
I worked some more on this and found a follow up Problem.
Consider this model
`
simple_net <- nn_module(
  
  initialize = function() {
    
    self$normal <- distr_normal(torch_scalar_tensor(0),torch_scalar_tensor(1))

  },
  forward = function(x) {

    x <- self$normal$sample(x$shape)
    
    return(x)
  }
)

model <- simple_net()
torch_rand(10) %>% model()
model$to(device = "cuda")
torch_rand(10)$cuda() %>% model()
`
The model output will always be on cpu, even if I move the model to gpu. I tried all kinds of things, but there seems to be no way, to make it so that distr_normal$sample will automatically choose between cpu and gpu output. Other elements in the model can do this, like a linear layer. So if I want to combine the output with a linear layer and the output of distr_normal, I can only make one variant of the model work (device cpu or gpu) by forcing the output of distr_normal$sample to $cuda or not.

**Comment by dfalbel** [comment]
That happens because nn modules only track parameters and buffers in order to move them to the selected device. Distributions are not tracked at all by the nn_module unfortunately. 

You could do something like this though, so the output is always on the device the model has been moved to.

```
library(torch)
simple_net <- nn_module(
  initialize = function() {
    self$dummy_param <- nn_parameter(torch_tensor(1))
    self$normal <- distr_normal(torch_scalar_tensor(0),torch_scalar_tensor(1))
  },
  forward = function(x) {
    x <- self$normal$sample(x$shape)$to(device = self$dummy_param$device)
    return(x)
  }
)


m <- simple_net()
m(torch_randn(10))
```

**Comment by dfalbel** [comment]
> One more idea: Why not force inputs to the distr_normal to torch_scalar_tensor? Or maybe let the function have the option?

The problem with this approach is that a user that does:

```
distr_normal(0, 1)$sample()
```

gets the same result as someone doing:

```
distr_normal(c(0), c(1))$sample()
```

That's known to cause a lot of bugs in user code. For example, the fact that indexing data.frames with lenght 1 vectors vs length > 1 has caused a lot of hard to debug errors:
```
class(mtcars[1,1])
#> [1] "numeric"
class(mtcars[1, 1:2])
#> [1] "data.frame"
```
