### ISSUE TITLE
Support for CUDA 11.2 to run easily on colab 

### ISSUE THREAD

**Issue by ericdunipace** [mlverse/torch#946]
Hello,

I have attempted to run the following colab (https://colab.research.google.com/drive/1VQDSg5j2wfCTYqd0o9r8bfHQZMBIuz8w?usp=sharing) but get this message: `Cuda 11.2 detected but torch only supports: cpu, 10.2, 11.3, 11.6`. Further attempts to use the GPU generate errors, as one would expect.

This seems like the issue that was suggested by #579 . Currently, Colab supports CUDA 11.2 but the torch versions are unfortunately higher and lower. 

Alternatively, is it easy to add a specific CUDA version in my own version of torch on colab?

Thank you!

**Comment by dfalbel** [comment]
Hi @ericdunipace ,

We have worked on improving installation recently. We are now experimenting with providing pre-built binaries that bundle all necessary torch runtime dependencies. You can try in on colab with:

```
options(timeout=600)
kind <- "cu113" # "cpu", "cu113" are the only currently supported.
version <- "0.9.1.9000"
options(repos = c(
  torch = sprintf("https://storage.googleapis.com/torch-lantern-builds/packages/%s/%s/", kind, version),
  CRAN = "https://cloud.r-project.org" # or any other from which you want to install the other R dependencies.
))
install.packages("torch")
```

With that, CUDA version from host doesn't need to match the CUDA veersion PyTorch has been compiled with (CUDA doesn't even need to be installed actually). It should be much faster to install on Google Colab and other platforms too.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/4706822/216562079-ce90cf26-ebed-4c74-bd67-be62146ef98a.png">

**Comment by ericdunipace** [comment]
Hi @dfalbel ,

This worked wonderfully! Thank you for your help.
