### ISSUE TITLE
'glue' should be an import

### ISSUE THREAD

**Issue by shikokuchuo** [mlverse/torch#958]
'glue' should be under 'imports' rather than 'suggests' as it is a hard dependency (used in conditions.R and distributions-constraints.R). Currently installing 'torch' does not automatically install 'glue' and it will proceed to error with package not found.

**Comment by skeydan** [comment]
Thanks for reporting! Will be fixed in #960.

**Comment by shikokuchuo** [comment]
Thanks for this. Makes for a cleaner install e.g. in a new cloud instance.
