### ISSUE TITLE
Dataloader drops dimensions

### ISSUE THREAD

**Issue by opasche** [mlverse/torch#961]
Hello,

I've noticed the dataloader simplifies/drops dimensions if they equal 1, which is unexpected.

In particular, if the number of observations in a sampled batch equals one, the "batch" dimension will be simplified.

Example:

    ds <- tensor_dataset(torch_rand(11,3), torch_rand(11,1))
    loader <- dataloader(ds, batch_size=10, shuffle=TRUE)
    coro::loop(for (b in loader) {
        print(b[[1]]$shape)
    })

outputs:

    [1] 10  3
    [1] 3

instead of what would be expected:

    [1] 10  3
    [1] 1 3

I haven't investigated whether it's specifically from the dataloader, or if it inherits this behaviour from another function (that might not be supposed to simplify either).

**Comment by opasche** [comment]
Thank you for the fix!

**Comment by dfalbel** [comment]
Thank you @opasche for reporting!
