### ISSUE TITLE
Deep Cloning of modules

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torch#968]
I am trying to figure out a way to create a deep clone of a torch module. 
While trying out different approaches  I discovered some unexpected behavior that I am documenting here. 

The tricky part about creating the deep clone is to preserve reference semantics. 
Therefore I picked the otherwise randomly seeming example below, where a deep clone should preserve the references, i.e. that weight1 and weight2 point to the same parameter. 

``` r
library(torch)

nn_custom = nn_module("nn_custom",
  initialize = function() {
    w = nn_parameter(torch_randn(1, 1))
    self$weight1 = w
    self$weight2 = w
  }
)

net = nn_custom()


# This returns only weight1
net$named_parameters(TRUE)
#> $weight1
#> torch_tensor
#> -2.2368
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
# This returns weight1 and weight2
net$named_parameters(FALSE)
#> $weight1
#> torch_tensor
#> -2.2368
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
#> 
#> $weight2
#> torch_tensor
#> -2.2368
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]

# This does not work, because `$register_parameter()` is not called.
# I would expect it to work though or at least throw a warning
net$weight1 = torch_clone(net$weight1) + 1000
net$weight1
#> torch_tensor
#> -2.2368
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
# This does work
net$weight1 = nn_parameter(torch_clone(net$weight1) + 1000)
net$weight1
#> torch_tensor
#>  997.7632
#> [ CPUFloatType{1,1} ][ grad_fn = <AddBackward1> ]

# Also I was surprised to observe the following:
net = nn_custom()
net1 = net$clone(deep = TRUE)

state = lapply(net1$state_dict(), function(x) nn_parameter(torch_clone(x) + 1000))

net1$load_state_dict(state)

net$weight1
#> torch_tensor
#>  1001.7814
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
net1$weight1
#> torch_tensor
#>  1001.7814
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
```

<sup>Created on 2023-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sebffischer** [comment]
Similar things as the ones mentioned above can also be observed for buffers and (sub-)modules of a module.

**Comment by sebffischer** [comment]
It would actually be great if there as a function provided by the `torch` package to allow for deep cloning of modules!

**Comment by sebffischer** [comment]
Maybe one could add an `inplace` argument to the `load_state_dict` method to replace the `$copy_()` with a `$copy()` call" https://github.com/mlverse/torch/blob/8369336cc25df518f6791917ad2653661b1f1a28/R/nn.R#L174

It would also be great if something like that was available for optimizers.

**Comment by dfalbel** [comment]
Makes sense! It would be great to have a built-in way of deep cloning modules. Currently I think the somewhat hacky way is to serialize and reload, eg:

``` r
library(torch)

nn_custom = nn_module(
  "nn_custom",
  initialize = function() {
    w = nn_parameter(torch_randn(1, 1))
    self$weight1 = w
    self$weight2 = w
  }
)

net1 = nn_custom()

tmp <- tempfile()
torch_save(net1, tmp)
net2 <- torch_load(tmp)

with_no_grad({net2$weight1$add_(1000)})
#> torch_tensor
#>  1001.5737
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]

net2$parameters
#> $weight1
#> torch_tensor
#>  1001.5737
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
net1$parameters
#> $weight1
#> torch_tensor
#>  1.5737
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
```

**Comment by dfalbel** [comment]
```
# This does not work, because `$register_parameter()` is not called.
# I would expect it to work though or at least throw a warning
net$weight1 = torch_clone(net$weight1) + 1000
net$weight1
```

I think we should throw a warning here. If a `nn_parameter` already exists with that name, then reassigning a 'non-parameter' to the same name is probably a mistake.

**Comment by dfalbel** [comment]
```
# This returns only weight1
net$named_parameters(TRUE)
#> $weight1
#> torch_tensor
#> -2.2368
#> [ CPUFloatType{1,1} ][ requires_grad = TRUE ]
# This returns weight1 and weight2
net$named_parameters(FALSE)
```

This is a bug. We should only ever return unique tensors.
We could potentially make it an error to assign the same tensor to multiple names within a module to avoid having to handle this case.
