### ISSUE TITLE
CUDA version 11.3 only available for Windows 10

### ISSUE THREAD

**Issue by farach** [mlverse/torch#973]
I was attempting to run Torch for R using local GPUs. Torch for R only works with CUDA version 11.3 if running on Windows. To install CUDA version 11.3 one must have Windows 10 installed.

![Screenshot 2023-01-29 135144](https://user-images.githubusercontent.com/1520139/215349176-db12149d-fcaf-4cf8-86e6-2373b73755a0.jpg)

Is there plans to have Torch for R support a CUDA version that works with Windows 11?

**Comment by dfalbel** [comment]
Hi @farach,

The windows10 version should also work on windows 11. I recently tried on a win11 machine and installation went smoothly.

That said, I'm experimenting with providing pre-built CUDA enabled binaries for torch, so you can install it without installing CUDA, cuDNN or any additional software and would love to get some feedback. If you are into trying it you can run:

```
kind <- "cu11.3" # "cpu", "cu113" are the only currently supported.
version <- "0.9.1.9000"
option(repos = c(
  torch = sprintf("https://storage.googleapis.com/torch-lantern-builds/packages/%s/%s/", kind, version),
  CRAN = "https://cloud.r-project.org" # or any other from which you want to install the other R dependencies.
))
install.packages("torch")
```

In this case, you woudn't need to install CUDA above at all.

**Comment by VladPerervenko** [comment]
Failure. Cause?
> kind <- "cu11.3" # "cpu", "cu113" are the only currently supported.
> version <- "0.9.1.9000"
> options(repos = c(torch = sprintf("https://storage.googleapis.com/torch-lantern-builds/packages/%s/%s/", kind, version),     CRAN = "https://cloud.r-project.org" # or any other from which you want to install the other R dependencies.))
> install.packages("torch")
Устанавливаю пакет в ‘C:/Users/User/AppData/Local/R/win-library/4.2’
(потому что ‘lib’ не определено)
trying URL 'https://storage.googleapis.com/torch-lantern-builds/packages/cu11.3/0.9.1.9000/bin/windows/contrib/4.2/torch_0.9.1.9000.zip'
downloaded 639.9 MB

Warning in install.packages :
  URL 'https://storage.googleapis.com/torch-lantern-builds/packages/cu11.3/0.9.1.9000/bin/windows/contrib/4.2/torch_0.9.1.9000.zip': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://storage.googleapis.com/torch-lantern-builds/packages/cu11.3/0.9.1.9000/bin/windows/contrib/4.2/torch_0.9.1.9000.zip' failed
Warning in install.packages :
  скачивание пакета ‘torch’ не удалось

> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.utf8  LC_CTYPE=Russian_Russia.utf8   
[3] LC_MONETARY=Russian_Russia.utf8 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2

**Comment by VladPerervenko** [comment]
Just downloaded the zip file. Continue to R
`> install.packages("C:/Users/User/Downloads/torch_0.9.1.9000.zip", repos = NULL, type = "win.binary")
Устанавливаю пакет в ‘C:/Users/User/AppData/Local/R/win-library/4.2’
(потому что ‘lib’ не определено)
пакет ‘torch’ успешно распакован, MD5-суммы проверены`
The package installed fine. How to check if the graphics card is working?

**Comment by VladPerervenko** [comment]
Sorry. Understood
`> library(torch)
> backends_cudnn_is_available()
[1] TRUE
> backends_cudnn_version()
[1] ‘8.3.2’
> backends_mkldnn_is_available()
[1] TRUE
> backends_mkl_is_available()
[1] TRUE
> backends_mps_is_available()
[1] FALSE
> backends_openmp_is_available()
[1] TRUE
> cuda_current_device()
[1] 0
> cuda_device_count()
[1] 1
> cuda_empty_cache()
> cuda_get_device_capability(device = cuda_current_device())
Major Minor 
    8     6 
> cuda_is_available()
[1] TRUE`
