### ISSUE TITLE
Support Metal Performance Shaders (MPS) backend for GPU acceleration on Apple Silicon

### ISSUE THREAD

**Issue by rosericazondekon** [mlverse/torch#997]
Dear mlverse developers,
Pytorch Preview (Nightly) supports MPS backend for GPU acceleration. Would it be possible to do the same for R torch? On October 5, 2022, you released a libtorch binary for R. Does it support MPS backend for GPU acceleration on M1 and M2 Macs?
Thanks for the wonderful job!

**Comment by dfalbel** [comment]
Hi,

Yes, this is supported. Operations on Tensors that are allocated on the `'mps'` device will bennefit from GPU acceleration. 
Eg:

``` r
library(torch)

x_cpu <- torch_randn(10000, 10000)
x_mps <- x_cpu$to(device="mps")

bench::mark(
  torch_mm(x_cpu, x_cpu),
  torch_mm(x_mps, x_mps), 
  check = FALSE
)
#> # A tibble: 2 × 6
#>   expression                  min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>             <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 torch_mm(x_cpu, x_cpu)    1.14s    1.14s     0.876   16.41KB        0
#> 2 torch_mm(x_mps, x_mps) 113.45µs 145.53µs    36.7      4.98KB        0
```

<sup>Created on 2023-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rosericazondekon** [comment]
This is awesome.
PyTorch has a `torch.backends.mps.is_available()` function to check for `MPS` support. Are you planning to add a `mps_is_available()` function to `torch`?

**Comment by dfalbel** [comment]
You can use: ```torch::backends_mps_is_available()```
