### ISSUE TITLE
Temporarily change torch seed

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torch#998]
In a function I want to set the torch seed using `torch::torch_manual_seed()` to a specific value. 
When exiting the function, I would like to reset the seed to its previous state. 

Is this currently possible?

**Comment by dfalbel** [comment]
I don't think that's possible at the moment. I **think** we can make it work for CPU by wraping `get_rng_state()` and `set_rng_state()` (https://pytorch.org/docs/stable/_modules/torch/random.html#get_rng_state), but unlikely for CUDA or other devices. Do you know if that's possible in PyTorch?

**Comment by dfalbel** [comment]
Oh! i missed it! yeah, sounds possible! will try to implement it soon

**Comment by sebffischer** [comment]
Thanks! :)
